// stimulus_current.svh — generated for trigger_output_xsim
// Generated by gen_stimulus.py — DO NOT EDIT
// Source: trigger_demo_golden.xml
//
// Defines task run_stimulus() — called from the TB initial block
// after reset/idle phases.  Uses $fatal(1,...) on any assertion failure.

task automatic run_stimulus();
  integer _fail;
  _fail = 0;

  // Event 0: accept=1 quality=3 → word=0x80030000
  @(posedge ap_clk);
  trigger_accept  = 1'b1;
  trigger_quality = 8'd3;
  trigger_valid   = 1'b1;
  #1;  // combinational settle
  if (trigger_word !== 32'h80030000) begin $display("FAIL [E0] trigger_word=0x%08X expect=0x80030000", trigger_word); _fail = 1; end
  if (out_valid !== 1'b1) begin $display("FAIL [E0] out_valid=%0b expect=1", out_valid); _fail = 1; end

  // Event 1: accept=0 quality=1 → word=0x00010000
  @(posedge ap_clk);
  trigger_accept  = 1'b0;
  trigger_quality = 8'd1;
  trigger_valid   = 1'b1;
  #1;  // combinational settle
  if (trigger_word !== 32'h00010000) begin $display("FAIL [E1] trigger_word=0x%08X expect=0x00010000", trigger_word); _fail = 1; end
  if (out_valid !== 1'b1) begin $display("FAIL [E1] out_valid=%0b expect=1", out_valid); _fail = 1; end

  // Event 2: accept=1 quality=4 → word=0x80040000
  @(posedge ap_clk);
  trigger_accept  = 1'b1;
  trigger_quality = 8'd4;
  trigger_valid   = 1'b1;
  #1;  // combinational settle
  if (trigger_word !== 32'h80040000) begin $display("FAIL [E2] trigger_word=0x%08X expect=0x80040000", trigger_word); _fail = 1; end
  if (out_valid !== 1'b1) begin $display("FAIL [E2] out_valid=%0b expect=1", out_valid); _fail = 1; end

  // Event 3: accept=0 quality=0 → word=0x00000000
  @(posedge ap_clk);
  trigger_accept  = 1'b0;
  trigger_quality = 8'd0;
  trigger_valid   = 1'b0;
  #1;  // combinational settle
  if (trigger_word !== 32'h00000000) begin $display("FAIL [E3] trigger_word=0x%08X expect=0x00000000", trigger_word); _fail = 1; end
  if (out_valid !== 1'b0) begin $display("FAIL [E3] out_valid=%0b expect=0", out_valid); _fail = 1; end

  if (_fail) $fatal(1, "TB FAIL: trigger_output_xsim — %0d assertion(s) failed", _fail);
endtask
