// ============================================================
// tb_trigger_output_xsim.sv — Generated by gen-sim
// Flow:         trigger_output_xsim
// Top module:   trigger_output
// Generated at: 2026-04-28 16:38 UTC
// DO NOT EDIT — regenerate with: gen-sim trigger_output_xsim
// ============================================================
`timescale 1ns/1ps

module tb_trigger_output_xsim;

  // ── Timing parameters ────────────────────────────────────
  localparam real CLK_PERIOD_NS              = 4.0;
  localparam int  RESET_CYCLES               = 4;
  localparam int  IDLE_CYCLES_AFTER_RESET    = 0;
  localparam int  POST_STIMULUS_DRAIN_CYCLES = 4;

  // ── Clock and reset ──────────────────────────────────────
  logic ap_clk;
  logic ap_rst;

  initial ap_clk = 1'b0;
  always #(CLK_PERIOD_NS / 2.0) ap_clk = ~ap_clk;

    `ifndef PROBE_LOG
    localparam int PROBE_LOG = 0;
    `else
    localparam int PROBE_LOG = `PROBE_LOG;
    `endif

  // ── DUT signals (from port_map) ───────────────────────
  logic trigger_accept;
  logic [7:0] trigger_quality;
  logic trigger_valid;
  wire  [31:0] trigger_word;
  wire  out_valid;


  // ── Stimulus ─────────────────────────────────────────────
  `include "stimulus_current.svh"

  // ── DUT instantiation ────────────────────────────────────
  trigger_output dut (
    .trigger_accept(trigger_accept),
    .trigger_quality(trigger_quality),
    .trigger_valid(trigger_valid),
    .trigger_word(trigger_word),
    .out_valid(out_valid),
    .ap_rst(ap_rst)
  );

  // ── Cycle counter ────────────────────────────────────────
  integer cycle_count;

  // ── Output trace ─────────────────────────────────────────
  integer trace_fd;
    integer probe_fd;

  // ── Main test sequence ──────────────────────────────────
  initial begin
    cycle_count = 0;
    ap_rst      = 1'b1;
    trigger_accept = '0;
    trigger_quality = '0;
    trigger_valid = '0;

    trace_fd = $fopen("trigger_output_outputs.csv", "w");
    $fwrite(trace_fd, "cycle,trigger_word,out_valid\n");


    // Reset phase
    repeat (RESET_CYCLES) @(posedge ap_clk);
    ap_rst = 1'b0;

    // Idle settle phase
    repeat (IDLE_CYCLES_AFTER_RESET) @(posedge ap_clk);

    // Stimulus phase
    run_stimulus();  // defined in stimulus_current.svh (framework-standard handoff contract)

    // Drain phase
    repeat (POST_STIMULUS_DRAIN_CYCLES) @(posedge ap_clk);

    $fclose(trace_fd);

    $display("TB PASS: trigger_output_xsim completed");
    $finish;
  end

  // ── Output logging ───────────────────────────────────────
  always @(posedge ap_clk) begin
    if (!ap_rst) begin
      $fwrite(trace_fd, "%0d,%0h,%0b\n", cycle_count, trigger_word, out_valid);

      cycle_count <= cycle_count + 1;
    end
  end

endmodule
