// stimulus_current.svh — generated for hit_decoder_xsim
// Generated by gen_stimulus.py — DO NOT EDIT
// Source: trigger_demo_golden.xml
//
// Defines task run_stimulus() — called from the TB initial block
// after reset/idle phases.  Uses $fatal(1,...) on any assertion failure.

task automatic run_stimulus();
  integer _fail;
  _fail = 0;

  // Event 0 ch0: raw=0x00A00050 valid=1  →  decoded=0x00A10050 valid=1
  @(posedge ap_clk);
  raw_hit   = 32'h00A00050;
  raw_valid = 1'b1;
  #1;  // combinational settle
  if (decoded_hit !== 32'h00A10050) begin $display("FAIL [E0.ch0] decoded_hit=0x%08X expect=0x00A10050", decoded_hit); _fail = 1; end
  if (decoded_valid !== 1'b1) begin $display("FAIL [E0.ch0] decoded_valid=%0b expect=1", decoded_valid); _fail = 1; end

  // Event 0 ch1: raw=0x00B00060 valid=1  →  decoded=0x00B10060 valid=1
  @(posedge ap_clk);
  raw_hit   = 32'h00B00060;
  raw_valid = 1'b1;
  #1;  // combinational settle
  if (decoded_hit !== 32'h00B10060) begin $display("FAIL [E0.ch1] decoded_hit=0x%08X expect=0x00B10060", decoded_hit); _fail = 1; end
  if (decoded_valid !== 1'b1) begin $display("FAIL [E0.ch1] decoded_valid=%0b expect=1", decoded_valid); _fail = 1; end

  // Event 0 ch2: raw=0x00000000 valid=0  →  decoded=0x00010000 valid=0
  @(posedge ap_clk);
  raw_hit   = 32'h00000000;
  raw_valid = 1'b0;
  #1;  // combinational settle
  if (decoded_valid !== 1'b0) begin $display("FAIL [E0.ch2] decoded_valid=%0b expect=0", decoded_valid); _fail = 1; end

  // Event 0 ch3: raw=0x00C00070 valid=1  →  decoded=0x00C10070 valid=1
  @(posedge ap_clk);
  raw_hit   = 32'h00C00070;
  raw_valid = 1'b1;
  #1;  // combinational settle
  if (decoded_hit !== 32'h00C10070) begin $display("FAIL [E0.ch3] decoded_hit=0x%08X expect=0x00C10070", decoded_hit); _fail = 1; end
  if (decoded_valid !== 1'b1) begin $display("FAIL [E0.ch3] decoded_valid=%0b expect=1", decoded_valid); _fail = 1; end

  // Event 1 ch0: raw=0x00D00080 valid=1  →  decoded=0x00D10080 valid=1
  @(posedge ap_clk);
  raw_hit   = 32'h00D00080;
  raw_valid = 1'b1;
  #1;  // combinational settle
  if (decoded_hit !== 32'h00D10080) begin $display("FAIL [E1.ch0] decoded_hit=0x%08X expect=0x00D10080", decoded_hit); _fail = 1; end
  if (decoded_valid !== 1'b1) begin $display("FAIL [E1.ch0] decoded_valid=%0b expect=1", decoded_valid); _fail = 1; end

  // Event 1 ch1: raw=0x00000000 valid=0  →  decoded=0x00010000 valid=0
  @(posedge ap_clk);
  raw_hit   = 32'h00000000;
  raw_valid = 1'b0;
  #1;  // combinational settle
  if (decoded_valid !== 1'b0) begin $display("FAIL [E1.ch1] decoded_valid=%0b expect=0", decoded_valid); _fail = 1; end

  // Event 1 ch2: raw=0x00000000 valid=0  →  decoded=0x00010000 valid=0
  @(posedge ap_clk);
  raw_hit   = 32'h00000000;
  raw_valid = 1'b0;
  #1;  // combinational settle
  if (decoded_valid !== 1'b0) begin $display("FAIL [E1.ch2] decoded_valid=%0b expect=0", decoded_valid); _fail = 1; end

  // Event 1 ch3: raw=0x00000000 valid=0  →  decoded=0x00010000 valid=0
  @(posedge ap_clk);
  raw_hit   = 32'h00000000;
  raw_valid = 1'b0;
  #1;  // combinational settle
  if (decoded_valid !== 1'b0) begin $display("FAIL [E1.ch3] decoded_valid=%0b expect=0", decoded_valid); _fail = 1; end

  // Event 2 ch0: raw=0x01000100 valid=1  →  decoded=0x01010100 valid=1
  @(posedge ap_clk);
  raw_hit   = 32'h01000100;
  raw_valid = 1'b1;
  #1;  // combinational settle
  if (decoded_hit !== 32'h01010100) begin $display("FAIL [E2.ch0] decoded_hit=0x%08X expect=0x01010100", decoded_hit); _fail = 1; end
  if (decoded_valid !== 1'b1) begin $display("FAIL [E2.ch0] decoded_valid=%0b expect=1", decoded_valid); _fail = 1; end

  // Event 2 ch1: raw=0x02000200 valid=1  →  decoded=0x02010200 valid=1
  @(posedge ap_clk);
  raw_hit   = 32'h02000200;
  raw_valid = 1'b1;
  #1;  // combinational settle
  if (decoded_hit !== 32'h02010200) begin $display("FAIL [E2.ch1] decoded_hit=0x%08X expect=0x02010200", decoded_hit); _fail = 1; end
  if (decoded_valid !== 1'b1) begin $display("FAIL [E2.ch1] decoded_valid=%0b expect=1", decoded_valid); _fail = 1; end

  // Event 2 ch2: raw=0x03000300 valid=1  →  decoded=0x03010300 valid=1
  @(posedge ap_clk);
  raw_hit   = 32'h03000300;
  raw_valid = 1'b1;
  #1;  // combinational settle
  if (decoded_hit !== 32'h03010300) begin $display("FAIL [E2.ch2] decoded_hit=0x%08X expect=0x03010300", decoded_hit); _fail = 1; end
  if (decoded_valid !== 1'b1) begin $display("FAIL [E2.ch2] decoded_valid=%0b expect=1", decoded_valid); _fail = 1; end

  // Event 2 ch3: raw=0x04000400 valid=1  →  decoded=0x04010400 valid=1
  @(posedge ap_clk);
  raw_hit   = 32'h04000400;
  raw_valid = 1'b1;
  #1;  // combinational settle
  if (decoded_hit !== 32'h04010400) begin $display("FAIL [E2.ch3] decoded_hit=0x%08X expect=0x04010400", decoded_hit); _fail = 1; end
  if (decoded_valid !== 1'b1) begin $display("FAIL [E2.ch3] decoded_valid=%0b expect=1", decoded_valid); _fail = 1; end

  // Event 3 ch0: raw=0x00000000 valid=0  →  decoded=0x00010000 valid=0
  @(posedge ap_clk);
  raw_hit   = 32'h00000000;
  raw_valid = 1'b0;
  #1;  // combinational settle
  if (decoded_valid !== 1'b0) begin $display("FAIL [E3.ch0] decoded_valid=%0b expect=0", decoded_valid); _fail = 1; end

  // Event 3 ch1: raw=0x00000000 valid=0  →  decoded=0x00010000 valid=0
  @(posedge ap_clk);
  raw_hit   = 32'h00000000;
  raw_valid = 1'b0;
  #1;  // combinational settle
  if (decoded_valid !== 1'b0) begin $display("FAIL [E3.ch1] decoded_valid=%0b expect=0", decoded_valid); _fail = 1; end

  // Event 3 ch2: raw=0x00000000 valid=0  →  decoded=0x00010000 valid=0
  @(posedge ap_clk);
  raw_hit   = 32'h00000000;
  raw_valid = 1'b0;
  #1;  // combinational settle
  if (decoded_valid !== 1'b0) begin $display("FAIL [E3.ch2] decoded_valid=%0b expect=0", decoded_valid); _fail = 1; end

  // Event 3 ch3: raw=0x00000000 valid=0  →  decoded=0x00010000 valid=0
  @(posedge ap_clk);
  raw_hit   = 32'h00000000;
  raw_valid = 1'b0;
  #1;  // combinational settle
  if (decoded_valid !== 1'b0) begin $display("FAIL [E3.ch3] decoded_valid=%0b expect=0", decoded_valid); _fail = 1; end

  if (_fail) $fatal(1, "TB FAIL: hit_decoder_xsim — %0d assertion(s) failed", _fail);
endtask
