// ============================================================
// tb_hit_decoder_xsim.sv — Generated by gen-sim
// Flow:         hit_decoder_xsim
// Top module:   hit_decoder
// Generated at: 2026-07-27 17:46 UTC
// DO NOT EDIT — regenerate with: gen-sim hit_decoder_xsim
// ============================================================
`timescale 1ns/1ps

module tb_hit_decoder_xsim;

  // ── Timing parameters ────────────────────────────────────
  localparam real CLK_PERIOD_NS              = 4.0;
  localparam int  RESET_CYCLES               = 4;
  localparam int  IDLE_CYCLES_AFTER_RESET    = 0;
  localparam int  POST_STIMULUS_DRAIN_CYCLES = 4;

  // ── Clock and reset ──────────────────────────────────────
  logic ap_clk;
  logic ap_rst;

  initial ap_clk = 1'b0;
  always #(CLK_PERIOD_NS / 2.0) ap_clk = ~ap_clk;

    `ifndef PROBE_LOG
    localparam int PROBE_LOG = 0;
    `else
    localparam int PROBE_LOG = `PROBE_LOG;
    `endif

  // ── DUT signals (from port_map) ───────────────────────
  logic [31:0] raw_hit;
  logic raw_valid;
  wire  [31:0] decoded_hit;
  wire  decoded_valid;


  // ── Stimulus ─────────────────────────────────────────────
  `include "stimulus_current.svh"

  // ── DUT instantiation ────────────────────────────────────
  hit_decoder dut (
    .raw_hit(raw_hit),
    .raw_valid(raw_valid),
    .decoded_hit(decoded_hit),
    .decoded_valid(decoded_valid),
    .ap_rst(ap_rst)
  );

  // ── Cycle counter ────────────────────────────────────────
  integer cycle_count;

  // ── Output trace ─────────────────────────────────────────
  integer trace_fd;
    integer probe_fd;

  // ── Main test sequence ──────────────────────────────────
  initial begin
    cycle_count = 0;
    ap_rst      = 1'b1;
    raw_hit = '0;
    raw_valid = '0;

    trace_fd = $fopen("hit_decoder_outputs.csv", "w");
    $fwrite(trace_fd, "cycle,decoded_hit,decoded_valid\n");


    // Reset phase
    repeat (RESET_CYCLES) @(posedge ap_clk);
    ap_rst = 1'b0;

    // Idle settle phase
    repeat (IDLE_CYCLES_AFTER_RESET) @(posedge ap_clk);

    // Stimulus phase
    run_stimulus();  // defined in stimulus_current.svh (framework-standard handoff contract)

    // Drain phase
    repeat (POST_STIMULUS_DRAIN_CYCLES) @(posedge ap_clk);

    $fclose(trace_fd);

    $display("TB PASS: hit_decoder_xsim completed");
    $finish;
  end

  // ── Output logging ───────────────────────────────────────
  always @(posedge ap_clk) begin
    if (!ap_rst) begin
      $fwrite(trace_fd, "%0d,%0h,%0b\n", cycle_count, decoded_hit, decoded_valid);

      cycle_count <= cycle_count + 1;
    end
  end

endmodule
