"""CLI reference generator — walks the real,
live ``build_parser()`` tree so ``docs/reference/cli.md`` cannot drift
from the actual registered commands and flags.

The subparser-walking approach (``_subparsers_action``/``_iter_command_tree``)
intentionally mirrors the pattern already established and tested in
``forge/tests/test_cli_help_consistency.py`` rather than a second,
potentially-diverging reimplementation of argparse introspection — it is
duplicated here (not imported) only because test modules aren't part of
the installed package.
"""
from __future__ import annotations

import os
from argparse import ArgumentParser, _SubParsersAction
from typing import Iterator, Tuple

from forge.core.cli.main import build_parser
from forge.verify.__main__ import build_parser as build_verify_parser

# forge verify delegates its own subcommand tree to a separate parser via
# REMAINDER (forge/core/cli/groups/verify.py::cmd_verify_dispatch) — it's a
# leaf in the main tree, so its real subcommands are walked separately here.
_DELEGATED_GROUP_PARSERS = {"verify": build_verify_parser}

# Pinned so generated help text never depends on the terminal width of
# whichever machine/CI runner regenerates it — the same determinism
# requirement already established for field-type strings, extended here
# to argparse's own help formatting.
_PINNED_COLUMNS = "100"


def _subparsers_action(parser: ArgumentParser) -> "_SubParsersAction | None":
    for action in parser._actions:
        if isinstance(action, _SubParsersAction):
            return action
    return None


def _iter_command_tree(
    parser: ArgumentParser, prefix: "Tuple[str, ...]" = (),
) -> "Iterator[Tuple[Tuple[str, ...], ArgumentParser]]":
    """Yield ``(path, parser)`` for every leaf and intermediate subcommand."""
    yield prefix, parser
    action = _subparsers_action(parser)
    if action is None:
        return
    for name, sub in action.choices.items():
        yield from _iter_command_tree(sub, prefix + (name,))


def _build_full_tree() -> "dict[Tuple[str, ...], ArgumentParser]":
    tree: "dict[Tuple[str, ...], ArgumentParser]" = {}
    for path, parser in _iter_command_tree(build_parser()):
        tree[path] = parser
    # Overwrites the thin top-level "verify" leaf with the real delegated
    # parser at the same path, then adds its real subcommands beneath it.
    for group_name, build_delegate in _DELEGATED_GROUP_PARSERS.items():
        for path, parser in _iter_command_tree(build_delegate(), (group_name,)):
            tree[path] = parser
    return tree


def _heading_level(path: "Tuple[str, ...]") -> str:
    return "#" * min(2 + len(path), 6)


def generate_cli_reference_page() -> str:
    """Return the complete, deterministic Markdown content for
    ``docs/reference/cli.md``."""
    old_columns = os.environ.get("COLUMNS")
    os.environ["COLUMNS"] = _PINNED_COLUMNS
    try:
        tree = _build_full_tree()

        lines = [
            "# CLI Reference",
            "",
            "<!-- Generated by `python -m forge.docsgen`. Do not edit directly. -->",
            "",
            "Generated directly from the live `forge` argument parser",
            "(`forge.core.cli.main.build_parser()`), so this reference cannot",
            "silently drift from the real registered commands and flags. See",
            "[CLI Exit Codes](../development/cli_exit_codes.md) for the shared",
            "exit-code / `--json` envelope contract every command follows.",
            "",
        ]
        for path in sorted(tree.keys()):
            parser = tree[path]
            label = "forge " + " ".join(path) if path else "forge"
            lines.append(f"{_heading_level(path)} `{label}`")
            lines.append("")
            lines.append("```text")
            lines.append(parser.format_help().rstrip())
            lines.append("```")
            lines.append("")
        return "\n".join(lines).rstrip() + "\n"
    finally:
        if old_columns is None:
            os.environ.pop("COLUMNS", None)
        else:
            os.environ["COLUMNS"] = old_columns
