"""Public Python API inventory generator.

Discovers FORGE's stable Python API the same way an external caller would
find it: by walking every ``forge`` submodule and reading each module's own
``__all__``. There is no separate hand-maintained list to drift from the
real package — the rule this generator enforces (and the release plan
states explicitly) is:

- only symbols listed in a module's ``__all__`` are stable;
- a name beginning with ``_`` is unsupported even if a module lists it in
  ``__all__`` — that's a pre-existing inconsistency this generator reports
  as an excluded/warning entry rather than silently promoting it to public
  API status.
"""
from __future__ import annotations

import importlib
import inspect
import pkgutil
from dataclasses import dataclass
from typing import Any

import forge


@dataclass(frozen=True)
class PublicSymbol:
    module: str
    name: str
    kind: str  # "class" | "function" | "value"
    summary: str


def _first_doc_line(obj: Any) -> str:
    doc = inspect.getdoc(obj) or ""
    return doc.strip().splitlines()[0].strip() if doc.strip() else ""


def _classify(obj: Any) -> str:
    if inspect.isclass(obj):
        return "class"
    if inspect.isfunction(obj) or inspect.isbuiltin(obj):
        return "function"
    return "value"


def discover_public_api() -> "tuple[list[PublicSymbol], list[PublicSymbol]]":
    """Walk every ``forge`` submodule for ``__all__``.

    Returns ``(public, excluded_private)`` — ``excluded_private`` holds
    ``__all__`` entries that start with ``_`` (unsupported per policy,
    listed separately rather than silently dropped so the inconsistency
    stays visible).
    """
    public: "list[PublicSymbol]" = []
    excluded: "list[PublicSymbol]" = []

    def _record(module: Any) -> None:
        # Resolved immediately on import, before any submodule import can
        # shadow a same-named attribute on *module* (Python's import
        # system binds an imported submodule as an attribute of its
        # parent package — e.g. importing forge.core.cli.main would
        # otherwise silently replace forge.core.cli's own `main`
        # function with the submodule object).
        all_names = getattr(module, "__all__", None)
        if not all_names:
            return
        for name in all_names:
            obj = getattr(module, name, None)
            entry = PublicSymbol(
                module=module.__name__,
                name=name,
                kind=_classify(obj) if obj is not None else "value",
                summary=_first_doc_line(obj) if obj is not None else "",
            )
            # Dunder names (e.g. __version__) are a standard, legitimate
            # public convention — distinct from a single-leading-
            # underscore "private" name, which is what's actually
            # unsupported.
            is_private = name.startswith("_") and not (name.startswith("__") and name.endswith("__"))
            (excluded if is_private else public).append(entry)

    _record(forge)
    for info in pkgutil.walk_packages(forge.__path__, prefix="forge."):
        if ".tests" in f".{info.name}." or info.name.endswith(".tests"):
            continue
        try:
            module = importlib.import_module(info.name)
        except BaseException:
            # Not every submodule is import-safe standalone (e.g. CLI
            # entry points/scripts with side-effecting top-level code,
            # some of which call sys.exit() on missing optional tooling —
            # SystemExit isn't an Exception, hence the broad catch here).
            # Skip it: a module that can't even be imported declares no
            # public API.
            continue
        _record(module)

    public.sort(key=lambda s: (s.module, s.name))
    excluded.sort(key=lambda s: (s.module, s.name))
    return public, excluded


def generate_public_api_page() -> str:
    public, excluded = discover_public_api()

    lines = [
        "# Public Python API",
        "",
        "<!-- Generated by `python -m forge.docsgen`. Do not edit directly. -->",
        "",
        "This page is the complete, real public Python API surface: every",
        "symbol listed in a `forge` submodule's own `__all__`. Only symbols",
        "on this page are stable across minor releases — anything else",
        "(including any name not listed here, even if importable) is",
        "internal and may change or move without notice. Import from the",
        "module shown in the **Module** column, not from a deeper internal",
        "path.",
        "",
        "| Module | Symbol | Kind | Summary |",
        "|---|---|---|---|",
    ]
    for s in public:
        summary = s.summary.replace("|", "\\|")
        lines.append(f"| `{s.module}` | `{s.name}` | {s.kind} | {summary} |")

    if excluded:
        lines += [
            "",
            "## Known inconsistencies",
            "",
            "The following names are listed in a module's `__all__` but begin",
            "with `_` — private-by-naming-convention. Per policy, a leading",
            "`_` makes a name unsupported regardless of `__all__` membership,",
            "so these are **not** part of the stable API above. Listed here so",
            "the inconsistency stays visible instead of silently promoting",
            "them:",
            "",
        ]
        for s in excluded:
            lines.append(f"- `{s.module}.{s.name}`")

    lines.append("")
    return "\n".join(lines)


def build_inventory() -> "dict[str, Any]":
    public, excluded = discover_public_api()
    return {
        "forge_version": forge.__version__,
        "public": [
            {"module": s.module, "name": s.name, "kind": s.kind, "summary": s.summary}
            for s in public
        ],
        "excluded_private_in_all": [
            {"module": s.module, "name": s.name, "kind": s.kind, "summary": s.summary}
            for s in excluded
        ],
    }
