"""Support-matrix reference generator.

Generated directly from
``forge.verify.supported_matrix.MATRIX`` — the complete, real support
matrix (every recognised kind, with its full ``allowed_backends``/
``reason``), not the lossy ``SUPPORTED_MATRIX``/``EXPERIMENTAL_KINDS``
views that predate it.
"""
from __future__ import annotations

from forge.verify.supported_matrix import MATRIX, FlowClassification


def generate_support_matrix_page() -> str:
    lines = [
        "# Support Matrix",
        "",
        "<!-- Generated by `python -m forge.docsgen`. Do not edit directly. -->",
        "",
        "Generated directly from `forge.verify.supported_matrix.MATRIX` —",
        "the complete, real (kind, backend) support matrix. Every command",
        "that processes flow declarations validates against this matrix",
        "before doing any further work (`validate_flow_matrix()`).",
        "",
        "| Kind | Classification | Default backend | Allowed backends | Reason |",
        "|---|---|---|---|---|",
    ]
    for kind in sorted(MATRIX):
        entry = MATRIX[kind]
        classification = entry.classification.value
        allowed = ", ".join(f"`{b}`" for b in sorted(entry.allowed_backends))
        lines.append(
            f"| `{kind}` | {classification} | `{entry.default_backend}` | "
            f"{allowed} | {entry.reason} |"
        )
    lines.append("")

    supported = sorted(k for k, v in MATRIX.items() if v.classification == FlowClassification.SUPPORTED)
    experimental = sorted(k for k, v in MATRIX.items() if v.classification == FlowClassification.EXPERIMENTAL)
    lines += [
        "## Supported kinds",
        "",
        "\n".join(f"- `{k}`" for k in supported) or "*(none)*",
        "",
        "## Experimental kinds",
        "",
        "\n".join(f"- `{k}`" for k in experimental) or "*(none)*",
        "",
    ]
    return "\n".join(lines)
