"""Support-matrix reference generator.

Generated directly from
``forge.verification.supported_matrix.MATRIX`` — the complete, real support
matrix (every recognised kind, with its full ``allowed_backends``/
``reason``), not the lossy ``SUPPORTED_MATRIX``/``EXPERIMENTAL_KINDS``
views that predate it.
"""
from __future__ import annotations

from forge.verification.supported_matrix import MATRIX, FlowClassification


def _hls_tool_versions() -> list:
    """The Vitis HLS releases the port predictor has been validated against.

    Computed, not written down: every row comes from replaying the fixture
    corpus against that version's recorded synthesis output
    (``forge.hls.tool_matrix``). A release with no recorded output cannot
    appear here at all, which is the point — the page can never imply
    stability for a version nobody has tested.
    """
    from forge.hls import tool_matrix

    lines = [
        "## Vitis HLS versions",
        "",
        "FORGE predicts the RTL interface Vitis HLS will generate for a C++",
        "kernel (`forge.hls.port_prediction`), and HLS port naming moves",
        "between releases. This table is generated by replaying the fixture",
        "corpus (`forge/tests/fixtures/hls_port_matrix/`) against the real",
        "synthesis output recorded for each release — a version absent from",
        "it has not been tested, and FORGE claims nothing about it.",
        "",
        "| Vitis HLS | Status | What that means |",
        "|---|---|---|",
    ]
    matrix = tool_matrix.support_matrix()
    for version, status in sorted(matrix.items()):
        lines.append(
            f"| `{version}` | {status} | {tool_matrix.describe_status(status)} |"
        )
    if not matrix:
        lines.append("| *(none)* | untested | no recorded synthesis output |")
    lines.append("")
    lines.append(
        f"Any other release reports `{tool_matrix.UNTESTED}`: "
        f"{tool_matrix.describe_status(tool_matrix.UNTESTED)}. "
        f"`forge doctor` reports the status of the release on your own PATH."
    )
    lines.append("")

    for version in sorted(matrix):
        report = tool_matrix.validate_version(version)
        gaps = report.documented_gaps
        if not gaps:
            continue
        lines += [
            f"### Known gaps under {version}",
            "",
            "Differences between the prediction and this version's real output",
            "that the corpus records and explains. They are not reproduced by",
            "the predictor, and are reported rather than guessed at:",
            "",
        ]
        for case, reason in gaps:
            lines.append(f"- **`{case}`** — {reason}")
        lines.append("")
    return lines


def generate_support_matrix_page() -> str:
    lines = [
        "# Support Matrix",
        "",
        "<!-- Generated by `python -m forge.docsgen`. Do not edit directly. -->",
        "",
        "Generated directly from `forge.verification.supported_matrix.MATRIX` —",
        "the complete, real (kind, backend) support matrix. Every command",
        "that processes flow declarations validates against this matrix",
        "before doing any further work (`validate_flow_matrix()`).",
        "",
        "| Kind | Classification | Default backend | Allowed backends | Reason |",
        "|---|---|---|---|---|",
    ]
    for kind in sorted(MATRIX):
        entry = MATRIX[kind]
        classification = entry.classification.value
        allowed = ", ".join(f"`{b}`" for b in sorted(entry.allowed_backends))
        lines.append(
            f"| `{kind}` | {classification} | `{entry.default_backend}` | "
            f"{allowed} | {entry.reason} |"
        )
    lines.append("")

    lines += _hls_tool_versions()

    supported = sorted(k for k, v in MATRIX.items() if v.classification == FlowClassification.SUPPORTED)
    experimental = sorted(k for k, v in MATRIX.items() if v.classification == FlowClassification.EXPERIMENTAL)
    lines += [
        "## Supported kinds",
        "",
        "\n".join(f"- `{k}`" for k in supported) or "*(none)*",
        "",
        "## Experimental kinds",
        "",
        "\n".join(f"- `{k}`" for k in experimental) or "*(none)*",
        "",
    ]
    return "\n".join(lines)
