"""Canonical-role / protocol / interface-member / transformation-kind
reference generators (release-plan Phase 9, Defect 10).

These are four distinct, real, separately-validated vocabularies — not
one "protocols" page:

- **Canonical roles** — ``forge/topgen/ip/canonical_roles.yaml``, loaded
  via ``forge.topgen.ip.contract_verifier.load_canonical_role_vocab()``.
- **Protocols** — ``forge.topgen.ip.contract_verifier.KNOWN_PROTOCOLS``.
- **Interface members** — ``forge.topgen.ip.contract_verifier.KNOWN_MEMBERS``.
- **Transformation kinds** — not backed by a live registry in the source
  (documented only in ``forge.ir.model.ResolvedTransformation``'s
  docstring); this module is the fix — an AST-verified, typed registry
  (Defect 13's approach, applied here too) that structurally scans
  ``forge/ir/build.py`` for every real ``ResolvedTransformation(kind=...)``
  construction site and fails loudly if a real kind isn't in the registry,
  rather than trusting the docstring to stay in sync with the code.
"""
from __future__ import annotations

import importlib.resources
from dataclasses import dataclass
from pathlib import Path

from forge.ir import build as _ir_build
from forge.topgen.ip.contract_verifier import (
    KNOWN_MEMBERS,
    KNOWN_PROTOCOLS,
    load_canonical_role_vocab,
)

from ._ast_utils import find_call_kwarg_string_values

_IR_BUILD_SOURCE = Path(_ir_build.__file__)


# ── Canonical roles ──────────────────────────────────────────────────────

def generate_canonical_roles_page() -> str:
    vocab = load_canonical_role_vocab()
    lines = [
        "# Canonical Roles",
        "",
        "<!-- Generated by `python -m forge.docsgen`. Do not edit directly. -->",
        "",
        "Generated directly from `forge/topgen/ip/canonical_roles.yaml`",
        "(loaded via",
        "`forge.topgen.ip.contract_verifier.load_canonical_role_vocab()`) —",
        "the canonical *role* vocabulary specifically, distinct from the",
        "[Protocols](protocols.md) and [Interface Members](interface-members.md)",
        "vocabularies, which are separate, independently-validated sources.",
        "See [Contracts and Protocols](../concepts/contracts-and-protocols.md)",
        "for what these roles mean conceptually.",
        "",
        "| Role | Description | Direction | Width | Required | Generation-authoritative | Status |",
        "|---|---|---|---|---|---|---|",
    ]
    for name in sorted(vocab):
        entry = vocab[name] or {}
        description = str(entry.get("description", "")).strip().replace("\n", " ")
        direction = entry.get("direction", "")
        width = entry.get("width", "")
        required = "yes" if entry.get("required") else "no"
        gen_auth = "yes" if entry.get("generation_authoritative") else "no"
        status = entry.get("status", "active")
        lines.append(
            f"| `{name}` | {description} | {direction} | {width} | "
            f"{required} | {gen_auth} | {status} |"
        )
    lines.append("")
    return "\n".join(lines)


# ── Protocols ─────────────────────────────────────────────────────────────

def generate_protocols_page() -> str:
    lines = [
        "# Protocols",
        "",
        "<!-- Generated by `python -m forge.docsgen`. Do not edit directly. -->",
        "",
        "Generated directly from",
        "`forge.topgen.ip.contract_verifier.KNOWN_PROTOCOLS` — the complete",
        "set of documented built-in values a role's `protocol:` field may",
        "declare. Absent means unspecified, not a validation failure. See",
        "[Contracts and Protocols](../concepts/contracts-and-protocols.md)",
        "for what each value means semantically.",
        "",
    ]
    for protocol in sorted(KNOWN_PROTOCOLS):
        lines.append(f"- `{protocol}`")
    lines.append("")
    return "\n".join(lines)


# ── Interface members ────────────────────────────────────────────────────

def generate_interface_members_page() -> str:
    lines = [
        "# Interface Members",
        "",
        "<!-- Generated by `python -m forge.docsgen`. Do not edit directly. -->",
        "",
        "Generated directly from",
        "`forge.topgen.ip.contract_verifier.KNOWN_MEMBERS` — the recognized",
        "`member:` names a role may declare when it opts into interface",
        "grouping via a shared `interface:` name. See",
        "[Contracts and Protocols](../concepts/contracts-and-protocols.md)",
        "for the interface-member-grouping model.",
        "",
    ]
    for member in sorted(KNOWN_MEMBERS):
        lines.append(f"- `{member}`")
    lines.append("")
    return "\n".join(lines)


# ── Transformation kinds ─────────────────────────────────────────────────

@dataclass(frozen=True)
class TransformationKindDefinition:
    kind: str
    status: str  # "real" | "reserved"
    description: str


TRANSFORMATION_KINDS: "dict[str, TransformationKindDefinition]" = {
    "pipeline_register": TransformationKindDefinition(
        "pipeline_register", "real",
        "A pipeline register stage inserted on a connection, from "
        "`Connection.register_stages`.",
    ),
    "latency_delay": TransformationKindDefinition(
        "latency_delay", "real",
        "A fixed-cycle latency delay element, from `Connection.delay_cycles` "
        "with no `boundary` tag.",
    ),
    "slr_crossing": TransformationKindDefinition(
        "slr_crossing", "real",
        "An SLR-crossing delay register — `Connection.delay_cycles` *with* a "
        "`boundary` tag; `tag` carries the boundary string.",
    ),
    "fanout": TransformationKindDefinition(
        "fanout", "real",
        "Computed generically whenever a producer pin drives more than one "
        "connection; excludes clock/reset global-net fan-out.",
    ),
    "cdc_synchronizer": TransformationKindDefinition(
        "cdc_synchronizer", "real",
        "A two-flop synchronizer, from `Connection.cdc: {kind: level_sync}` "
        "(`2ff_sync` is a backwards-compatible alias, real generated RTL — "
        "`cdc_sync2ff`).",
    ),
    "pulse_sync": TransformationKindDefinition(
        "pulse_sync", "real",
        "A toggle + double-flop-sync + edge-detect pulse synchronizer, from "
        "`Connection.cdc: {kind: pulse_sync, min_spacing_cycles: N}` "
        "(release-plan §10.0B, real generated RTL — `cdc_pulse_sync`).",
    ),
    "mailbox_transfer": TransformationKindDefinition(
        "mailbox_transfer", "real",
        "A request/acknowledge handshake synchronizer for a coherent "
        "multi-bit payload, from `Connection.cdc: {kind: mailbox_transfer}` "
        "(release-plan §10.0B, real generated RTL — `cdc_mailbox`).",
    ),
    "async_fifo": TransformationKindDefinition(
        "async_fifo", "real",
        "From `Connection.cdc: {kind: async_fifo, depth: N}`. Real "
        "generated dual-clock FIFO RTL (release-plan §10.0B — "
        "`cdc_async_fifo`, Gray-code pointer synchronization).",
    ),
    "reset_synchronizer": TransformationKindDefinition(
        "reset_synchronizer", "real",
        "An async-assert/sync-deassert reset synchronizer, from "
        "`reset_domains.<name>.sync: reset_sync` (release-plan §10.0B, "
        "real generated RTL — `cdc_reset_sync`). Domain-keyed, not "
        "connection-keyed — see `ResolvedResetDomain.transformations`.",
    ),
    "tie_off": TransformationKindDefinition(
        "tie_off", "real",
        "Synthesized post-generation from the generator's `tied_to_zero` "
        "report (a `\"$tie_off\"` producer sentinel).",
    ),
    "gather_scatter": TransformationKindDefinition(
        "gather_scatter", "real",
        "Scatter/gather classification surfaced via "
        "`MatchReport.gather_scatter_evidence`; `tag` carries `\"scatter\"` "
        "or `\"gather\"`.",
    ),
    "width_adapter": TransformationKindDefinition(
        "width_adapter", "reserved",
        "Nothing in the matcher or generators ever inserts an adapter for a "
        "width mismatch today; mismatches simply fail to auto-match or are "
        "wired as-is.",
    ),
    "protocol_adapter": TransformationKindDefinition(
        "protocol_adapter", "reserved",
        "Same as `width_adapter`, for protocol mismatches — no adapter is "
        "ever inserted today.",
    ),
    "constant_source": TransformationKindDefinition(
        "constant_source", "reserved",
        "FORGE has no mechanism for declaring a non-zero constant source; "
        "only tie-to-zero (`tie_off`) exists.",
    ),
}


def real_transformation_kinds_in_source() -> "set[str]":
    """The transformation kinds actually constructed in
    ``forge/ir/build.py`` right now, found via a structural AST scan (not
    a text grep) — see ``_ast_utils.find_call_kwarg_string_values``."""
    return find_call_kwarg_string_values(
        _IR_BUILD_SOURCE, {"ResolvedTransformation"}, "kind",
    )


def check_transformation_registry_matches_source() -> "list[str]":
    """Return a list of human-readable problems, empty if the registry
    and the real emission sites in ``forge/ir/build.py`` agree exactly:
    every kind actually constructed is registered as ``"real"``, and no
    kind registered as ``"real"`` is missing from the source."""
    problems: "list[str]" = []
    real_in_source = real_transformation_kinds_in_source()
    registered_real = {
        k for k, d in TRANSFORMATION_KINDS.items() if d.status == "real"
    }

    for kind in sorted(real_in_source - registered_real):
        problems.append(
            f"kind {kind!r} is constructed in forge/ir/build.py but missing "
            f"from TRANSFORMATION_KINDS (or marked non-'real')"
        )
    for kind in sorted(registered_real - real_in_source):
        problems.append(
            f"kind {kind!r} is registered as 'real' but no construction site "
            f"was found in forge/ir/build.py — demote to 'reserved' or fix "
            f"the registry"
        )
    return problems


def generate_transformations_page() -> str:
    problems = check_transformation_registry_matches_source()
    if problems:
        raise RuntimeError(
            "TRANSFORMATION_KINDS registry is out of sync with "
            "forge/ir/build.py:\n  " + "\n  ".join(problems)
        )

    lines = [
        "# Transformations",
        "",
        "<!-- Generated by `python -m forge.docsgen`. Do not edit directly. -->",
        "",
        "The transformation-kind vocabulary (`forge.ir.model.ResolvedTransformation`)",
        "isn't backed by a live registry in the source — this page is",
        "generated from a small, AST-verified registry in",
        "`forge.docsgen.vocab_reference` that is checked, at generation",
        "time, against every real `ResolvedTransformation(kind=...)`",
        "construction site in `forge/ir/build.py` (structurally, via AST,",
        "not a text grep) — so this page cannot silently drift the way a",
        "docstring copy could.",
        "",
        "## Real (constructed today)",
        "",
        "| Kind | Description |",
        "|---|---|",
    ]
    for defn in sorted(
        (d for d in TRANSFORMATION_KINDS.values() if d.status == "real"),
        key=lambda d: d.kind,
    ):
        lines.append(f"| `{defn.kind}` | {defn.description} |")

    lines += [
        "",
        "## Reserved (declared, zero live instances today)",
        "",
        "| Kind | Description |",
        "|---|---|",
    ]
    for defn in sorted(
        (d for d in TRANSFORMATION_KINDS.values() if d.status == "reserved"),
        key=lambda d: d.kind,
    ):
        lines.append(f"| `{defn.kind}` | {defn.description} |")
    lines.append("")
    return "\n".join(lines)
