// stimulus_current.svh — generated by plugin gen_stimulus.py
// DO NOT EDIT — regenerate by running gen_stimulus.py
//
// Framework contract:
//   * This file is `include'd into the testbench module body.
//   * Must declare exactly one task: ``task automatic run_stimulus();``
//   * The task is called once after reset + idle cycles.
//   * Signals ap_clk, ap_rst (and all DUT ports) are in scope.

// flow=passthrough_xsim event=0

task automatic run_stimulus();

    // ── reset ──
    ap_rst <= 1'b1;
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    ap_rst <= 1'b0;
    @(posedge ap_clk);
    // ── end: reset ──


    // ── event_0 ──
    pt_data_in <= 8'h3A;
    pt_data_in_valid <= 1'b1;
    @(posedge ap_clk);
    @(posedge ap_clk);
    // ── end: event_0 ──


    // ── checks ──
    $display("FORGE_CHECK|check_id=0:data_out_check|label=data_out_check|signal=pt_data_out|expected=0x3a|observed=0x%h|width=8|passed=%0d", pt_data_out, (pt_data_out === 8'h3A));
    if (pt_data_out !== 8'h3A) begin
      $display("FAIL: data_out_check — expected 8'h3A, got %0h", pt_data_out);
      $fatal(1, "Check failed: data_out_check");
    end
    $display("FORGE_CHECK|check_id=0:data_out_valid_check|label=data_out_valid_check|signal=pt_data_out_valid|expected=0x1|observed=0x%h|width=1|passed=%0d", pt_data_out_valid, (pt_data_out_valid === 1'b1));
    if (pt_data_out_valid !== 1'b1) begin
      $display("FAIL: data_out_valid_check — expected 1'b1, got %0h", pt_data_out_valid);
      $fatal(1, "Check failed: data_out_valid_check");
    end
    // ── end: checks ──


    // ── drain ──
    pt_data_in_valid <= 1'b0;
    @(posedge ap_clk);
    @(posedge ap_clk);
    // ── end: drain ──

endtask : run_stimulus
