// RegisterStage.v — Parameterised pipeline register stage
//
// Inserts STAGES flip-flop stages between data_in and data_out.
// Used by topgen-generated algo_top.v to implement register_stages on
// inter-module connections for timing alignment / pipeline balancing.
//
// Parameters:
//   DATAWIDTH  – bit width of the data path (default 1)
//   STAGES     – number of clock cycles of delay (default 1)
//
// Usage (generated by topgen structural_verilog):
//   RegisterStage #(.DATAWIDTH(16), .STAGES(2)) reg_stage_0 (
//       .clk(ap_clk),
//       .data_in(net_col_phi_sum),
//       .data_out(reg_net_col_trig_phi_sum)
//   );
//
// Timing:
//   Signal presented at data_in on cycle N appears at data_out on cycle N+STAGES.

`timescale 1ns / 1ps

module RegisterStage #(
    parameter DATAWIDTH = 1,
    parameter STAGES    = 1
)(
    input  wire                  clk,
    input  wire [DATAWIDTH-1:0]  data_in,
    output wire [DATAWIDTH-1:0]  data_out
);

    // Shift-register pipeline
    reg [DATAWIDTH-1:0] pipe [0:STAGES-1];

    integer i;
    always @(posedge clk) begin : pipe_shift
        pipe[0] <= data_in;
        for (i = 1; i < STAGES; i = i + 1)
            pipe[i] <= pipe[i-1];
    end

    assign data_out = pipe[STAGES-1];

endmodule
