// stimulus_current.svh — generated for hit_collector_xsim
// Generated by gen_stimulus.py — DO NOT EDIT
// Source: trigger_demo_golden.xml
//
// Defines task run_stimulus() — called from the TB initial block
// after reset/idle phases.  Uses $fatal(1,...) on any assertion failure.

task automatic run_stimulus();
  integer _fail;
  _fail = 0;

  // Event 0: n_hits=3 phi_sum=0x0213
  @(posedge ap_clk);
  in_hit_0   = 32'h00A10050;
  in_valid_0 = 1'b1;
  in_hit_1   = 32'h00B10060;
  in_valid_1 = 1'b1;
  in_hit_2   = 32'h00010000;
  in_valid_2 = 1'b0;
  in_hit_3   = 32'h00C10070;
  in_valid_3 = 1'b1;
  #1;  // combinational settle
  if (n_hits !== 3'd3) begin $display("FAIL [E0] n_hits=%0d expect=3", n_hits); _fail = 1; end
  if (phi_sum !== 16'h0213) begin $display("FAIL [E0] phi_sum=0x%04X expect=0x0213", phi_sum); _fail = 1; end
  if (collector_valid !== 1'b1) begin $display("FAIL [E0] collector_valid=%0b expect=1", collector_valid); _fail = 1; end

  // Event 1: n_hits=1 phi_sum=0x00D1
  @(posedge ap_clk);
  in_hit_0   = 32'h00D10080;
  in_valid_0 = 1'b1;
  in_hit_1   = 32'h00010000;
  in_valid_1 = 1'b0;
  in_hit_2   = 32'h00010000;
  in_valid_2 = 1'b0;
  in_hit_3   = 32'h00010000;
  in_valid_3 = 1'b0;
  #1;  // combinational settle
  if (n_hits !== 3'd1) begin $display("FAIL [E1] n_hits=%0d expect=1", n_hits); _fail = 1; end
  if (phi_sum !== 16'h00D1) begin $display("FAIL [E1] phi_sum=0x%04X expect=0x00D1", phi_sum); _fail = 1; end
  if (collector_valid !== 1'b1) begin $display("FAIL [E1] collector_valid=%0b expect=1", collector_valid); _fail = 1; end

  // Event 2: n_hits=4 phi_sum=0x0A04
  @(posedge ap_clk);
  in_hit_0   = 32'h01010100;
  in_valid_0 = 1'b1;
  in_hit_1   = 32'h02010200;
  in_valid_1 = 1'b1;
  in_hit_2   = 32'h03010300;
  in_valid_2 = 1'b1;
  in_hit_3   = 32'h04010400;
  in_valid_3 = 1'b1;
  #1;  // combinational settle
  if (n_hits !== 3'd4) begin $display("FAIL [E2] n_hits=%0d expect=4", n_hits); _fail = 1; end
  if (phi_sum !== 16'h0A04) begin $display("FAIL [E2] phi_sum=0x%04X expect=0x0A04", phi_sum); _fail = 1; end
  if (collector_valid !== 1'b1) begin $display("FAIL [E2] collector_valid=%0b expect=1", collector_valid); _fail = 1; end

  // Event 3: n_hits=0 phi_sum=0x0000
  @(posedge ap_clk);
  in_hit_0   = 32'h00010000;
  in_valid_0 = 1'b0;
  in_hit_1   = 32'h00010000;
  in_valid_1 = 1'b0;
  in_hit_2   = 32'h00010000;
  in_valid_2 = 1'b0;
  in_hit_3   = 32'h00010000;
  in_valid_3 = 1'b0;
  #1;  // combinational settle
  if (n_hits !== 3'd0) begin $display("FAIL [E3] n_hits=%0d expect=0", n_hits); _fail = 1; end
  if (phi_sum !== 16'h0000) begin $display("FAIL [E3] phi_sum=0x%04X expect=0x0000", phi_sum); _fail = 1; end
  if (collector_valid !== 1'b0) begin $display("FAIL [E3] collector_valid=%0b expect=0", collector_valid); _fail = 1; end

  if (_fail) $fatal(1, "TB FAIL: hit_collector_xsim — %0d assertion(s) failed", _fail);
endtask
