"""forge.analyze.latency_static.reporter
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Render latency-check results as a Markdown report.
"""
from __future__ import annotations

from pathlib import Path
from typing import List

from forge.analyze.latency_static.graph import LatencyGraph
from forge.analyze.latency_static.checker import MismatchReport


def render_markdown(
    graph: LatencyGraph,
    reports: List[MismatchReport],
    out_path: Path,
) -> None:
    """Write a Markdown latency-check report to *out_path*."""
    lines: List[str] = ["# Latency Check Report", ""]

    # ── Module table ───────────────────────────────────────────────────────
    lines += [
        "## Module Latency Summary", "",
        "| Module | Ref | Kind | Instances | Latency (cycles) | Source |",
        "|--------|-----|------|-----------|-----------------|--------|",
    ]
    for node in graph.nodes.values():
        if node.latency_cycles is not None:
            lat = str(node.latency_cycles)
            if node.is_variable:
                lat += " *(variable)*"
        else:
            lat = "**unknown**"
        lines.append(
            f"| {node.name} | {node.ref} | {node.kind} | {node.instances} "
            f"| {lat} | {node.latency_source} |"
        )
    lines.append("")

    # ── Merge-point analysis ───────────────────────────────────────────────
    lines += ["## Merge Point Analysis", ""]

    if not reports:
        lines += ["*No merge points found — single linear pipeline.*", ""]
    else:
        mismatches = [r for r in reports if r.is_mismatch]
        unknowns   = [r for r in reports if r.has_unknowns and not r.is_mismatch]
        ok_merges  = [r for r in reports if not r.is_mismatch and not r.has_unknowns]

        for r in reports:
            if r.is_mismatch:
                heading = f"### ❌ Mismatch at `{r.merge_node}`"
            elif r.has_unknowns:
                heading = f"### ⚠ Unknown latency at `{r.merge_node}`"
            else:
                heading = f"### ✅ Balanced at `{r.merge_node}`"

            lines += [heading, ""]
            lines += [f"Alignment: `{r.alignment}`", ""]
            lines += [
                "| Input path | Accumulated latency | Source |",
                "|-----------|---------------------|--------|",
            ]
            for p in r.paths:
                lat_str = str(p.total_cycles) if p.total_cycles is not None else "unknown"
                path_str = " → ".join(p.path)
                src_str = p.provenance.source if p.provenance else "unknown"
                lines.append(f"| `{path_str}` | {lat_str} | {src_str} |")
            lines.append("")

            if r.is_mismatch:
                lines += [
                    f"**Latency mismatch: {r.delta} cycle(s)**  "
                    f"(max={r.max_latency}, min={r.min_latency})",
                    "",
                ]
                if r.suggestion:
                    lines += [f"> 💡 {r.suggestion}", ""]

        # Summary
        lines += [
            "## Summary", "",
            f"| | Count |",
            f"|---|---|",
            f"| Merge points checked | {len(reports)} |",
            f"| ❌ Mismatches         | {len(mismatches)} |",
            f"| ⚠ Unknown latencies  | {len(unknowns)} |",
            f"| ✅ Balanced           | {len(ok_merges)} |",
            "",
        ]

    lines += ["*Generated by `forge analyze latency-check`*", ""]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
