// stimulus_current.svh — generated by plugin gen_stimulus.py
// DO NOT EDIT — regenerate by running gen_stimulus.py
//
// Framework contract:
//   * This file is `include'd into the testbench module body.
//   * Must declare exactly one task: ``task automatic run_stimulus();``
//   * The task is called once after reset + idle cycles.
//   * Signals ap_clk, ap_rst (and all DUT ports) are in scope.

// flow=quickstart_pipeline_xsim event=0

task automatic run_stimulus();

    // ── reset ──
    ap_rst <= 1'b1;
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    ap_rst <= 1'b0;
    @(posedge ap_clk);
    // ── end: reset ──


    // ── event_0 ──
    norm_pixel <= 8'h00;
    norm_x <= 12'h000;
    norm_y <= 12'h000;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    // ── end: event_0 ──


    // ── checks ──
    $display("FORGE_CHECK|check_id=0:normalized_pixel_check|label=normalized_pixel_check|signal=thresh_out_pixel|expected=0x00|observed=0x%h|width=8|passed=%0d", thresh_out_pixel, (thresh_out_pixel === 8'h00));
    if (thresh_out_pixel !== 8'h00) begin
      $display("FAIL: normalized_pixel_check — expected 8'h00, got %0h", thresh_out_pixel);
      $fatal(1, "Check failed: normalized_pixel_check");
    end
    $display("FORGE_CHECK|check_id=0:threshold_mask_check|label=threshold_mask_check|signal=thresh_threshold_mask|expected=0x0|observed=0x%h|width=1|passed=%0d", thresh_threshold_mask, (thresh_threshold_mask === 1'b0));
    if (thresh_threshold_mask !== 1'b0) begin
      $display("FAIL: threshold_mask_check — expected 1'b0, got %0h", thresh_threshold_mask);
      $fatal(1, "Check failed: threshold_mask_check");
    end
    $display("FORGE_CHECK|check_id=0:out_valid_check|label=out_valid_check|signal=thresh_out_valid|expected=0x1|observed=0x%h|width=1|passed=%0d", thresh_out_valid, (thresh_out_valid === 1'b1));
    if (thresh_out_valid !== 1'b1) begin
      $display("FAIL: out_valid_check — expected 1'b1, got %0h", thresh_out_valid);
      $fatal(1, "Check failed: out_valid_check");
    end
    // ── end: checks ──


    // ── drain ──
    norm_pixel_valid <= 1'b0;
    @(posedge ap_clk);
    @(posedge ap_clk);
    // ── end: drain ──

endtask : run_stimulus
