// ============================================================
// tb_algo_top.sv — Generated by gen-sim
// Flow:         quickstart_pipeline_xsim
// Top module:   algo_top
// Generated at: 2026-08-05 20:28 UTC
// DO NOT EDIT — regenerate with: gen-sim quickstart_pipeline_xsim
// ============================================================
`timescale 1ns/1ps

module tb_algo_top;

  // ── Timing parameters ────────────────────────────────────
  localparam real CLK_PERIOD_NS              = 4.0;
  localparam int  RESET_CYCLES               = 4;
  localparam int  IDLE_CYCLES_AFTER_RESET    = 0;
  localparam int  POST_STIMULUS_DRAIN_CYCLES = 6;

  // ── Clock and reset ──────────────────────────────────────
  logic ap_clk;
  logic ap_rst;

  initial ap_clk = 1'b0;
  always #(CLK_PERIOD_NS / 2.0) ap_clk = ~ap_clk;


    `ifndef PROBE_LOG
    localparam int PROBE_LOG = 0;
    `else
    localparam int PROBE_LOG = `PROBE_LOG;
    `endif

  // ── DUT signals (from port_map) ───────────────────────
  wire  thresh_out_end_of_frame;
  wire  thresh_out_end_of_line;
  wire  [15:0] thresh_out_frame_id;
  wire  [7:0] thresh_out_pixel;
  wire  [15:0] thresh_out_tile_id;
  wire  thresh_out_valid;
  wire  [11:0] thresh_out_x;
  wire  [11:0] thresh_out_y;
  wire  thresh_threshold_mask;
  logic norm_end_of_frame;
  logic norm_end_of_line;
  logic [15:0] norm_frame_id;
  logic [7:0] norm_pixel;
  logic norm_pixel_valid;
  logic [15:0] norm_tile_id;
  logic [11:0] norm_x;
  logic [11:0] norm_y;


  // ── Stimulus ─────────────────────────────────────────────
  `include "stimulus_current.svh"

  // ── DUT instantiation ────────────────────────────────────
  algo_top dut (
    .thresh_out_end_of_frame(thresh_out_end_of_frame),
    .thresh_out_end_of_line(thresh_out_end_of_line),
    .thresh_out_frame_id(thresh_out_frame_id),
    .thresh_out_pixel(thresh_out_pixel),
    .thresh_out_tile_id(thresh_out_tile_id),
    .thresh_out_valid(thresh_out_valid),
    .thresh_out_x(thresh_out_x),
    .thresh_out_y(thresh_out_y),
    .thresh_threshold_mask(thresh_threshold_mask),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .norm_end_of_frame(norm_end_of_frame),
    .norm_end_of_line(norm_end_of_line),
    .norm_frame_id(norm_frame_id),
    .norm_pixel(norm_pixel),
    .norm_pixel_valid(norm_pixel_valid),
    .norm_tile_id(norm_tile_id),
    .norm_x(norm_x),
    .norm_y(norm_y)
  );

  // ── Cycle counter ────────────────────────────────────────
  integer cycle_count;

  // ── Output trace ─────────────────────────────────────────
  integer trace_fd;
    integer probe_fd;

  // ── Main test sequence ──────────────────────────────────
  initial begin
    cycle_count = 0;
    ap_rst      = 1'b1;
    norm_end_of_frame = '0;
    norm_end_of_line = '0;
    norm_frame_id = '0;
    norm_pixel = '0;
    norm_pixel_valid = '0;
    norm_tile_id = '0;
    norm_x = '0;
    norm_y = '0;

    trace_fd = $fopen("algo_top_outputs.csv", "w");
    $fwrite(trace_fd, "cycle,thresh_out_end_of_frame,thresh_out_end_of_line,thresh_out_frame_id,thresh_out_pixel,thresh_out_tile_id,thresh_out_valid,thresh_out_x,thresh_out_y,thresh_threshold_mask\n");


    // Reset phase
    repeat (RESET_CYCLES) @(posedge ap_clk);
    ap_rst = 1'b0;

    // Idle settle phase
    repeat (IDLE_CYCLES_AFTER_RESET) @(posedge ap_clk);

    // Stimulus phase
    run_stimulus();  // defined in stimulus_current.svh (framework-standard handoff contract)

    // Drain phase
    repeat (POST_STIMULUS_DRAIN_CYCLES) @(posedge ap_clk);

    $fclose(trace_fd);

    $display("TB PASS: quickstart_pipeline_xsim completed");
    $finish;
  end

  // ── Output logging ───────────────────────────────────────
  always @(posedge ap_clk) begin
    if (!ap_rst) begin
      $fwrite(trace_fd, "%0d,%0b,%0b,%0h,%0h,%0h,%0b,%0h,%0h,%0b\n", cycle_count, thresh_out_end_of_frame, thresh_out_end_of_line, thresh_out_frame_id, thresh_out_pixel, thresh_out_tile_id, thresh_out_valid, thresh_out_x, thresh_out_y, thresh_threshold_mask);

      cycle_count <= cycle_count + 1;
    end
  end

endmodule
