#!/usr/bin/env python3
"""Prototype testbench generator (gen-sim).

Responsibility boundary
-----------------------
This module generates skeleton SystemVerilog testbench files and waveform
TCL scripts from the verify design contract and flow configuration.

Generated artifacts per flow
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ``tb_<top_module>.sv``    Testbench module skeleton
  ``wave.tcl``              Waveform logging + run all + quit

The generated testbench includes:
  * Timescale and module declaration
  * Clock and reset generation from flow timing parameters
  * ``tb_bindings.svh`` include (if available — gen-top output)
  * DUT instantiation stub
  * Reset → idle → stimulus → drain → finish main sequence
  * Stimulus include placeholder (``stimulus_current.svh``)

Public API
----------
  generate_testbench(flow, defaults, output_dir, port_map_path, tb_bindings)
      → dict[str, Path]    mapping {"tb": path, "wave": path}
  generate_verify_flow_yml(flow_decl, defaults, output_path, consumer_root, ...)
      → Path               path to the written verify.flow.yml
  render_tb_sv(...)   → str    raw SV text
  render_wave_tcl(...)→ str    raw TCL text
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

# Framework imports at use-time only (this module may be used standalone).


# ── Templates ──────────────────────────────────────────────────────────────

_TB_TEMPLATE = '''\
// ============================================================
// {tb_module}.sv — Generated by gen-sim
// Flow:         {flow_name}
// Top module:   {top_module}
// Generated at: {timestamp}
// DO NOT EDIT — regenerate with: gen-sim {flow_name}
// ============================================================
`timescale 1ns/1ps

module {tb_module};

  // ── Timing parameters ────────────────────────────────────
  localparam real CLK_PERIOD_NS              = {clk_period_ns};
  localparam int  RESET_CYCLES               = {reset_cycles};
  localparam int  IDLE_CYCLES_AFTER_RESET    = {idle_cycles_after_reset};
  localparam int  POST_STIMULUS_DRAIN_CYCLES = {post_stimulus_drain_cycles};

  // ── Clock and reset ──────────────────────────────────────
  logic ap_clk;
  logic ap_rst;

  initial ap_clk = 1'b0;
  always #(CLK_PERIOD_NS / 2.0) ap_clk = ~ap_clk;

{extra_clocks_and_resets}
    `ifndef PROBE_LOG
    localparam int PROBE_LOG = 0;
    `else
    localparam int PROBE_LOG = `PROBE_LOG;
    `endif

{signal_declarations}
  // ── Stimulus ─────────────────────────────────────────────
  `include "stimulus_current.svh"

  // ── DUT instantiation ────────────────────────────────────
{dut_instantiation}
  // ── Cycle counter ────────────────────────────────────────
  integer cycle_count;

  // ── Output trace ─────────────────────────────────────────
  integer trace_fd;
    integer probe_fd;

  // ── Main test sequence ──────────────────────────────────
  initial begin
    cycle_count = 0;
    ap_rst      = 1'b1;
{input_zeroing}
    trace_fd = $fopen("{csv_filename}", "w");
    $fwrite(trace_fd, "{csv_header}\\n");
{probe_open}

    // Reset phase
    repeat (RESET_CYCLES) @(posedge ap_clk);
    ap_rst = 1'b0;

    // Idle settle phase
    repeat (IDLE_CYCLES_AFTER_RESET) @(posedge ap_clk);

    // Stimulus phase
    run_stimulus();  // defined in stimulus_current.svh (framework-standard handoff contract)

    // Drain phase
    repeat (POST_STIMULUS_DRAIN_CYCLES) @(posedge ap_clk);

    $fclose(trace_fd);
{probe_close}
    $display("TB PASS: {flow_name} completed");
    $finish;
  end

  // ── Output logging ───────────────────────────────────────
  always @(posedge ap_clk) begin
    if (!ap_rst) begin
{csv_fwrite}
{probe_fwrite}
      cycle_count <= cycle_count + 1;
    end
  end

endmodule
'''

_WAVE_TCL_TEMPLATE = '''\
# wave.tcl — Generated by gen-sim
# Flow: {flow_name}
# Top: {tb_module}
log_wave /{tb_module}/*
run all
quit
'''


# ── Port map reader ────────────────────────────────────────────────────────

def _load_port_map_raw(port_map_path: Path | None) -> dict[str, Any]:
    """Load the raw YAML dict from a port_map file, or {} on any failure."""
    if port_map_path is None or not port_map_path.exists():
        return {}
    try:
        import yaml as _yaml
        return _yaml.safe_load(port_map_path.read_text()) or {}
    except Exception:
        return {}


def _flatten_ports(raw: dict[str, Any]) -> list[dict[str, Any]]:
    """Flatten ports from either format into a single list.

    Flat format:    ``ports: [{name, direction, width}, ...]``
    Port-groups:    ``port_groups: {group: list | {channels: list} | {ports: list}}``
    """
    if "ports" in raw:
        return raw.get("ports", []) or []
    ports: list[dict[str, Any]] = []
    for group_val in raw.get("port_groups", {}).values():
        if isinstance(group_val, list):
            ports.extend(group_val)
        elif isinstance(group_val, dict):
            # Dict-style groups use either 'channels' or 'ports' as the sub-list key.
            sub: list[Any] = group_val.get("channels") or group_val.get("ports") or []
            ports.extend(sub)
    return ports


def _output_ports(raw: dict[str, Any]) -> list[dict[str, Any]]:
    """Return only the DUT output port entries.

    In port_groups format the outputs are under ``port_groups.outputs``.
    In flat format outputs are identified by ``direction: output``.
    """
    if "port_groups" in raw:
        outs = raw["port_groups"].get("outputs", [])
        return [p for p in (outs if isinstance(outs, list) else []) if isinstance(p, dict)]
    return [p for p in raw.get("ports", []) if p.get("direction") == "output"]


def _bx0_signal(raw: dict[str, Any]) -> str | None:
    """Return the BX0 input signal name from the ``bx0`` group, or ``None``."""
    bx0_grp = raw.get("port_groups", {}).get("bx0", [])
    if isinstance(bx0_grp, list) and bx0_grp:
        return bx0_grp[0].get("name") if isinstance(bx0_grp[0], dict) else None
    return None


def _read_port_map(port_map_path: Path | None) -> list[dict[str, Any]]:
    """Read a port_map.yaml and return a flattened list of port entries.

    Supports both the flat ``ports:`` format and the ``port_groups:`` format
    produced by topgen.  Each entry has at minimum: name, direction, width.
    Returns [] if the file is missing or unparseable.
    """
    return _flatten_ports(_load_port_map_raw(port_map_path))


# ── CSV trace helpers ──────────────────────────────────────────────────────

def _fmt_spec(width: int) -> str:
    """Return a SystemVerilog $fwrite format specifier for *width* bits."""
    if width == 1:
        return "%0b"
    if width <= 4:
        return "%0d"
    return "%0h"


def _render_csv_header(out_ports: list[dict[str, Any]], bx0_sig: str | None) -> str:
    """Build the CSV column header string (no trailing newline)."""
    cols = ["cycle"]
    if bx0_sig:
        cols.append("bx0")
    cols.extend(p.get("name", "?") for p in out_ports)
    return ",".join(cols)


def _render_csv_fwrite(out_ports: list[dict[str, Any]], bx0_sig: str | None) -> str:
    """Build a ``$fwrite`` statement that emits one CSV data row per clock cycle."""
    fmt_parts = ["%0d"]  # cycle
    var_parts = ["cycle_count"]
    if bx0_sig:
        fmt_parts.append("%0b")
        var_parts.append(bx0_sig)
    for p in out_ports:
        fmt_parts.append(_fmt_spec(int(p.get("width", 1))))
        var_parts.append(p.get("name", "?"))
    fmt = ",".join(fmt_parts)
    return f'      $fwrite(trace_fd, "{fmt}\\n", {", ".join(var_parts)});'


# ── Signal & instantiation rendering ──────────────────────────────────────

def _render_signal_declarations(
    ports: list[dict[str, Any]],
    reserved_names: "frozenset[str]" = frozenset(),
) -> str:
    """Render SV signal declarations from port map entries.

    ``reserved_names``: extra clock/reset
    net names already declared by :func:`_render_extra_clocks_and_resets` —
    skipped here the same way ``ap_clk``/``ap_rst`` always have been, so a
    multi-clock-domain design's domain clock/reset ports don't get declared
    twice.
    """
    if not ports:
        return "  // (no port_map available — declare signals manually)\n"

    skip = {"ap_clk", "ap_rst"} | reserved_names
    lines: list[str] = ["  // ── DUT signals (from port_map) ───────────────────────"]
    for port in ports:
        name = port.get("name", "unknown")
        width = port.get("width", 1)
        direction = port.get("direction", "input")
        if name in skip:
            continue  # Already declared
        if width == 1:
            keyword = "wire" if direction == "output" else "logic"
            lines.append(f"  {keyword:5s} {name};")
        else:
            keyword = "wire" if direction == "output" else "logic"
            lines.append(f"  {keyword:5s} [{width - 1}:0] {name};")
    lines.append("")
    return "\n".join(lines) + "\n"


def _render_dut_instantiation(
    top_module: str,
    ports: list[dict[str, Any]],
) -> str:
    """Render a DUT instantiation block connecting all ports by name."""
    if not ports:
        return (
            f"  // TODO: Instantiate {top_module} — no port_map available.\n"
            f"  // {top_module} dut (\n"
            f"  //   .ap_clk(ap_clk),\n"
            f"  //   .ap_rst(ap_rst)\n"
            f"  // );\n"
        )

    lines = [f"  {top_module} dut ("]
    port_lines: list[str] = []
    for port in ports:
        name = port.get("name", "unknown")
        port_lines.append(f"    .{name}({name})")
    lines.append(",\n".join(port_lines))
    lines.append("  );")
    return "\n".join(lines) + "\n"


def _render_input_zeroing(
    ports: list[dict[str, Any]],
    reserved_names: "frozenset[str]" = frozenset(),
) -> str:
    """Render initial zeroing of all input signals.

    ``reserved_names``: extra clock/reset nets — these are
    driven by their own free-running generator / reset sequence
    (:func:`_render_extra_clocks_and_resets`), not zeroed as plain stimulus.
    """
    if not ports:
        return "    // (zero inputs manually)\n"

    skip = {"ap_clk", "ap_rst"} | reserved_names
    lines: list[str] = []
    for port in ports:
        name = port.get("name", "unknown")
        direction = port.get("direction", "input")
        if direction == "output" or name in skip:
            continue
        lines.append(f"    {name} = '0;")
    return "\n".join(lines) + "\n" if lines else "    // (no inputs to zero)\n"


def _render_extra_clocks_and_resets(
    extra_clocks: "dict[str, float]",
    extra_resets: "dict[str, str]",
) -> str:
    """Render additional free-running clocks and their own
    reset-then-synchronously-deassert sequences (real multi-clock-domain
    xsim support).

    Each extra clock gets its own ``logic``/``always`` toggle pair, exactly
    like ``ap_clk``'s own generation above, just at its own declared period.
    Each extra reset gets its own ``initial`` block, asserted for
    ``RESET_CYCLES`` cycles of *its own* declared clock before deasserting —
    a reset crossing's whole point (``reset_domains.<name>.sync: reset_sync``,
    ``cdc_reset_sync``) is a *synchronous-to-its-destination-domain*
    deassertion, so this must count cycles on that domain's own clock, not
    ``ap_clk``. A reset with no matching clock name in ``extra_clocks``
    falls back to ``ap_clk`` — the primary domain's clock is still a valid
    synchronization reference for an otherwise-undeclared clock name.
    Runs concurrently with the main ``initial`` block (SystemVerilog allows
    multiple ``initial`` blocks; simulation time only advances via clock
    edges/delays, so this is a real, independent reset sequence per domain,
    not a race).
    """
    if not extra_clocks and not extra_resets:
        return ""

    lines: list[str] = ["  // ── Additional clock domains ──"]
    for name, period_ns in sorted(extra_clocks.items()):
        lines.append(f"  logic {name};")
        lines.append(f"  initial {name} = 1'b0;")
        lines.append(f"  always #({period_ns} / 2.0) {name} = ~{name};")
    if extra_resets:
        lines.append("")
        lines.append("  // ── Additional reset domains — synchronous deassert per-domain ──")
        for reset_name, clock_name in sorted(extra_resets.items()):
            ref_clock = clock_name if clock_name in extra_clocks else "ap_clk"
            lines.append(f"  logic {reset_name};")
            lines.append(f"  initial begin")
            lines.append(f"    {reset_name} = 1'b1;")
            lines.append(f"    repeat (RESET_CYCLES) @(posedge {ref_clock});")
            lines.append(f"    {reset_name} = 1'b0;")
            lines.append(f"  end")
    lines.append("")
    return "\n".join(lines) + "\n"


def _tier2_probes(raw: dict[str, Any]) -> list[dict[str, Any]]:
    """Return Tier 2 probe descriptors from either supported metadata format."""
    probes: list[dict[str, Any]] = []
    tier2 = raw.get("tier2_probes", [])
    if isinstance(tier2, list):
        probes.extend([p for p in tier2 if isinstance(p, dict)])

    probe_tiers = raw.get("probe_tiers", {})
    if isinstance(probe_tiers, dict):
        tier2b = probe_tiers.get("tier2", [])
        if isinstance(tier2b, list):
            probes.extend([p for p in tier2b if isinstance(p, dict)])
    return probes


def _render_probe_open(tier2_probes: list[dict[str, Any]], top_module: str) -> str:
    if not tier2_probes:
        return ""

    header = ",".join(["cycle"] + [str(p.get("name", "probe")) for p in tier2_probes])
    return "\n".join([
        "    if (PROBE_LOG) begin",
        f"      probe_fd = $fopen(\"{top_module}_probe.csv\", \"w\");",
        f"      if (probe_fd == 0) $fatal(1, \"Failed to open {top_module}_probe.csv\");",
        f"      $fwrite(probe_fd, \"{header}\\n\");",
        "    end",
    ])


def _render_probe_close(tier2_probes: list[dict[str, Any]]) -> str:
    if not tier2_probes:
        return ""
    return "    if (PROBE_LOG) $fclose(probe_fd);"


def _render_probe_fwrite(tier2_probes: list[dict[str, Any]]) -> str:
    if not tier2_probes:
        return ""

    fmt_parts = ["%0d"]
    var_parts = ["cycle_count"]
    for probe in tier2_probes:
        fmt_parts.append(_fmt_spec(int(probe.get("width", 1) or 1)))
        var_parts.append(str(probe.get("net", probe.get("name", "probe"))))

    fmt = ",".join(fmt_parts)
    args = ", ".join(var_parts)
    # `ifdef-guarded, not just the runtime `if (PROBE_LOG)`: this $fwrite
    # references DUT-internal hierarchy nets (probe["net"]), and Verilog
    # elaborates every referenced signal regardless of which branch of a
    # runtime conditional is taken. Under --mode bd those nets live under a
    # different (IP-Integrator-managed) hierarchy than --mode verilog's flat
    # one, so elaboration fails even with PROBE_LOG=0 unless this text is
    # compiled out entirely when the macro isn't defined.
    return "\n".join([
        "`ifdef PROBE_LOG",
        "      if (PROBE_LOG) begin",
        f"        $fwrite(probe_fd, \"{fmt}\\n\", {args});",
        "      end",
        "`endif",
    ])


# ── Public API ─────────────────────────────────────────────────────────────

def render_tb_sv(
    flow_name: str,
    top_module: str,
    tb_module: str,
    clk_period_ns: float,
    reset_cycles: int,
    idle_cycles_after_reset: int,
    post_stimulus_drain_cycles: int,
    port_map_path: Path | None = None,
    extra_clocks: "dict[str, float] | None" = None,
    extra_resets: "dict[str, str] | None" = None,
) -> str:
    """Render a skeleton SystemVerilog testbench.

    Args:
        flow_name:   Verification flow name (for comments).
        top_module:   DUT top module name.
        tb_module:    Testbench module name.
        clk_period_ns, reset_cycles, idle_cycles_after_reset,
        post_stimulus_drain_cycles:  Simulation timing parameters.
        port_map_path:  Optional path to port_map.yaml (gen-top output).
        extra_clocks, extra_resets:  Multi-clock-domain designs —
            additional top-level clock/reset nets beyond the primary
            ap_clk/ap_rst. See
            forge.verification.design_contract.SimulationDefaults's own
            extra_clocks/extra_resets fields for the {net_name: value}
            shape. Empty/None (the default) reproduces the exact
            single-clock output every pre-existing flow already depends on.

    Returns:
        The generated SV source as a string.
    """
    import datetime
    extra_clocks = extra_clocks or {}
    extra_resets = extra_resets or {}
    reserved_names = frozenset(extra_clocks) | frozenset(extra_resets)
    raw = _load_port_map_raw(port_map_path)
    ports = _flatten_ports(raw)
    out_ports = _output_ports(raw)
    bx0_sig = _bx0_signal(raw)
    tier2_probes = _tier2_probes(raw)
    csv_filename = f"{top_module}_outputs.csv"
    csv_header = _render_csv_header(out_ports, bx0_sig)
    csv_fwrite = _render_csv_fwrite(out_ports, bx0_sig)
    return _TB_TEMPLATE.format(
        flow_name=flow_name,
        top_module=top_module,
        tb_module=tb_module,
        clk_period_ns=clk_period_ns,
        reset_cycles=reset_cycles,
        idle_cycles_after_reset=idle_cycles_after_reset,
        post_stimulus_drain_cycles=post_stimulus_drain_cycles,
        timestamp=datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        extra_clocks_and_resets=_render_extra_clocks_and_resets(extra_clocks, extra_resets),
        signal_declarations=_render_signal_declarations(ports, reserved_names),
        dut_instantiation=_render_dut_instantiation(top_module, ports),
        input_zeroing=_render_input_zeroing(ports, reserved_names),
        csv_filename=csv_filename,
        csv_header=csv_header,
        csv_fwrite=csv_fwrite,
        probe_open=_render_probe_open(tier2_probes, top_module),
        probe_close=_render_probe_close(tier2_probes),
        probe_fwrite=_render_probe_fwrite(tier2_probes),
    )


def render_wave_tcl(flow_name: str, tb_module: str) -> str:
    """Render a waveform TCL script.

    Returns:
        The generated TCL source as a string.
    """
    return _WAVE_TCL_TEMPLATE.format(
        flow_name=flow_name,
        tb_module=tb_module,
    )


def generate_testbench(
    flow_name: str,
    top_module: str,
    tb_module: str,
    clk_period_ns: float,
    reset_cycles: int,
    idle_cycles_after_reset: int,
    post_stimulus_drain_cycles: int,
    output_dir: Path,
    port_map_path: Path | None = None,
    extra_clocks: "dict[str, float] | None" = None,
    extra_resets: "dict[str, str] | None" = None,
) -> dict[str, Path]:
    """Generate testbench files in *output_dir*.

    Creates:
      ``<output_dir>/<tb_module>.sv``
      ``<output_dir>/wave.tcl``

    ``extra_clocks``/``extra_resets``: see :func:`render_tb_sv`.

    Returns:
        ``{"tb": Path, "wave": Path}`` mapping to the generated files.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    tb_path = output_dir / f"{tb_module}.sv"
    wave_path = output_dir / "wave.tcl"

    tb_path.write_text(render_tb_sv(
        flow_name=flow_name,
        top_module=top_module,
        tb_module=tb_module,
        clk_period_ns=clk_period_ns,
        reset_cycles=reset_cycles,
        idle_cycles_after_reset=idle_cycles_after_reset,
        post_stimulus_drain_cycles=post_stimulus_drain_cycles,
        port_map_path=port_map_path,
        extra_clocks=extra_clocks,
        extra_resets=extra_resets,
    ))

    wave_path.write_text(render_wave_tcl(flow_name, tb_module))

    return {"tb": tb_path, "wave": wave_path}


# ── verify.flow.yml generation ─────────────────────────────────────────────

_FLOW_YML_TEMPLATE = """\
# verify.flow.yml — Generated by gen-sim
# Flow:   {flow_name}
# Plugin: {plugin}
# Source: {source_path}
# DO NOT EDIT — regenerate with: gen-sim generate {flow_name}

flow:
  plugin:     {plugin}
  name:       {flow_name}
  kind:       {kind}
  backend:    {backend}
  top_module: {top_module}
  tb_module:  {tb_module}

dut:
  rtl:            {dut_rtl}
  manifest:       {dut_manifest}
  port_map:       {dut_port_map}
  tb_bindings:    {dut_tb_bindings}
  port_signature: {dut_port_signature}

dataset:
  xml:              {dataset_xml}
{dataset_parts_text}  default_event_id: {default_event_id}

simulation:
  clk_period_ns:              {clk_period_ns}
  reset_cycles:               {reset_cycles}
  idle_cycles_after_reset:    {idle_cycles_after_reset}
  post_stimulus_drain_cycles: {post_stimulus_drain_cycles}
{extra_sim_text}checker_mode: {checker_mode}
stimulus_mode: {stimulus_mode}
{xsim_section}
{checker_section}"""

def _yaml_nullable(value: Any) -> str:
    """Return YAML representation for a potentially-null value."""
    if value is None or value == "" or value == "~":
        return "~"
    return str(value)


def _yaml_bool(value: bool) -> str:
    return "true" if value else "false"


def _yaml_list_block(key: str, values: list[str], indent: str = "  ") -> str:
    if not values:
        return ""
    lines = [f"{indent}{key}:"]
    lines.extend(f"{indent}  - {v}" for v in values)
    return "\n".join(lines) + "\n"


def _checker_args_block(args: list[str]) -> str:
    if not args:
        return ""
    lines = ["  args:"]
    lines.extend(f'    - "{a}"' for a in args)
    return "\n".join(lines)


def _xsim_extra_sources_block(extra_sources: list[tuple[str, str]]) -> str:
    if not extra_sources:
        return ""
    lines = ["  extra_sources:"]
    for path, lang in extra_sources:
        lines.append(f"    - path: {path}")
        lines.append(f"      lang: {lang}")
    return "\n".join(lines) + "\n"


def _render_checker_section(checker: Any, checker_mode: str, top_module: str) -> str:
    observed = getattr(checker, "observed_log", None) or f"xsim_work/{top_module}_outputs.csv"
    lines = [
        "checker:",
        f"  mode:           {getattr(checker, 'mode', None) or checker_mode}",
        f"  tool:           {getattr(checker, 'tool', None) or 'algo_top_xsim_checker'}",
        f"  binary:         {_yaml_nullable(getattr(checker, 'binary', None))}",
        f"  observed_log:   {observed}",
        f"  latency_cycles: {getattr(checker, 'latency_cycles', 0) or 0}",
        f"  tolerance:      {getattr(checker, 'tolerance', 0) or 0}",
        f"  pass_condition: {getattr(checker, 'pass_condition', None) or 'zero_mismatches'}",
    ]
    args = list(getattr(checker, "args", ()) or [])
    if args:
        lines.append("  args:")
        lines.extend(f'    - "{a}"' for a in args)
    return "\n".join(lines) + "\n"


def _render_xsim_section(xsim: Any) -> str:
    lines = [
        "xsim:",
        f"  use_sv_flag: {_yaml_bool(bool(getattr(xsim, 'use_sv_flag', True)))}",
        f"  top_lib: {_yaml_nullable(getattr(xsim, 'top_lib', None))}",
    ]
    extra_top_modules = list(getattr(xsim, "extra_top_modules", ()) or [])
    if extra_top_modules:
        lines.append("  extra_top_modules:")
        lines.extend(f"    - {v}" for v in extra_top_modules)
    elab_libs = list(getattr(xsim, "elab_libs", ()) or [])
    if elab_libs:
        lines.append("  elab_libs:")
        lines.extend(f"    - {v}" for v in elab_libs)
    extra_sources = list(getattr(xsim, "extra_sources", ()) or [])
    if extra_sources:
        lines.append("  extra_sources:")
        for src in extra_sources:
            lines.append(f"    - path: {src.path}")
            lines.append(f"      lang: {src.lang}")
    return "\n".join(lines) + "\n"


def generate_verify_flow_yml(
    flow_decl: Any,
    defaults: Any,
    output_path: Path,
    consumer_root: Path,
    plugin_id: "str" = "",
    dut_rtl: "str | None" = None,
    dut_manifest: "str | None" = None,
    dut_port_map: "str | None" = None,
    dut_tb_bindings: "str | None" = None,
    dut_port_signature: "str | None" = None,
    dataset_xml: "str | None" = None,
    dataset_parts_glob: "str | None" = None,
    dataset_parts: "tuple[str, ...]" = (),
    extra_simulation_fields: tuple = (),  # (key, value) pairs from plugin defaults
    source_path: "str" = "design.verification.yml",
) -> Path:
    """Generate a ``verify.flow.yml`` from a ``FlowDeclaration`` and defaults.

    Parameters
    ----------
    flow_decl:
        A ``FlowDeclaration`` dataclass instance from ``design_contract``.
    defaults:
        A ``SimulationDefaults`` dataclass instance for timing fallbacks.
    output_path:
        Absolute path where the ``verify.flow.yml`` should be written.
    consumer_root:
        Repo root used to make paths relative in the generated file.
    dut_rtl, dut_manifest, dut_port_map, dut_tb_bindings, dut_port_signature:
        Resolved DUT artifact paths, expressed relative to ``consumer_root``.
        Pass ``None`` for fields not relevant to the flow kind.
    dataset_xml:
        Resolved dataset XML path relative to ``consumer_root``.
    source_path:
        Informational: path of the source ``design.verification.yml`` shown
        in the generated file header comment.

    Returns
    -------
    Path to the written file.
    """
    # Resolve per-flow simulation values, falling back to contract defaults.
    clk   = getattr(defaults, "clk_period_ns", 4.0)
    rst   = getattr(flow_decl, "reset_cycles",               None) or getattr(defaults, "reset_cycles", 4)
    idle  = getattr(flow_decl, "idle_cycles_after_reset",    None) or getattr(defaults, "idle_cycles_after_reset", 0)
    drain = getattr(flow_decl, "post_stimulus_drain_cycles", None) or getattr(defaults, "post_stimulus_drain_cycles", 8)
    # Extra plugin-specific simulation fields passed through verbatim
    _extra = extra_simulation_fields or getattr(defaults, "extra", ())
    extra_sim_text = "".join(f"  {k}: {v}\n" for k, v in _extra) if _extra else ""

    checker = getattr(flow_decl, "checker", None)
    checker_mode = getattr(flow_decl, "checker_mode", "log_scan")
    if checker is not None and any(
        getattr(checker, f, None) is not None
        for f in ("binary", "observed_log", "latency_cycles", "tolerance", "pass_condition")
    ):
        checker_text = _render_checker_section(checker, checker_mode, flow_decl.top_module)
    else:
        checker_text = ""

    xsim = getattr(flow_decl, "xsim", None)
    if xsim is not None:
        xsim_text = _render_xsim_section(xsim)
    else:
        xsim_text = ""

    text = _FLOW_YML_TEMPLATE.format(
        flow_name=flow_decl.name,
        plugin=plugin_id or getattr(flow_decl, "_plugin", ""),
        kind=flow_decl.kind,
        backend=flow_decl.backend,
        top_module=flow_decl.top_module,
        tb_module=flow_decl.tb_module,
        dut_rtl=_yaml_nullable(dut_rtl),
        dut_manifest=_yaml_nullable(dut_manifest),
        dut_port_map=_yaml_nullable(dut_port_map),
        dut_tb_bindings=_yaml_nullable(dut_tb_bindings),
        dut_port_signature=_yaml_nullable(dut_port_signature),
        dataset_xml=_yaml_nullable(dataset_xml),
        dataset_parts_text=_render_dataset_parts(dataset_parts_glob, dataset_parts),
        default_event_id=getattr(flow_decl, "default_event_id", 1),
        clk_period_ns=clk,
        reset_cycles=rst,
        idle_cycles_after_reset=idle,
        post_stimulus_drain_cycles=drain,
        extra_sim_text=extra_sim_text,
        checker_mode=checker_mode,
        stimulus_mode=getattr(flow_decl, "stimulus_mode", "svh_include"),
        xsim_section=xsim_text,
        checker_section=checker_text,
        source_path=str(source_path),
    )

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(text)
    return output_path


def _render_dataset_parts(parts_glob: str | None, parts: tuple[str, ...]) -> str:
    lines: list[str] = []
    if parts_glob:
        lines.append(f"  parts_glob:       {parts_glob}")
    if parts:
        lines.append("  parts:")
        lines.extend(f"    - {part}" for part in parts)
    return ("\n".join(lines) + "\n") if lines else ""
