#!/usr/bin/env python3
"""Stale artifact detection for fw_verify — Workstream D6 / B4.

Detects when framework-generated artifacts are older than the source files
that should have regenerated them.  This prevents silent failures caused by
forgetting to re-run ``fw_verify generate`` or ``fw_verify prepare`` after:

  * Editing ``design.verification.yml``
  * Running new HLS synthesis (updating the Verilog RTL)
  * Changing the dataset XML
  * Re-running the plugin's stimulus generator

Behaviour
---------
By default, stale artifacts produce **warnings**.
In ``--strict`` mode callers should treat these as errors.

Sources checked (most-recent mtime wins)
-----------------------------------------
  * ``design.verification.yml``  — always
  * DUT RTL Verilog (``dut_rtl_source/<module>.v``) — when available
  * Dataset XML                 — when declared in contract
  * ``tools/gen_stimulus.py``   — when exists (affects stimulus freshness)

Artifacts checked per flow
---------------------------
  * ``verify.flow.yml``        — generated by ``fw_verify generate``
  * ``port_map.yaml``          — derived from DUT RTL
  * ``tb_<module>.sv``         — generated from port_map + template
  * ``wave.tcl``               — generated along with TB
  * ``stimulus_current.svh``   — generated by ``gen_stimulus.py``

Public API
----------
  StalenessResult        dataclass — per-artifact staleness finding
  StaleArtifactReport    dataclass — full report for one flow
  check_flow_staleness(verify_root, flow_decl, contract, consumer_root)
      → StaleArtifactReport
  check_all_flows(design_path, consumer_root)
      → list[StaleArtifactReport]
"""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


# ── Helpers ────────────────────────────────────────────────────────────────

def _mtime(path: Path) -> float:
    """Return the mtime of *path* or –∞ if it does not exist."""
    try:
        return path.stat().st_mtime
    except OSError:
        return float("-inf")


def _newest_mtime(paths: "list[Path]") -> float:
    """Return the most-recent mtime among the given paths (ignoring missing)."""
    mtimes = [_mtime(p) for p in paths if p.exists()]
    return max(mtimes) if mtimes else float("-inf")


# ── Result model ───────────────────────────────────────────────────────────

@dataclass
class StalenessResult:
    """One stale-artifact finding.

    Attributes:
        artifact_path: The generated artifact that appears stale.
        source_path:   The most-recently-modified source file.
        artifact_mtime: mtime of the artifact.
        source_mtime:  mtime of the source.
    """
    artifact_path:  Path
    source_path:    Path
    artifact_mtime: float
    source_mtime:   float

    @property
    def stale(self) -> bool:
        return self.source_mtime > self.artifact_mtime

    def message(self) -> str:
        import time
        a_age = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(self.artifact_mtime))
        s_age = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(self.source_mtime))
        return (
            f"{self.artifact_path.name} is stale\n"
            f"    artifact: {self.artifact_path}  [{a_age}]\n"
            f"    newer source: {self.source_path.name}  [{s_age}]"
        )


@dataclass
class StaleArtifactReport:
    """Full staleness report for one flow."""

    flow_name:     str
    stale_items:   list[StalenessResult] = field(default_factory=list)
    skipped:       list[str]             = field(default_factory=list)   # missing artifacts — not stale, just absent

    @property
    def has_stale(self) -> bool:
        return any(r.stale for r in self.stale_items)

    @property
    def stale_artifacts(self) -> list[StalenessResult]:
        return [r for r in self.stale_items if r.stale]


# ── Core check logic ───────────────────────────────────────────────────────

def check_flow_staleness(
    verify_root: Path,
    flow_decl: Any,           # fw_verify.design_contract.FlowDeclaration
    contract: Any,            # fw_verify.design_contract.VerifyDesignContract
    consumer_root: Path,
) -> StaleArtifactReport:
    """Check generated artifacts for one flow against their source files.

    Args:
        verify_root:   Plugin's ``verify/`` directory.
        flow_decl:     ``FlowDeclaration`` from ``design.verification.yml``.
        contract:      ``VerifyDesignContract`` container.
        consumer_root: Repository root for resolving relative paths.

    Returns:
        ``StaleArtifactReport`` listing which artifacts are stale.
    """
    report = StaleArtifactReport(flow_name=flow_decl.name)

    # ── Collect source mtimes ────────────────────────────────────────────
    design_yml = verify_root / "design.verification.yml"
    sources: list[Path] = [design_yml]

    # DUT RTL Verilog
    dut_rtl_source = getattr(flow_decl, "dut_rtl_source", None)
    if dut_rtl_source:
        verilog = consumer_root / dut_rtl_source / f"{flow_decl.top_module}.v"
        if verilog.exists():
            sources.append(verilog)

    # Dataset XML
    ds = None
    if hasattr(contract, "get_dataset") and getattr(flow_decl, "dataset", None):
        ds = contract.get_dataset(flow_decl.dataset)
    if ds:
        ds_xml = Path(getattr(ds, "xml", "") or "")
        if ds_xml.suffix and ds_xml.exists():
            sources.append(ds_xml)
        elif consumer_root and ds_xml.suffix:
            abs_xml = consumer_root / ds_xml
            if abs_xml.exists():
                sources.append(abs_xml)

    # gen_stimulus.py (affects stimulus freshness)
    gen_stimulus_py = verify_root / "tools" / "gen_stimulus.py"
    _CSIM_KINDS = {"hls_csim", "hls_cosim"}
    is_csim = flow_decl.kind in _CSIM_KINDS

    newest_source = _newest_mtime(sources)
    if newest_source == float("-inf"):
        # No sources exist yet — nothing to compare against
        report.skipped.append("no source files found to compare against")
        return report

    # Identify the most-recently modified source file for reporting
    def _newest_source_path() -> Path:
        existing = [(p, _mtime(p)) for p in sources if p.exists()]
        if not existing:
            return design_yml
        return max(existing, key=lambda x: x[1])[0]

    newest_src_path = _newest_source_path()

    # ── Check generated artifacts ────────────────────────────────────────
    from arc.verify.layout import resolve_generated_files, canonical_flow_dir

    flow_dir = canonical_flow_dir(verify_root, flow_decl.name)

    # verify.flow.yml — always check
    flow_yml = flow_dir / "verify.flow.yml"
    if flow_yml.exists():
        _check(report, flow_yml, newest_src_path, newest_source)

    if is_csim:
        # csim flows have no RTL artifacts
        return report

    gen = resolve_generated_files(
        verify_root, flow_decl.name, flow_decl.tb_module, is_csim=False
    )

    # port_map.yaml (source: DUT RTL)
    rtl_sources = [p for p in sources if p.suffix == ".v"]
    rtl_newest = _newest_mtime(rtl_sources) if rtl_sources else newest_source
    rtl_newest_path = max(
        ((p, _mtime(p)) for p in rtl_sources if p.exists()),
        key=lambda x: x[1],
        default=(newest_src_path, newest_source),
    )[0]

    if gen.port_map.exists():
        _check(report, gen.port_map, rtl_newest_path, rtl_newest)

    # tb_*.sv (source: port_map + design.verification.yml)
    tb_sources = [design_yml, gen.port_map]
    tb_newest = _newest_mtime(tb_sources)
    tb_newest_path = max(
        ((p, _mtime(p)) for p in tb_sources if p.exists()),
        key=lambda x: x[1],
        default=(newest_src_path, newest_source),
    )[0]

    if gen.tb_sv and gen.tb_sv.exists():
        _check(report, gen.tb_sv, tb_newest_path, tb_newest)

    if gen.wave_tcl.exists():
        _check(report, gen.wave_tcl, tb_newest_path, tb_newest)

    # stimulus_current.svh (source: gen_stimulus.py + dataset + design.yml)
    stim_sources = list(sources)
    if gen_stimulus_py.exists():
        stim_sources.append(gen_stimulus_py)
    stim_newest = _newest_mtime(stim_sources)
    stim_newest_path = max(
        ((p, _mtime(p)) for p in stim_sources if p.exists()),
        key=lambda x: x[1],
        default=(newest_src_path, newest_source),
    )[0]

    if gen.stimulus_svh.exists():
        _check(report, gen.stimulus_svh, stim_newest_path, stim_newest)

    return report


def _check(
    report: StaleArtifactReport,
    artifact: Path,
    source_path: Path,
    source_mtime: float,
) -> None:
    """Add a staleness finding to *report* (only if artifact is older)."""
    a_mtime = _mtime(artifact)
    result = StalenessResult(
        artifact_path=artifact,
        source_path=source_path,
        artifact_mtime=a_mtime,
        source_mtime=source_mtime,
    )
    if result.stale:
        report.stale_items.append(result)


def check_all_flows(
    design_path: "str | Path",
    consumer_root: "str | Path | None" = None,
) -> list[StaleArtifactReport]:
    """Run staleness checks for all flows declared in *design_path*.

    Args:
        design_path:   Path to ``design.verification.yml``.
        consumer_root: Repository root for resolved paths.

    Returns:
        List of ``StaleArtifactReport``, one per flow.
    """
    design_path = Path(design_path).resolve()
    if consumer_root is None:
        consumer_root = design_path.parents[2]
    else:
        consumer_root = Path(consumer_root).resolve()

    from arc.verify.design_contract import load_verify_design
    contract = load_verify_design(design_path)
    verify_root = design_path.parent

    return [
        check_flow_staleness(verify_root, flow, contract, consumer_root)
        for flow in contract.flows
    ]
