#!/usr/bin/env python3
"""gen_stimulus.py — Generate stimulus_current.svh for each trigger_demo xsim flow.

Reads the golden XML dataset and derives expected outputs from the known
module algorithms, then writes a self-contained SV task ``run_stimulus()``
for each module.

The generated SVH is included at module level in the TB:

    // In tb_<module>_xsim.sv (at module scope):
    `include "stimulus_current.svh"   // defines task run_stimulus()
    ...
    initial begin
        ...
        run_stimulus();   // drives all 4 golden events + checks outputs
        ...
    end

Algorithm constants (from trigger_types.h):
  - PHI_W = 16 bits; phi_corrected = phi_in + 1
  - ETA_W = 16 bits; passes through unchanged
  - DECODED_HIT = {phi_corrected[15:0], eta[15:0]}
  - DECODED_VALID = raw_valid & (raw_hit != 0)
  - TRIGGER_THRESHOLD = 2   (n_hits >= 2 → accept)
  - trigger_word = (accept << 31) | (quality << 16)

Public API::

    generate_all(consumer_root, xml_path)    → list[Path]
    generate_for_module(module, events, out) → Path
    parse_golden_xml(xml_path)               → list[Event]

CLI::

    python3 gen_stimulus.py                  # generate all 5 SVH files
    python3 gen_stimulus.py --module hit_decoder
    python3 gen_stimulus.py --dry-run
"""
from __future__ import annotations

import argparse
import sys
import textwrap
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# ── Path bootstrap ─────────────────────────────────────────────────────────
_HERE         = Path(__file__).resolve().parent
_PLUGIN_ROOT  = _HERE.parent           # plugins/trigger_demo/forge/verify/
_PLUGIN_VERIFY = _PLUGIN_ROOT           # alias
_REPO_ROOT    = _HERE.parents[4]       # arc-framework/

_DEFAULT_XML = (
    _REPO_ROOT
    / "plugins/trigger_demo/forge/verify/schemas/data/trigger_demo_golden.xml"
)

# ── Golden data model ──────────────────────────────────────────────────────

@dataclass
class ChannelHit:
    ch_id:  int
    raw:    int   # 32-bit
    valid:  int   # 0 or 1

@dataclass
class GoldenExpected:
    n_hits:  int
    phi_sum: int
    accept:  int
    quality: int
    word:    int

@dataclass
class Event:
    event_id: int
    bx:       int
    channels: list[ChannelHit] = field(default_factory=list)
    golden:   GoldenExpected | None = None


def parse_golden_xml(xml_path: Path) -> list[Event]:
    """Parse trigger_demo_golden.xml into Event objects."""
    tree = ET.parse(xml_path)
    root = tree.getroot()
    events: list[Event] = []
    for ev_el in root.findall("event"):
        ev = Event(
            event_id=int(ev_el.get("id", 0)),
            bx=int(ev_el.get("bx", 0)),
        )
        for ch_el in ev_el.findall("ch"):
            raw_str = ch_el.get("raw", "0")
            ev.channels.append(ChannelHit(
                ch_id=int(ch_el.get("id", 0)),
                raw=int(raw_str, 16) if raw_str.startswith("0x") else int(raw_str),
                valid=int(ch_el.get("valid", 0)),
            ))
        gold_el = ev_el.find("golden")
        if gold_el is not None:
            def _h(s: str) -> int:
                s = s or "0"
                return int(s, 16) if s.startswith("0x") else int(s)
            ev.golden = GoldenExpected(
                n_hits=int(gold_el.get("n_hits", 0)),
                phi_sum=_h(gold_el.get("phi_sum", "0")),
                accept=int(gold_el.get("accept", 0)),
                quality=int(gold_el.get("quality", 0)),
                word=_h(gold_el.get("word", "0")),
            )
        # Ensure 4 channels (pad with zeros if missing)
        while len(ev.channels) < 4:
            ev.channels.append(ChannelHit(ch_id=len(ev.channels), raw=0, valid=0))
        events.append(ev)
    return events


# ── Derived computation helpers ────────────────────────────────────────────

def _decoded_hit(raw: int, valid: int) -> tuple[int, int]:
    """Compute (decoded_hit, decoded_valid) exactly as hit_decoder.cpp does."""
    phi = (raw >> 16) & 0xFFFF
    eta = raw & 0xFFFF
    phi_corrected = (phi + 1) & 0xFFFF
    d_hit = (phi_corrected << 16) | eta
    d_valid = valid & (1 if raw != 0 else 0)
    return d_hit, d_valid


# ── Per-module SVH generators ──────────────────────────────────────────────

_HDR = """\
// stimulus_current.svh — generated for {module}_xsim
// Generated by gen_stimulus.py — DO NOT EDIT
// Source: {xml_name}
//
// Defines task run_stimulus() — called from the TB initial block
// after reset/idle phases.  Uses $fatal(1,...) on any assertion failure.
"""

def _gen_hit_decoder(events: list[Event]) -> str:
    """Tests hit_decoder one channel per clock cycle across all events."""
    lines: list[str] = [_HDR.replace("{module}", "hit_decoder")
                            .replace("{xml_name}", "trigger_demo_golden.xml"),
                        "task automatic run_stimulus();",
                        "  integer _fail;",
                        "  _fail = 0;",
                        ""]

    for ev in events:
        for ch in ev.channels:
            d_hit, d_valid = _decoded_hit(ch.raw, ch.valid)
            lines.append(
                f"  // Event {ev.event_id} ch{ch.ch_id}: "
                f"raw=0x{ch.raw:08X} valid={ch.valid}"
                f"  →  decoded=0x{d_hit:08X} valid={d_valid}"
            )
            lines.append(f"  @(posedge ap_clk);")
            lines.append(f"  raw_hit   = 32'h{ch.raw:08X};")
            lines.append(f"  raw_valid = 1'b{ch.valid};")
            lines.append(f"  #1;  // combinational settle")
            if ch.valid and ch.raw != 0:
                lines.append(
                    f"  if (decoded_hit !== 32'h{d_hit:08X}) begin "
                    f"$display(\"FAIL [E{ev.event_id}.ch{ch.ch_id}] "
                    f"decoded_hit=0x%08X expect=0x{d_hit:08X}\", decoded_hit); "
                    f"_fail = 1; end"
                )
            lines.append(
                f"  if (decoded_valid !== 1'b{d_valid}) begin "
                f"$display(\"FAIL [E{ev.event_id}.ch{ch.ch_id}] "
                f"decoded_valid=%0b expect={d_valid}\", decoded_valid); "
                f"_fail = 1; end"
            )
            lines.append("")

    lines += [
        "  if (_fail) $fatal(1, \"TB FAIL: hit_decoder_xsim — %0d assertion(s) failed\", _fail);",
        "endtask",
    ]
    return "\n".join(lines) + "\n"


def _gen_hit_collector(events: list[Event]) -> str:
    """Tests hit_collector with all 4 decoded channels simultaneously."""
    lines: list[str] = [_HDR.replace("{module}", "hit_collector")
                            .replace("{xml_name}", "trigger_demo_golden.xml"),
                        "task automatic run_stimulus();",
                        "  integer _fail;",
                        "  _fail = 0;",
                        ""]

    for ev in events:
        g = ev.golden
        # Compute decoded channel values (hit_collector receives decoded hits)
        dec = [_decoded_hit(ch.raw, ch.valid) for ch in ev.channels]

        lines.append(f"  // Event {ev.event_id}: n_hits={g.n_hits} phi_sum=0x{g.phi_sum:04X}")
        lines.append(f"  @(posedge ap_clk);")
        for i, (d_hit, d_valid) in enumerate(dec):
            lines.append(f"  in_hit_{i}   = 32'h{d_hit:08X};")
            lines.append(f"  in_valid_{i} = 1'b{d_valid};")
        lines.append(f"  #1;  // combinational settle")
        lines.append(
            f"  if (n_hits !== 3'd{g.n_hits}) begin "
            f"$display(\"FAIL [E{ev.event_id}] n_hits=%0d expect={g.n_hits}\", n_hits); "
            f"_fail = 1; end"
        )
        lines.append(
            f"  if (phi_sum !== 16'h{g.phi_sum:04X}) begin "
            f"$display(\"FAIL [E{ev.event_id}] phi_sum=0x%04X expect=0x{g.phi_sum:04X}\", phi_sum); "
            f"_fail = 1; end"
        )
        coll_valid = 1 if g.n_hits > 0 else 0
        lines.append(
            f"  if (collector_valid !== 1'b{coll_valid}) begin "
            f"$display(\"FAIL [E{ev.event_id}] collector_valid=%0b expect={coll_valid}\", collector_valid); "
            f"_fail = 1; end"
        )
        lines.append("")

    lines += [
        "  if (_fail) $fatal(1, \"TB FAIL: hit_collector_xsim — %0d assertion(s) failed\", _fail);",
        "endtask",
    ]
    return "\n".join(lines) + "\n"


def _gen_trigger_logic(events: list[Event]) -> str:
    """Tests trigger_logic with n_hits and phi_sum from each golden event."""
    THRESHOLD = 2
    lines: list[str] = [_HDR.replace("{module}", "trigger_logic")
                            .replace("{xml_name}", "trigger_demo_golden.xml"),
                        "task automatic run_stimulus();",
                        "  integer _fail;",
                        "  _fail = 0;",
                        ""]

    for ev in events:
        g = ev.golden
        # trigger_logic input validity: matches collector_valid (n_hits > 0)
        in_valid = 1 if g.n_hits > 0 else 0
        exp_accept  = 1 if g.n_hits >= THRESHOLD else 0
        exp_quality = g.n_hits & 0xFF

        lines.append(
            f"  // Event {ev.event_id}: n_hits={g.n_hits} → accept={exp_accept} quality={exp_quality}"
        )
        lines.append(f"  @(posedge ap_clk);")
        lines.append(f"  n_hits   = 3'd{g.n_hits};")
        lines.append(f"  phi_sum  = 16'h{g.phi_sum:04X};")
        lines.append(f"  in_valid = 1'b{in_valid};")
        lines.append(f"  #1;  // combinational settle")
        lines.append(
            f"  if (trigger_accept !== 1'b{exp_accept}) begin "
            f"$display(\"FAIL [E{ev.event_id}] trigger_accept=%0b expect={exp_accept}\", trigger_accept); "
            f"_fail = 1; end"
        )
        lines.append(
            f"  if (trigger_quality !== 8'd{exp_quality}) begin "
            f"$display(\"FAIL [E{ev.event_id}] trigger_quality=%0d expect={exp_quality}\", trigger_quality); "
            f"_fail = 1; end"
        )
        lines.append(
            f"  if (trigger_valid !== 1'b{in_valid}) begin "
            f"$display(\"FAIL [E{ev.event_id}] trigger_valid=%0b expect={in_valid}\", trigger_valid); "
            f"_fail = 1; end"
        )
        lines.append("")

    lines += [
        "  if (_fail) $fatal(1, \"TB FAIL: trigger_logic_xsim — %0d assertion(s) failed\", _fail);",
        "endtask",
    ]
    return "\n".join(lines) + "\n"


def _gen_trigger_output(events: list[Event]) -> str:
    """Tests trigger_output with golden trigger decision fields."""
    lines: list[str] = [_HDR.replace("{module}", "trigger_output")
                            .replace("{xml_name}", "trigger_demo_golden.xml"),
                        "task automatic run_stimulus();",
                        "  integer _fail;",
                        "  _fail = 0;",
                        ""]

    for ev in events:
        g = ev.golden
        # trigger_output valid = same as trigger_valid = collector_valid
        t_valid = 1 if g.n_hits > 0 else 0
        # word = (accept << 31) | (quality << 16)
        exp_word = ((g.accept & 1) << 31) | ((g.quality & 0xFF) << 16)

        lines.append(
            f"  // Event {ev.event_id}: accept={g.accept} quality={g.quality}"
            f" → word=0x{exp_word:08X}"
        )
        lines.append(f"  @(posedge ap_clk);")
        lines.append(f"  trigger_accept  = 1'b{g.accept};")
        lines.append(f"  trigger_quality = 8'd{g.quality};")
        lines.append(f"  trigger_valid   = 1'b{t_valid};")
        lines.append(f"  #1;  // combinational settle")
        lines.append(
            f"  if (trigger_word !== 32'h{exp_word:08X}) begin "
            f"$display(\"FAIL [E{ev.event_id}] trigger_word=0x%08X expect=0x{exp_word:08X}\", trigger_word); "
            f"_fail = 1; end"
        )
        lines.append(
            f"  if (out_valid !== 1'b{t_valid}) begin "
            f"$display(\"FAIL [E{ev.event_id}] out_valid=%0b expect={t_valid}\", out_valid); "
            f"_fail = 1; end"
        )
        lines.append("")

    lines += [
        "  if (_fail) $fatal(1, \"TB FAIL: trigger_output_xsim — %0d assertion(s) failed\", _fail);",
        "endtask",
    ]
    return "\n".join(lines) + "\n"


def _gen_trigger_pipeline(events: list[Event]) -> str:
    """Tests the generated algo_top integration with one event at a time."""
    latency_cycles = 6
    lines: list[str] = [_HDR.replace("{module}", "trigger_pipeline")
                            .replace("{xml_name}", "trigger_demo_golden.xml"),
                        "task automatic run_stimulus();",
                        "  integer _fail;",
                        "  integer _step;",
                        "  _fail = 0;",
                        ""]

    for ev in events:
        g = ev.golden
        expected_valid = 1 if g.n_hits > 0 else 0
        lines.append(
            f"  // Event {ev.event_id}: expected word=0x{g.word:08X} valid={expected_valid}"
        )
        lines.append("  @(posedge ap_clk);")
        for idx, ch in enumerate(ev.channels):
            lines.append(f"  dec_{idx}_raw_hit   = 32'h{ch.raw:08X};")
            lines.append(f"  dec_{idx}_raw_valid = 1'b{ch.valid};")
        lines.append("  @(posedge ap_clk);")
        for idx in range(4):
            lines.append(f"  dec_{idx}_raw_hit   = '0;")
            lines.append(f"  dec_{idx}_raw_valid = 1'b0;")
        lines.append(f"  for (_step = 0; _step < {latency_cycles}; _step = _step + 1) @(posedge ap_clk);")
        lines.append("  #1;")
        if expected_valid:
            lines.append(
                f"  if (tout_out_valid !== 1'b1) begin "
                f"$display(\"FAIL [E{ev.event_id}] tout_out_valid=%0b expect=1\", tout_out_valid); "
                f"_fail = 1; end"
            )
            lines.append(
                f"  if (tout_trigger_word !== 32'h{g.word:08X}) begin "
                f"$display(\"FAIL [E{ev.event_id}] tout_trigger_word=0x%08X expect=0x{g.word:08X}\", tout_trigger_word); "
                f"_fail = 1; end"
            )
        else:
            lines.append(
                f"  if (tout_out_valid !== 1'b0) begin "
                f"$display(\"FAIL [E{ev.event_id}] tout_out_valid=%0b expect=0\", tout_out_valid); "
                f"_fail = 1; end"
            )
        lines.append("")

    lines += [
        "  if (_fail) $fatal(1, \"TB FAIL: trigger_pipeline_xsim — %0d assertion(s) failed\", _fail);",
        "endtask",
    ]
    return "\n".join(lines) + "\n"


# ── Module dispatch ────────────────────────────────────────────────────────

_GENERATORS: dict[str, Any] = {
    "hit_decoder":    _gen_hit_decoder,
    "hit_collector":  _gen_hit_collector,
    "trigger_logic":  _gen_trigger_logic,
    "trigger_output": _gen_trigger_output,
    "trigger_pipeline": _gen_trigger_pipeline,
}


# ── Public API ─────────────────────────────────────────────────────────────

def generate_for_module(
    module: str,
    events: list[Event],
    output_path: Path,
    dry_run: bool = False,
) -> Path:
    """Generate ``stimulus_current.svh`` for *module* and write to *output_path*.

    Args:
        module:      One of hit_decoder, hit_collector, trigger_logic, trigger_output,
                 trigger_pipeline.
        events:      Parsed golden events (from parse_golden_xml).
        output_path: Destination path for the SVH file.
        dry_run:     If True, return path without writing.

    Returns:
        The path that was (or would be) written.
    """
    gen_fn = _GENERATORS.get(module)
    if gen_fn is None:
        raise ValueError(f"Unknown module {module!r}. Known: {list(_GENERATORS)}")
    content = gen_fn(events)
    if not dry_run:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content)
    return output_path


def generate_all(
    xml_path: Path,
    verify_root: Path,
    module_filter: str | None = None,
    dry_run: bool = False,
) -> list[Path]:
    """Generate stimulus files for all xsim flows.

    Args:
        xml_path:      Path to trigger_demo_golden.xml.
        verify_root:   plugins/trigger_demo/forge/verify/ directory.
        module_filter: If set, only generate for the named module.
        dry_run:       Print plan without writing.

    Returns:
        List of output paths.
    """
    events = parse_golden_xml(xml_path)
    results: list[Path] = []
    for module, gen_fn in _GENERATORS.items():
        if module_filter and module != module_filter:
            continue
        flow_dir_name = f"{module}_xsim" if module != "trigger_pipeline" else "trigger_pipeline_xsim"
        flow_dir = verify_root / flow_dir_name
        out_path = flow_dir / "stimulus_current.svh"
        generate_for_module(module, events, out_path, dry_run=dry_run)
        action = "(dry-run)" if dry_run else f"→ {out_path.relative_to(verify_root.parent)}"
        print(f"  [{flow_dir_name}] events={len(events)}  {action}")
        results.append(out_path)
    return results


# ── CLI entry point ────────────────────────────────────────────────────────

def _main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Generate stimulus_current.svh for trigger_demo xsim flows"
    )
    p.add_argument("--module", metavar="NAME",
                   help="Only generate for this module (default: all)")
    p.add_argument("--dry-run", action="store_true",
                   help="Print plan without writing files")
    p.add_argument("--xml",
                   default=str(_DEFAULT_XML),
                   metavar="PATH",
                   help=f"Path to golden XML  [default: {_DEFAULT_XML}]")
    p.add_argument("--verify-root",
                   default=str(_PLUGIN_VERIFY),
                   metavar="PATH",
                   help="plugins/trigger_demo/forge/verify/  [default: auto]")
    args = p.parse_args(argv)

    xml_path    = Path(args.xml)
    verify_root = Path(args.verify_root)

    if not xml_path.exists():
        print(f"ERROR: golden XML not found: {xml_path}", file=sys.stderr)
        return 1

    print(f"gen_stimulus — trigger_demo xsim stimulus generator")
    print(f"  XML:         {xml_path}")
    print(f"  verify_root: {verify_root}")
    print(f"  dry_run:     {args.dry_run}")
    print()
    generate_all(
        xml_path=xml_path,
        verify_root=verify_root,
        module_filter=args.module,
        dry_run=args.dry_run,
    )
    print()
    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(_main())
