// stimulus_current.svh — generated by plugin gen_stimulus.py
// DO NOT EDIT — regenerate by running gen_stimulus.py
//
// Framework contract:
//   * This file is `include'd into the testbench module body.
//   * Must declare exactly one task: ``task automatic run_stimulus();``
//   * The task is called once after reset + idle cycles.
//   * Signals ap_clk, ap_rst (and all DUT ports) are in scope.

// flow=cdc_xsim (multi-domain CDC)

task automatic run_stimulus();

    // ── reset ──
    ap_rst <= 1'b1;
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    ap_rst <= 1'b0;
    @(posedge ap_clk);
    // ── end: reset ──


    // ── drive_constants ──
    ctrl_level_enable_in <= 1'b1;
    ctrl_mailbox_threshold_in <= 8'hAB;
    ctrl_mailbox_kernel_mode_in <= 2'h2;
    ctrl_mailbox_frame_limit_in <= 16'hCAFE;
    pxsink_result_data_in <= 26'h3ABCDEF;
    outsink_level_error_in <= 1'b1;
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    // ── end: drive_constants ──


    // ── pulse_apply ──
    ctrl_pulse_apply_in <= 1'b1;
    @(posedge ap_clk);
    ctrl_pulse_apply_in <= 1'b0;
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    // ── end: pulse_apply ──


    // ── pulse_frame_done ──
    outsink_pulse_frame_done_pulse_in <= 1'b1;
    @(posedge clk_output);
    outsink_pulse_frame_done_pulse_in <= 1'b0;
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    // ── end: pulse_frame_done ──


    // ── checks ──
    $display("FORGE_CHECK|check_id=error_level_status_check|label=error_level_status_check|signal=ctrl_level_error_level_status|expected=0x1|observed=0x%h|width=1|passed=%0d", ctrl_level_error_level_status, (ctrl_level_error_level_status === 1'b1));
    if (ctrl_level_error_level_status !== 1'b1) begin
      $display("FAIL: error_level_status_check — expected 1'b1, got %0h", ctrl_level_error_level_status);
      $fatal(1, "Check failed: error_level_status_check");
    end
    $display("FORGE_CHECK|check_id=frame_done_count_check|label=frame_done_count_check|signal=ctrl_pulse_frame_done_count|expected=0x01|observed=0x%h|width=8|passed=%0d", ctrl_pulse_frame_done_count, (ctrl_pulse_frame_done_count === 8'h01));
    if (ctrl_pulse_frame_done_count !== 8'h01) begin
      $display("FAIL: frame_done_count_check — expected 8'h01, got %0h", ctrl_pulse_frame_done_count);
      $fatal(1, "Check failed: frame_done_count_check");
    end
    $display("FORGE_CHECK|check_id=enable_status_check|label=enable_status_check|signal=pxsink_enable_status|expected=0x1|observed=0x%h|width=1|passed=%0d", pxsink_enable_status, (pxsink_enable_status === 1'b1));
    if (pxsink_enable_status !== 1'b1) begin
      $display("FAIL: enable_status_check — expected 1'b1, got %0h", pxsink_enable_status);
      $fatal(1, "Check failed: enable_status_check");
    end
    $display("FORGE_CHECK|check_id=apply_count_check|label=apply_count_check|signal=pxsink_apply_count|expected=0x01|observed=0x%h|width=8|passed=%0d", pxsink_apply_count, (pxsink_apply_count === 8'h01));
    if (pxsink_apply_count !== 8'h01) begin
      $display("FAIL: apply_count_check — expected 8'h01, got %0h", pxsink_apply_count);
      $fatal(1, "Check failed: apply_count_check");
    end
    $display("FORGE_CHECK|check_id=mailbox_status_check|label=mailbox_status_check|signal=pxsink_mailbox_status|expected=0x2aecafe|observed=0x%h|width=26|passed=%0d", pxsink_mailbox_status, (pxsink_mailbox_status === 26'h2AECAFE));
    if (pxsink_mailbox_status !== 26'h2AECAFE) begin
      $display("FAIL: mailbox_status_check — expected 26'h2AECAFE, got %0h", pxsink_mailbox_status);
      $fatal(1, "Check failed: mailbox_status_check");
    end
    $display("FORGE_CHECK|check_id=result_status_check|label=result_status_check|signal=outsink_level_result_status|expected=0x3abcdef|observed=0x%h|width=26|passed=%0d", outsink_level_result_status, (outsink_level_result_status === 26'h3ABCDEF));
    if (outsink_level_result_status !== 26'h3ABCDEF) begin
      $display("FAIL: result_status_check — expected 26'h3ABCDEF, got %0h", outsink_level_result_status);
      $fatal(1, "Check failed: result_status_check");
    end
    // ── end: checks ──

endtask : run_stimulus
