// ============================================================
// tb_algo_top.sv — Generated by gen-sim
// Flow:         cdc_xsim
// Top module:   algo_top
// Generated at: 2026-08-05 09:21 UTC
// DO NOT EDIT — regenerate with: gen-sim cdc_xsim
// ============================================================
`timescale 1ns/1ps

module tb_algo_top;

  // ── Timing parameters ────────────────────────────────────
  localparam real CLK_PERIOD_NS              = 20.0;
  localparam int  RESET_CYCLES               = 4;
  localparam int  IDLE_CYCLES_AFTER_RESET    = 0;
  localparam int  POST_STIMULUS_DRAIN_CYCLES = 8;

  // ── Clock and reset ──────────────────────────────────────
  logic ap_clk;
  logic ap_rst;

  initial ap_clk = 1'b0;
  always #(CLK_PERIOD_NS / 2.0) ap_clk = ~ap_clk;

  // ── Additional clock domains (release-plan Phase 10, slice 10.4) ──
  logic clk_output;
  initial clk_output = 1'b0;
  always #(8.0 / 2.0) clk_output = ~clk_output;
  logic clk_pixel;
  initial clk_pixel = 1'b0;
  always #(5.0 / 2.0) clk_pixel = ~clk_pixel;


    `ifndef PROBE_LOG
    localparam int PROBE_LOG = 0;
    `else
    localparam int PROBE_LOG = `PROBE_LOG;
    `endif

  // ── DUT signals (from port_map) ───────────────────────
  wire  ctrl_level_error_level_status;
  wire  [7:0] ctrl_pulse_frame_done_count;
  wire  [25:0] outsink_level_result_status;
  wire  [7:0] pxsink_apply_count;
  wire  pxsink_enable_status;
  wire  [25:0] pxsink_mailbox_status;
  logic ctrl_level_enable_in;
  logic [15:0] ctrl_mailbox_frame_limit_in;
  logic [1:0] ctrl_mailbox_kernel_mode_in;
  logic [7:0] ctrl_mailbox_threshold_in;
  logic ctrl_pulse_apply_in;
  logic outsink_level_error_in;
  logic outsink_pulse_frame_done_pulse_in;
  logic [25:0] pxsink_result_data_in;
  logic rst_output;
  logic rst_pixel;


  // ── Stimulus ─────────────────────────────────────────────
  `include "stimulus_current.svh"

  // ── DUT instantiation ────────────────────────────────────
  algo_top dut (
    .ctrl_level_error_level_status(ctrl_level_error_level_status),
    .ctrl_pulse_frame_done_count(ctrl_pulse_frame_done_count),
    .outsink_level_result_status(outsink_level_result_status),
    .pxsink_apply_count(pxsink_apply_count),
    .pxsink_enable_status(pxsink_enable_status),
    .pxsink_mailbox_status(pxsink_mailbox_status),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .clk_output(clk_output),
    .clk_pixel(clk_pixel),
    .ctrl_level_enable_in(ctrl_level_enable_in),
    .ctrl_mailbox_frame_limit_in(ctrl_mailbox_frame_limit_in),
    .ctrl_mailbox_kernel_mode_in(ctrl_mailbox_kernel_mode_in),
    .ctrl_mailbox_threshold_in(ctrl_mailbox_threshold_in),
    .ctrl_pulse_apply_in(ctrl_pulse_apply_in),
    .outsink_level_error_in(outsink_level_error_in),
    .outsink_pulse_frame_done_pulse_in(outsink_pulse_frame_done_pulse_in),
    .pxsink_result_data_in(pxsink_result_data_in),
    .rst_output(rst_output),
    .rst_pixel(rst_pixel)
  );

  // ── Cycle counter ────────────────────────────────────────
  integer cycle_count;

  // ── Output trace ─────────────────────────────────────────
  integer trace_fd;
    integer probe_fd;

  // ── Main test sequence ──────────────────────────────────
  initial begin
    cycle_count = 0;
    ap_rst      = 1'b1;
    ctrl_level_enable_in = '0;
    ctrl_mailbox_frame_limit_in = '0;
    ctrl_mailbox_kernel_mode_in = '0;
    ctrl_mailbox_threshold_in = '0;
    ctrl_pulse_apply_in = '0;
    outsink_level_error_in = '0;
    outsink_pulse_frame_done_pulse_in = '0;
    pxsink_result_data_in = '0;
    rst_output = '0;
    rst_pixel = '0;

    trace_fd = $fopen("algo_top_outputs.csv", "w");
    $fwrite(trace_fd, "cycle,ctrl_level_error_level_status,ctrl_pulse_frame_done_count,outsink_level_result_status,pxsink_apply_count,pxsink_enable_status,pxsink_mailbox_status\n");


    // Reset phase
    repeat (RESET_CYCLES) @(posedge ap_clk);
    ap_rst = 1'b0;

    // Idle settle phase
    repeat (IDLE_CYCLES_AFTER_RESET) @(posedge ap_clk);

    // Stimulus phase
    run_stimulus();  // defined in stimulus_current.svh (framework-standard handoff contract)

    // Drain phase
    repeat (POST_STIMULUS_DRAIN_CYCLES) @(posedge ap_clk);

    $fclose(trace_fd);

    $display("TB PASS: cdc_xsim completed");
    $finish;
  end

  // ── Output logging ───────────────────────────────────────
  always @(posedge ap_clk) begin
    if (!ap_rst) begin
      $fwrite(trace_fd, "%0d,%0b,%0h,%0h,%0h,%0b,%0h\n", cycle_count, ctrl_level_error_level_status, ctrl_pulse_frame_done_count, outsink_level_result_status, pxsink_apply_count, pxsink_enable_status, pxsink_mailbox_status);

      cycle_count <= cycle_count + 1;
    end
  end

endmodule
