// stimulus_current.svh — generated by plugin gen_stimulus.py
// DO NOT EDIT — regenerate by running gen_stimulus.py
//
// Framework contract:
//   * This file is `include'd into the testbench module body.
//   * Must declare exactly one task: ``task automatic run_stimulus();``
//   * The task is called once after reset + idle cycles.
//   * Signals ap_clk, ap_rst (and all DUT ports) are in scope.

// flow=tile_stats_xsim (streamed full frame, back-to-back)

task automatic run_stimulus();

    // ── reset ──
    ap_rst <= 1'b1;
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    ap_rst <= 1'b0;
    @(posedge ap_clk);
    // ── end: reset ──


    // ── cycle_0 ──
    norm_pixel <= 8'h00;
    norm_x <= 12'h000;
    norm_y <= 12'h000;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_0 ──


    // ── cycle_1 ──
    norm_pixel <= 8'h04;
    norm_x <= 12'h001;
    norm_y <= 12'h000;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_1 ──


    // ── cycle_2 ──
    norm_pixel <= 8'h08;
    norm_x <= 12'h002;
    norm_y <= 12'h000;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_2 ──


    // ── cycle_3 ──
    norm_pixel <= 8'h0C;
    norm_x <= 12'h003;
    norm_y <= 12'h000;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_3 ──


    // ── cycle_4 ──
    norm_pixel <= 8'h10;
    norm_x <= 12'h004;
    norm_y <= 12'h000;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_4 ──


    // ── cycle_5 ──
    norm_pixel <= 8'h14;
    norm_x <= 12'h005;
    norm_y <= 12'h000;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_5 ──


    // ── cycle_6 ──
    norm_pixel <= 8'h18;
    norm_x <= 12'h006;
    norm_y <= 12'h000;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_6 ──


    // ── cycle_7 ──
    norm_pixel <= 8'h1C;
    norm_x <= 12'h007;
    norm_y <= 12'h000;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b1;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_7 ──


    // ── cycle_8 ──
    norm_pixel <= 8'h20;
    norm_x <= 12'h000;
    norm_y <= 12'h001;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_8 ──


    // ── cycle_9 ──
    norm_pixel <= 8'h24;
    norm_x <= 12'h001;
    norm_y <= 12'h001;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_9 ──


    // ── cycle_10 ──
    norm_pixel <= 8'h28;
    norm_x <= 12'h002;
    norm_y <= 12'h001;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_10 ──


    // ── cycle_11 ──
    norm_pixel <= 8'h2C;
    norm_x <= 12'h003;
    norm_y <= 12'h001;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_11 ──


    // ── cycle_12 ──
    norm_pixel <= 8'h30;
    norm_x <= 12'h004;
    norm_y <= 12'h001;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_12 ──


    // ── cycle_13 ──
    norm_pixel <= 8'h34;
    norm_x <= 12'h005;
    norm_y <= 12'h001;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_13 ──


    // ── cycle_14 ──
    norm_pixel <= 8'h38;
    norm_x <= 12'h006;
    norm_y <= 12'h001;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_14 ──


    // ── cycle_15 ──
    norm_pixel <= 8'h3C;
    norm_x <= 12'h007;
    norm_y <= 12'h001;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b1;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_15 ──


    // ── cycle_16 ──
    norm_pixel <= 8'h40;
    norm_x <= 12'h000;
    norm_y <= 12'h002;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_16 ──


    // ── cycle_17 ──
    norm_pixel <= 8'h44;
    norm_x <= 12'h001;
    norm_y <= 12'h002;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_17 ──


    // ── cycle_18 ──
    norm_pixel <= 8'h48;
    norm_x <= 12'h002;
    norm_y <= 12'h002;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_18 ──


    // ── cycle_19 ──
    norm_pixel <= 8'h4C;
    norm_x <= 12'h003;
    norm_y <= 12'h002;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_19 ──


    // ── cycle_20 ──
    norm_pixel <= 8'h50;
    norm_x <= 12'h004;
    norm_y <= 12'h002;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_20 ──


    // ── cycle_21 ──
    norm_pixel <= 8'h54;
    norm_x <= 12'h005;
    norm_y <= 12'h002;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_21 ──


    // ── cycle_22 ──
    norm_pixel <= 8'h58;
    norm_x <= 12'h006;
    norm_y <= 12'h002;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_22 ──


    // ── cycle_23 ──
    norm_pixel <= 8'h5C;
    norm_x <= 12'h007;
    norm_y <= 12'h002;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b1;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_23 ──


    // ── cycle_24 ──
    norm_pixel <= 8'h60;
    norm_x <= 12'h000;
    norm_y <= 12'h003;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_24 ──


    // ── cycle_25 ──
    norm_pixel <= 8'h64;
    norm_x <= 12'h001;
    norm_y <= 12'h003;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_25 ──


    // ── cycle_26 ──
    norm_pixel <= 8'h68;
    norm_x <= 12'h002;
    norm_y <= 12'h003;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_26 ──


    // ── cycle_27 ──
    norm_pixel <= 8'h6C;
    norm_x <= 12'h003;
    norm_y <= 12'h003;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_27 ──


    // ── cycle_28 ──
    norm_pixel <= 8'h70;
    norm_x <= 12'h004;
    norm_y <= 12'h003;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_28 ──


    // ── cycle_29 ──
    norm_pixel <= 8'h74;
    norm_x <= 12'h005;
    norm_y <= 12'h003;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_29 ──


    // ── cycle_30 ──
    norm_pixel <= 8'h78;
    norm_x <= 12'h006;
    norm_y <= 12'h003;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_30 ──


    // ── cycle_31 ──
    norm_pixel <= 8'h7C;
    norm_x <= 12'h007;
    norm_y <= 12'h003;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b1;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_31 ──


    // ── cycle_32 ──
    norm_pixel <= 8'h80;
    norm_x <= 12'h000;
    norm_y <= 12'h004;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_32 ──


    // ── cycle_33 ──
    norm_pixel <= 8'h84;
    norm_x <= 12'h001;
    norm_y <= 12'h004;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_33 ──


    // ── cycle_34 ──
    norm_pixel <= 8'h88;
    norm_x <= 12'h002;
    norm_y <= 12'h004;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_34 ──


    // ── cycle_35 ──
    norm_pixel <= 8'h8C;
    norm_x <= 12'h003;
    norm_y <= 12'h004;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_35 ──


    // ── cycle_36 ──
    norm_pixel <= 8'h90;
    norm_x <= 12'h004;
    norm_y <= 12'h004;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_36 ──


    // ── cycle_37 ──
    norm_pixel <= 8'h94;
    norm_x <= 12'h005;
    norm_y <= 12'h004;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_37 ──


    // ── cycle_38 ──
    norm_pixel <= 8'h98;
    norm_x <= 12'h006;
    norm_y <= 12'h004;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_38 ──


    // ── cycle_39 ──
    norm_pixel <= 8'h9C;
    norm_x <= 12'h007;
    norm_y <= 12'h004;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b1;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_39 ──


    // ── cycle_40 ──
    norm_pixel <= 8'hA0;
    norm_x <= 12'h000;
    norm_y <= 12'h005;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_40 ──


    // ── cycle_41 ──
    norm_pixel <= 8'hA4;
    norm_x <= 12'h001;
    norm_y <= 12'h005;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_41 ──


    // ── cycle_42 ──
    norm_pixel <= 8'hA8;
    norm_x <= 12'h002;
    norm_y <= 12'h005;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_42 ──


    // ── cycle_43 ──
    norm_pixel <= 8'hAC;
    norm_x <= 12'h003;
    norm_y <= 12'h005;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_43 ──


    // ── cycle_44 ──
    norm_pixel <= 8'hB0;
    norm_x <= 12'h004;
    norm_y <= 12'h005;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_44 ──


    // ── cycle_45 ──
    norm_pixel <= 8'hB4;
    norm_x <= 12'h005;
    norm_y <= 12'h005;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_45 ──


    // ── cycle_46 ──
    norm_pixel <= 8'hB8;
    norm_x <= 12'h006;
    norm_y <= 12'h005;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_46 ──


    // ── cycle_47 ──
    norm_pixel <= 8'hBC;
    norm_x <= 12'h007;
    norm_y <= 12'h005;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b1;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_47 ──


    // ── cycle_48 ──
    norm_pixel <= 8'hC0;
    norm_x <= 12'h000;
    norm_y <= 12'h006;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_48 ──


    // ── cycle_49 ──
    norm_pixel <= 8'hC4;
    norm_x <= 12'h001;
    norm_y <= 12'h006;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_49 ──


    // ── cycle_50 ──
    norm_pixel <= 8'hC8;
    norm_x <= 12'h002;
    norm_y <= 12'h006;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_50 ──


    // ── cycle_51 ──
    norm_pixel <= 8'hCC;
    norm_x <= 12'h003;
    norm_y <= 12'h006;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_51 ──


    // ── cycle_52 ──
    norm_pixel <= 8'hD0;
    norm_x <= 12'h004;
    norm_y <= 12'h006;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_52 ──


    // ── cycle_53 ──
    norm_pixel <= 8'hD4;
    norm_x <= 12'h005;
    norm_y <= 12'h006;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_53 ──


    // ── cycle_54 ──
    norm_pixel <= 8'hD8;
    norm_x <= 12'h006;
    norm_y <= 12'h006;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_54 ──


    // ── cycle_55 ──
    norm_pixel <= 8'hDC;
    norm_x <= 12'h007;
    norm_y <= 12'h006;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b1;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_55 ──


    // ── cycle_56 ──
    norm_pixel <= 8'hE0;
    norm_x <= 12'h000;
    norm_y <= 12'h007;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_56 ──


    // ── cycle_57 ──
    norm_pixel <= 8'hE4;
    norm_x <= 12'h001;
    norm_y <= 12'h007;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_57 ──


    // ── cycle_58 ──
    norm_pixel <= 8'hE8;
    norm_x <= 12'h002;
    norm_y <= 12'h007;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_58 ──


    // ── cycle_59 ──
    norm_pixel <= 8'hEC;
    norm_x <= 12'h003;
    norm_y <= 12'h007;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_59 ──


    // ── cycle_60 ──
    norm_pixel <= 8'hF0;
    norm_x <= 12'h004;
    norm_y <= 12'h007;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_60 ──


    // ── cycle_61 ──
    norm_pixel <= 8'hF4;
    norm_x <= 12'h005;
    norm_y <= 12'h007;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_61 ──


    // ── cycle_62 ──
    norm_pixel <= 8'hF8;
    norm_x <= 12'h006;
    norm_y <= 12'h007;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b0;
    norm_end_of_frame <= 1'b0;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_62 ──


    // ── cycle_63 ──
    norm_pixel <= 8'hFC;
    norm_x <= 12'h007;
    norm_y <= 12'h007;
    norm_frame_id <= 16'h0000;
    norm_tile_id <= 16'h0000;
    norm_end_of_line <= 1'b1;
    norm_end_of_frame <= 1'b1;
    norm_pixel_valid <= 1'b1;
    @(posedge ap_clk);
    // ── end: cycle_63 ──


    // ── cycle_64 ──
    norm_pixel_valid <= 1'b0;
    @(posedge ap_clk);
    // ── end: cycle_64 ──


    // ── cycle_65 ──
    norm_pixel_valid <= 1'b0;
    @(posedge ap_clk);
    // ── end: cycle_65 ──


    // ── cycle_66 ──
    norm_pixel_valid <= 1'b0;
    @(posedge ap_clk);
    // ── end: cycle_66 ──


    // ── cycle_67 ──
    norm_pixel_valid <= 1'b0;
    @(posedge ap_clk);
    // ── end: cycle_67 ──


    // ── cycle_68 ──
    norm_pixel_valid <= 1'b0;
    @(posedge ap_clk);
    $display("FORGE_CHECK|check_id=63:tile_minimum_check|label=tile_minimum_check|signal=tjoin_out_minimum|expected=0x00|observed=0x%h|width=8|passed=%0d", tjoin_out_minimum, (tjoin_out_minimum === 8'h00));
    if (tjoin_out_minimum !== 8'h00) begin
      $display("FAIL: tile_minimum_check — expected 8'h00, got %0h", tjoin_out_minimum);
      $fatal(1, "Check failed: tile_minimum_check");
    end
    $display("FORGE_CHECK|check_id=63:tile_maximum_check|label=tile_maximum_check|signal=tjoin_out_maximum|expected=0xff|observed=0x%h|width=8|passed=%0d", tjoin_out_maximum, (tjoin_out_maximum === 8'hFF));
    if (tjoin_out_maximum !== 8'hFF) begin
      $display("FAIL: tile_maximum_check — expected 8'hFF, got %0h", tjoin_out_maximum);
      $fatal(1, "Check failed: tile_maximum_check");
    end
    $display("FORGE_CHECK|check_id=63:tile_mean_check|label=tile_mean_check|signal=tjoin_out_mean|expected=0x007d|observed=0x%h|width=16|passed=%0d", tjoin_out_mean, (tjoin_out_mean === 16'h007D));
    if (tjoin_out_mean !== 16'h007D) begin
      $display("FAIL: tile_mean_check — expected 16'h007D, got %0h", tjoin_out_mean);
      $fatal(1, "Check failed: tile_mean_check");
    end
    $display("FORGE_CHECK|check_id=63:tile_variance_check|label=tile_variance_check|signal=tjoin_out_variance|expected=0x002434|observed=0x%h|width=24|passed=%0d", tjoin_out_variance, (tjoin_out_variance === 24'h002434));
    if (tjoin_out_variance !== 24'h002434) begin
      $display("FAIL: tile_variance_check — expected 24'h002434, got %0h", tjoin_out_variance);
      $fatal(1, "Check failed: tile_variance_check");
    end
    $display("FORGE_CHECK|check_id=63:tile_id_check|label=tile_id_check|signal=tjoin_out_tile_id|expected=0x0000|observed=0x%h|width=16|passed=%0d", tjoin_out_tile_id, (tjoin_out_tile_id === 16'h0000));
    if (tjoin_out_tile_id !== 16'h0000) begin
      $display("FAIL: tile_id_check — expected 16'h0000, got %0h", tjoin_out_tile_id);
      $fatal(1, "Check failed: tile_id_check");
    end
    $display("FORGE_CHECK|check_id=63:tile_frame_id_check|label=tile_frame_id_check|signal=tjoin_out_frame_id|expected=0x0000|observed=0x%h|width=16|passed=%0d", tjoin_out_frame_id, (tjoin_out_frame_id === 16'h0000));
    if (tjoin_out_frame_id !== 16'h0000) begin
      $display("FAIL: tile_frame_id_check — expected 16'h0000, got %0h", tjoin_out_frame_id);
      $fatal(1, "Check failed: tile_frame_id_check");
    end
    $display("FORGE_CHECK|check_id=63:tile_out_valid_check|label=tile_out_valid_check|signal=tjoin_out_valid|expected=0x1|observed=0x%h|width=1|passed=%0d", tjoin_out_valid, (tjoin_out_valid === 1'b1));
    if (tjoin_out_valid !== 1'b1) begin
      $display("FAIL: tile_out_valid_check — expected 1'b1, got %0h", tjoin_out_valid);
      $fatal(1, "Check failed: tile_out_valid_check");
    end
    $display("FORGE_CHECK|check_id=63:tile_join_mismatch_check|label=tile_join_mismatch_check|signal=tjoin_join_mismatch|expected=0x0|observed=0x%h|width=1|passed=%0d", tjoin_join_mismatch, (tjoin_join_mismatch === 1'b0));
    if (tjoin_join_mismatch !== 1'b0) begin
      $display("FAIL: tile_join_mismatch_check — expected 1'b0, got %0h", tjoin_join_mismatch);
      $fatal(1, "Check failed: tile_join_mismatch_check");
    end
    // ── end: cycle_68 ──

endtask : run_stimulus
