// ============================================================
// tb_algo_top.sv — Generated by gen-sim
// Flow:         trigger_pipeline_xsim
// Top module:   algo_top
// Generated at: 2026-07-27 17:46 UTC
// DO NOT EDIT — regenerate with: gen-sim trigger_pipeline_xsim
// ============================================================
`timescale 1ns/1ps

module tb_algo_top;

  // ── Timing parameters ────────────────────────────────────
  localparam real CLK_PERIOD_NS              = 4.0;
  localparam int  RESET_CYCLES               = 4;
  localparam int  IDLE_CYCLES_AFTER_RESET    = 0;
  localparam int  POST_STIMULUS_DRAIN_CYCLES = 25;

  // ── Clock and reset ──────────────────────────────────────
  logic ap_clk;
  logic ap_rst;

  initial ap_clk = 1'b0;
  always #(CLK_PERIOD_NS / 2.0) ap_clk = ~ap_clk;

    `ifndef PROBE_LOG
    localparam int PROBE_LOG = 0;
    `else
    localparam int PROBE_LOG = `PROBE_LOG;
    `endif

  // ── DUT signals (from port_map) ───────────────────────
  wire  tout_out_valid;
  wire  [31:0] tout_trigger_word;
  logic [31:0] dec_0_raw_hit;
  logic dec_0_raw_valid;
  logic [31:0] dec_1_raw_hit;
  logic dec_1_raw_valid;
  logic [31:0] dec_2_raw_hit;
  logic dec_2_raw_valid;
  logic [31:0] dec_3_raw_hit;
  logic dec_3_raw_valid;


  // ── Stimulus ─────────────────────────────────────────────
  `include "stimulus_current.svh"

  // ── DUT instantiation ────────────────────────────────────
  algo_top dut (
    .tout_out_valid(tout_out_valid),
    .tout_trigger_word(tout_trigger_word),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .dec_0_raw_hit(dec_0_raw_hit),
    .dec_0_raw_valid(dec_0_raw_valid),
    .dec_1_raw_hit(dec_1_raw_hit),
    .dec_1_raw_valid(dec_1_raw_valid),
    .dec_2_raw_hit(dec_2_raw_hit),
    .dec_2_raw_valid(dec_2_raw_valid),
    .dec_3_raw_hit(dec_3_raw_hit),
    .dec_3_raw_valid(dec_3_raw_valid)
  );

  // ── Cycle counter ────────────────────────────────────────
  integer cycle_count;

  // ── Output trace ─────────────────────────────────────────
  integer trace_fd;
    integer probe_fd;

  // ── Main test sequence ──────────────────────────────────
  initial begin
    cycle_count = 0;
    ap_rst      = 1'b1;
    dec_0_raw_hit = '0;
    dec_0_raw_valid = '0;
    dec_1_raw_hit = '0;
    dec_1_raw_valid = '0;
    dec_2_raw_hit = '0;
    dec_2_raw_valid = '0;
    dec_3_raw_hit = '0;
    dec_3_raw_valid = '0;

    trace_fd = $fopen("algo_top_outputs.csv", "w");
    $fwrite(trace_fd, "cycle,tout_out_valid,tout_trigger_word\n");


    // Reset phase
    repeat (RESET_CYCLES) @(posedge ap_clk);
    ap_rst = 1'b0;

    // Idle settle phase
    repeat (IDLE_CYCLES_AFTER_RESET) @(posedge ap_clk);

    // Stimulus phase
    run_stimulus();  // defined in stimulus_current.svh (framework-standard handoff contract)

    // Drain phase
    repeat (POST_STIMULUS_DRAIN_CYCLES) @(posedge ap_clk);

    $fclose(trace_fd);

    $display("TB PASS: trigger_pipeline_xsim completed");
    $finish;
  end

  // ── Output logging ───────────────────────────────────────
  always @(posedge ap_clk) begin
    if (!ap_rst) begin
      $fwrite(trace_fd, "%0d,%0b,%0h\n", cycle_count, tout_out_valid, tout_trigger_word);

      cycle_count <= cycle_count + 1;
    end
  end

endmodule
