// cdc_reset_sync.v — Asynchronous-assert, synchronous-deassert reset synchronizer
//
// Standard reset-crossing primitive: assertion of the incoming
// asynchronous reset takes effect immediately (no metastability risk on
// assert — every flop simply clears), while deassertion is synchronized
// to the destination clock so every flop in the destination domain
// releases reset on the same edge. Used by topgen-generated algo_top.v
// for `reset_domains.<name>.sync: reset_sync` declarations
// (release-plan §10.0B, §5 Decision A) — a reset crossing is a property
// of a destination reset *domain*, not a `connections:`-level data
// crossing, so this primitive is emitted once per synchronized reset
// domain rather than once per connection (see
// forge.topgen.ip.cdc's module docstring for why).
//
// Parameters: none (reset is always a single bit).
//
// Usage (generated by topgen structural_verilog):
//   cdc_reset_sync inst (
//       .dst_clk(clk_b), .async_rst_in(ap_rst), .sync_rst_out(rst_b)
//   );
//
// Timing: sync_rst_out asserts combinationally/asynchronously with
// async_rst_in and deasserts synchronously, 2 dst_clk cycles after
// async_rst_in releases.
//==============================================================================

`timescale 1ns / 1ps

module cdc_reset_sync (
    input  wire dst_clk,
    input  wire async_rst_in,
    output wire sync_rst_out
);

    reg [1:0] sync_stage;

    always @(posedge dst_clk or posedge async_rst_in) begin
        if (async_rst_in) sync_stage <= 2'b11;
        else               sync_stage <= {sync_stage[0], 1'b0};
    end

    assign sync_rst_out = sync_stage[1];

endmodule
