// cdc_async_fifo.v — Dual-clock asynchronous FIFO
//
// Real generated RTL for `cdc: {kind: async_fifo, depth: N}` connections
// (release-plan §10.0B, §5 Decision A/B) — this used to be structurally
// approved but emit no RTL at all ("wired directly, no crossing
// protection applied", documented limitation). Standard Gray-code
// dual-pointer design (Cummings, "Simulation and Synthesis Techniques
// for Asynchronous FIFO Design") — write/read binary pointers, Gray-code
// conversion before crossing domains, 2FF-synchronized in the opposite
// domain, full/empty derived from Gray-code pointer comparison.
//
// Like every other connection in FORGE's structural port_map wiring
// (which has no generic valid/ready concept), both sides are
// continuously driven: this primitive writes every write-domain cycle
// and reads every read-domain cycle, relying on its own internal
// full/empty guards to avoid corrupting the buffer — it does not
// require or expose separate write-enable/read-enable ports. It
// therefore provides real dual-clock buffering and synchronization, but
// not true producer/consumer backpressure — `overflow_attempt`/
// `underflow_attempt` are exposed for release-plan §5 Decision B /
// slice 10.0C to report on.
//
// `occupancy`/`high_water` (added slice 10.0C): real instrumentation
// signals, computed in the WRITE domain only — the synchronized read
// pointer (`rd_gray_sync1`, already 2FF-safe for comparison) is
// converted back to binary so it can be subtracted from the live write
// pointer. An async FIFO's occupancy is only ever exactly accurate in
// the domain that computes it (the other domain's pointer is always at
// least one synchronizer-latency stale) — a standard, honestly stated
// limitation, not new to this design. `high_water` is a running
// maximum of `occupancy`, cleared on `wr_rst`.
//
// Parameters:
//   WIDTH - Bit width of each entry (default: 8)
//   DEPTH - Number of entries; MUST be a power of two (Gray-code pointer
//           comparison requires it — enforced at design.yml load time,
//           see forge.topgen.config's cdc.depth validation)
//
// Usage (generated by topgen structural_verilog):
//   cdc_async_fifo #(.WIDTH(8), .DEPTH(16)) inst (
//       .wr_clk(clk_a), .wr_rst(rst_a), .din(net_src_dout),
//       .full(), .overflow_attempt(), .occupancy(), .high_water(),
//       .rd_clk(clk_b), .rd_rst(rst_b), .dout(sync_net_src_dst_dout),
//       .empty(), .underflow_attempt()
//   );
//
// Timing: fill/drain latency is data-dependent (depends on relative
// write/read rates and clock phase) and is not statically bounded —
// forge.analyze.latency_static.graph treats async_fifo edges as unknown
// (None), same as before this slice.
//==============================================================================

`timescale 1ns / 1ps

module cdc_async_fifo #(
    parameter WIDTH = 8,
    parameter DEPTH = 16
)(
    input  wire             wr_clk,
    input  wire             wr_rst,
    input  wire [WIDTH-1:0] din,
    output wire             full,
    output wire             overflow_attempt,
    output wire [$clog2(DEPTH):0] occupancy,
    output wire [$clog2(DEPTH):0] high_water,

    input  wire             rd_clk,
    input  wire             rd_rst,
    output wire [WIDTH-1:0] dout,
    output wire             empty,
    output wire             underflow_attempt
);

    localparam ADDR_WIDTH = $clog2(DEPTH);

    // Combinational Gray-to-binary conversion (MSB unchanged, each lower
    // bit is the XOR of itself and the already-converted bit above it).
    function [ADDR_WIDTH:0] gray2bin;
        input [ADDR_WIDTH:0] gray;
        integer i;
        begin
            gray2bin[ADDR_WIDTH] = gray[ADDR_WIDTH];
            for (i = ADDR_WIDTH - 1; i >= 0; i = i - 1)
                gray2bin[i] = gray2bin[i + 1] ^ gray[i];
        end
    endfunction

    reg [WIDTH-1:0] mem [0:DEPTH-1];

    // All registers declared up front, before either always block, so
    // neither domain's block ever references the other's register
    // before its declaration (xvlog enforces declare-before-use strictly
    // even though it's simulation-only cross-referencing, not a real
    // ordering dependency).
    reg  [ADDR_WIDTH:0] wr_bin, wr_gray;
    reg  [ADDR_WIDTH:0] rd_gray_sync0, rd_gray_sync1;
    reg  full_r;
    reg  [ADDR_WIDTH:0] high_water_r;
    reg  [ADDR_WIDTH:0] rd_bin, rd_gray;
    reg  [ADDR_WIDTH:0] wr_gray_sync0, wr_gray_sync1;
    reg  empty_r;

    // ── Write domain ────────────────────────────────────────────────
    wire [ADDR_WIDTH:0] wr_bin_next  = wr_bin + (!full);
    wire [ADDR_WIDTH:0] wr_gray_next = (wr_bin_next >> 1) ^ wr_bin_next;

    assign full             = full_r;
    assign overflow_attempt = full;
    assign occupancy        = wr_bin - gray2bin(rd_gray_sync1);
    assign high_water        = high_water_r;

    always @(posedge wr_clk) begin
        if (wr_rst) begin
            wr_bin        <= {(ADDR_WIDTH+1){1'b0}};
            wr_gray       <= {(ADDR_WIDTH+1){1'b0}};
            rd_gray_sync0 <= {(ADDR_WIDTH+1){1'b0}};
            rd_gray_sync1 <= {(ADDR_WIDTH+1){1'b0}};
            full_r        <= 1'b0;
            high_water_r  <= {(ADDR_WIDTH+1){1'b0}};
        end else begin
            wr_bin        <= wr_bin_next;
            wr_gray       <= wr_gray_next;
            rd_gray_sync0 <= rd_gray;
            rd_gray_sync1 <= rd_gray_sync0;
            full_r        <= (wr_gray_next ==
                {~rd_gray_sync1[ADDR_WIDTH:ADDR_WIDTH-1], rd_gray_sync1[ADDR_WIDTH-2:0]});
            if (occupancy > high_water_r) high_water_r <= occupancy;
        end
    end

    always @(posedge wr_clk) begin
        if (!full) mem[wr_bin[ADDR_WIDTH-1:0]] <= din;
    end

    // ── Read domain ─────────────────────────────────────────────────
    wire [ADDR_WIDTH:0] rd_bin_next  = rd_bin + (!empty);
    wire [ADDR_WIDTH:0] rd_gray_next = (rd_bin_next >> 1) ^ rd_bin_next;

    assign dout              = mem[rd_bin[ADDR_WIDTH-1:0]];
    assign empty             = empty_r;
    assign underflow_attempt = empty;

    always @(posedge rd_clk) begin
        if (rd_rst) begin
            rd_bin        <= {(ADDR_WIDTH+1){1'b0}};
            rd_gray       <= {(ADDR_WIDTH+1){1'b0}};
            wr_gray_sync0 <= {(ADDR_WIDTH+1){1'b0}};
            wr_gray_sync1 <= {(ADDR_WIDTH+1){1'b0}};
            empty_r       <= 1'b1;
        end else begin
            rd_bin        <= rd_bin_next;
            rd_gray       <= rd_gray_next;
            wr_gray_sync0 <= wr_gray;
            wr_gray_sync1 <= wr_gray_sync0;
            empty_r       <= (rd_gray_next == wr_gray_sync1);
        end
    end

endmodule
