// cdc_sync2ff.v — Two-flop clock-domain-crossing synchronizer
//
// Synchronizes a signal from an asynchronous (or unrelated) source domain
// into the destination clock domain using the standard double
// flip-flop pattern. Used by topgen-generated algo_top.v to implement
// `cdc: {kind: 2ff_sync}` connections (release-plan §3.2).
//
// Parameters:
//   WIDTH - Bit width of the signal to synchronize (default: 1)
//
// Usage (generated by topgen structural_verilog):
//   cdc_sync2ff #(.WIDTH(8)) cdc_sync_0 (
//       .dst_clk(clk_b),
//       .dst_rst(rst_b),
//       .din(net_src_dout),
//       .dout(sync_net_src_dst_dout)
//   );
//
// Notes:
//   Both flip-flop stages are clocked by the DESTINATION domain's clock —
//   this is what makes the crossing safe, not the source side. For a
//   multi-bit bus, this only guarantees each bit is metastability-safe
//   individually; it does NOT guarantee the bus is sampled as a coherent
//   multi-bit value (no Gray-coding/handshake is applied here). Use this
//   for single-bit control/status signals or signals whose bits are each
//   individually meaningful (e.g. one-hot). For a coherent multi-bit data
//   transfer across domains, use `cdc: {kind: async_fifo}` instead, which
//   generates a real dual-clock FIFO (cdc_async_fifo) for that purpose.
//
// Timing:
//   Reset is synchronous to dst_clk and clears both flop stages.
//==============================================================================

`timescale 1ns / 1ps

module cdc_sync2ff #(
    parameter WIDTH = 1
)(
    input  wire             dst_clk,
    input  wire             dst_rst,
    input  wire [WIDTH-1:0] din,
    output wire [WIDTH-1:0] dout
);

    reg [WIDTH-1:0] stage1;
    reg [WIDTH-1:0] stage2;

    always @(posedge dst_clk) begin
        if (dst_rst) begin
            stage1 <= {WIDTH{1'b0}};
            stage2 <= {WIDTH{1'b0}};
        end else begin
            stage1 <= din;
            stage2 <= stage1;
        end
    end

    assign dout = stage2;

endmodule
