// cdc_mailbox.v — Request/acknowledge coherent multi-bit CDC mailbox
//
// Synchronizes a coherent multi-bit payload across clock domains using a
// full request/acknowledge handshake (not just a double-flop, which only
// guarantees per-bit metastability safety, not a coherent multi-bit
// value — see cdc_sync2ff.v's own doc comment). Used by
// topgen-generated algo_top.v to implement `cdc: {kind: mailbox_transfer}`
// connections (release-plan §10.0B, §5 Decision A).
//
// Like every other connection in FORGE's structural port_map wiring
// (which has no generic valid/ready concept), the source side is
// continuously driven: this primitive captures `din` and starts a new
// transfer on every source-domain cycle it is not already busy with one
// in flight — it does not require or expose a separate valid/enable
// port. Supports exactly one outstanding transaction at a time (a new
// capture is held off internally until the previous transfer's
// acknowledge has propagated back to the source domain) — this is a
// fixed property of the primitive this release, not configurable.
//
// Parameters:
//   WIDTH - Bit width of the payload to transfer (default: 8)
//
// Usage (generated by topgen structural_verilog):
//   cdc_mailbox #(.WIDTH(8)) inst (
//       .src_clk(clk_a), .src_rst(rst_a), .din(net_src_dout),
//       .dst_clk(clk_b), .dst_rst(rst_b),
//       .dout(sync_net_src_dst_dout), .dout_valid(sync_net_src_dst_dout_valid)
//   );
//
// Timing: round-trip (request -> acknowledge) latency depends on the
// relative phase of src_clk/dst_clk and is not statically bounded across
// arbitrary clock ratios — forge.analyze.latency_static.graph treats
// mailbox_transfer edges the same honest way it already treats
// async_fifo: latency stays unknown (None), not silently mis-declared as
// fixed.
//==============================================================================

`timescale 1ns / 1ps

module cdc_mailbox #(
    parameter WIDTH = 8
)(
    input  wire             src_clk,
    input  wire             src_rst,
    input  wire [WIDTH-1:0] din,

    input  wire             dst_clk,
    input  wire             dst_rst,
    output reg  [WIDTH-1:0] dout,
    output wire             dout_valid
);

    // ── Source domain ──────────────────────────────────────────────
    reg [WIDTH-1:0] data_src;
    reg             req_toggle;
    reg             ack_sync0, ack_sync1;

    wire src_busy = (req_toggle != ack_sync1);

    always @(posedge src_clk) begin
        if (src_rst) begin
            data_src   <= {WIDTH{1'b0}};
            req_toggle <= 1'b0;
        end else if (!src_busy) begin
            data_src   <= din;
            req_toggle <= ~req_toggle;
        end
    end

    always @(posedge src_clk) begin
        if (src_rst) begin
            ack_sync0 <= 1'b0;
            ack_sync1 <= 1'b0;
        end else begin
            ack_sync0 <= ack_toggle;
            ack_sync1 <= ack_sync0;
        end
    end

    // ── Destination domain ─────────────────────────────────────────
    reg req_sync0, req_sync1, req_sync1_d;
    reg ack_toggle;

    always @(posedge dst_clk) begin
        if (dst_rst) begin
            req_sync0   <= 1'b0;
            req_sync1   <= 1'b0;
            req_sync1_d <= 1'b0;
        end else begin
            req_sync0   <= req_toggle;
            req_sync1   <= req_sync0;
            req_sync1_d <= req_sync1;
        end
    end

    // dout_valid pulses for exactly one dst_clk cycle once the
    // synchronized request toggle has settled — by this point data_src
    // has been stable in the source domain since before req_toggle
    // changed, so latching it here is safe (the standard toggle-handshake
    // CDC data-transfer guarantee).
    assign dout_valid = req_sync1 ^ req_sync1_d;

    always @(posedge dst_clk) begin
        if (dst_rst) begin
            dout       <= {WIDTH{1'b0}};
            ack_toggle <= 1'b0;
        end else if (dout_valid) begin
            dout       <= data_src;
            ack_toggle <= req_sync1;
        end
    end

endmodule
