// cdc_pulse_sync.v — Toggle-based single-event pulse synchronizer
//
// Synchronizes a one-cycle pulse in the SOURCE clock domain into a
// one-cycle pulse in the DESTINATION clock domain, using the standard
// toggle-flop + double-flop-synchronize + edge-detect pattern. Used by
// topgen-generated algo_top.v to implement `cdc: {kind: pulse_sync,
// min_spacing_cycles: N}` connections (release-plan §10.0B, §5 Decision A).
//
// Correctness depends on the connection's declared `min_spacing_cycles`:
// the source domain must not assert `pulse_in` again until the previous
// pulse has had time to fully cross (at minimum, 3 destination-domain
// clock cycles after the source toggle changes) — topgen does not itself
// enforce this at runtime; it is a contract the connected producer must
// honor, exactly like `min_spacing_cycles` documents.
//
// Parameters: none (single-bit event signal; no WIDTH — a "pulse" is a
// single-cycle event, not a data bus. For synchronizing a coherent
// multi-bit payload alongside an event, use `cdc: {kind: mailbox_transfer}`
// instead.)
//
// Usage (generated by topgen structural_verilog):
//   cdc_pulse_sync inst (
//       .src_clk(clk_a), .src_rst(rst_a), .pulse_in(net_src_dout),
//       .dst_clk(clk_b), .dst_rst(rst_b), .pulse_out(sync_net_src_dst_dout)
//   );
//
// Timing: destination-domain latency is fixed at 3 cycles (2 toggle-sync
// stages + 1 edge-detect stage) — see
// forge.analyze.latency_static.graph._edge_latency_from_connection.
//==============================================================================

`timescale 1ns / 1ps

module cdc_pulse_sync (
    input  wire src_clk,
    input  wire src_rst,
    input  wire pulse_in,

    input  wire dst_clk,
    input  wire dst_rst,
    output wire pulse_out
);

    // Source domain: toggle on every accepted pulse.
    reg toggle_src;
    always @(posedge src_clk) begin
        if (src_rst) toggle_src <= 1'b0;
        else if (pulse_in) toggle_src <= ~toggle_src;
    end

    // Destination domain: 2FF-synchronize the toggle, then edge-detect
    // to regenerate a single dst_clk-cycle pulse.
    reg [1:0] toggle_sync;
    reg       toggle_sync_d;

    always @(posedge dst_clk) begin
        if (dst_rst) begin
            toggle_sync   <= 2'b00;
            toggle_sync_d <= 1'b0;
        end else begin
            toggle_sync   <= {toggle_sync[0], toggle_src};
            toggle_sync_d <= toggle_sync[1];
        end
    end

    assign pulse_out = toggle_sync[1] ^ toggle_sync_d;

endmodule
