// cdc_async_fifo.v — Dual-clock asynchronous FIFO
//
// Real generated RTL for `cdc: {kind: async_fifo, depth: N}` connections
// — this used to be structurally
// approved but emit no RTL at all ("wired directly, no crossing
// protection applied", documented limitation). Standard Gray-code
// dual-pointer design (Cummings, "Simulation and Synthesis Techniques
// for Asynchronous FIFO Design") — write/read binary pointers, Gray-code
// conversion before crossing domains, 2FF-synchronized in the opposite
// domain, full/empty derived from Gray-code pointer comparison.
//
// Like every other connection in FORGE's structural port_map wiring
// (which has no generic valid/ready concept), both sides are
// continuously driven: this primitive writes every write-domain cycle
// and reads every read-domain cycle, relying on its own internal
// full/empty guards to avoid corrupting the buffer — it does not
// require or expose separate write-enable/read-enable ports. It
// therefore provides real dual-clock buffering and synchronization, but
// not true producer/consumer backpressure — `overflow_attempt`/
// `underflow_attempt` are exposed for real backpressure/occupancy
// reporting to consume.
//
// `occupancy`/`high_water`: real instrumentation
// signals, computed in the WRITE domain only — the synchronized read
// pointer (`rd_gray_sync1`, already 2FF-safe for comparison) is
// converted back to binary so it can be subtracted from the live write
// pointer. An async FIFO's occupancy is only ever exactly accurate in
// the domain that computes it (the other domain's pointer is always at
// least one synchronizer-latency stale) — a standard, honestly stated
// limitation, not new to this design. `high_water` is a running
// maximum of `occupancy`, cleared on `wr_rst`.
//
// `wr_en`: an explicit,
// real write-enable, tied to `1'b1` by every prior usage in this repo
// (`forge.topgen.generators.structural_verilog` defaults it there when
// a connection's `cdc:` doesn't declare `write_enable_pin` — see that
// generator's own comment), preserving this primitive's original
// "continuously driven" behavior unchanged for every existing design.
// Found empirically wiring a real, non-constant record producer for the
// first time (the packetizer design): without a real
// write-enable, this primitive writes a fresh entry every write-domain
// cycle regardless of whether `din` actually changed, so a source that
// only updates `din` occasionally (gated by its own upstream `in_valid`,
// not every cycle) still floods the FIFO with duplicate entries whenever
// the write clock is faster than the read clock — occupancy/high-water/
// overflow telemetry then reflects how fast the write clock runs, not
// how many real records were produced, defeating the whole point of
// this primitive's real backpressure/occupancy reporting. A real per-record
// write-enable (the source module's own `in_valid`, or equivalent) fixes
// this at the source, without changing what "continuously driven" means
// for a level-style status value that has no such concept.
//
// Parameters:
//   WIDTH - Bit width of each entry (default: 8)
//   DEPTH - Number of entries; MUST be a power of two (Gray-code pointer
//           comparison requires it — enforced at design.yml load time,
//           see forge.topgen.config's cdc.depth validation)
//
// Usage (generated by topgen structural_verilog):
//   cdc_async_fifo #(.WIDTH(8), .DEPTH(16)) inst (
//       .wr_clk(clk_a), .wr_rst(rst_a), .din(net_src_dout), .wr_en(1'b1),
//       .full(), .overflow_attempt(), .occupancy(), .high_water(),
//       .rd_clk(clk_b), .rd_rst(rst_b), .dout(sync_net_src_dst_dout),
//       .empty(), .underflow_attempt()
//   );
//
// Timing: fill/drain latency is data-dependent (depends on relative
// write/read rates and clock phase) and is not statically bounded —
// forge.analysis.latency_static.graph treats async_fifo edges as unknown
// (None).
//==============================================================================

`timescale 1ns / 1ps

module cdc_async_fifo #(
    parameter WIDTH = 8,
    parameter DEPTH = 16
)(
    input  wire             wr_clk,
    input  wire             wr_rst,
    input  wire [WIDTH-1:0] din,
    input  wire             wr_en,
    output wire             full,
    output wire             overflow_attempt,
    output wire [$clog2(DEPTH):0] occupancy,
    output wire [$clog2(DEPTH):0] high_water,

    input  wire             rd_clk,
    input  wire             rd_rst,
    output wire [WIDTH-1:0] dout,
    output wire             empty,
    output wire             underflow_attempt
);

    localparam ADDR_WIDTH = $clog2(DEPTH);

    // Combinational Gray-to-binary conversion (MSB unchanged, each lower
    // bit is the XOR of itself and the already-converted bit above it).
    function [ADDR_WIDTH:0] gray2bin;
        input [ADDR_WIDTH:0] gray;
        integer i;
        begin
            gray2bin[ADDR_WIDTH] = gray[ADDR_WIDTH];
            for (i = ADDR_WIDTH - 1; i >= 0; i = i - 1)
                gray2bin[i] = gray2bin[i + 1] ^ gray[i];
        end
    endfunction

    reg [WIDTH-1:0] mem [0:DEPTH-1];

    // All registers declared up front, before either always block, so
    // neither domain's block ever references the other's register
    // before its declaration (xvlog enforces declare-before-use strictly
    // even though it's simulation-only cross-referencing, not a real
    // ordering dependency).
    reg  [ADDR_WIDTH:0] wr_bin, wr_gray;
    reg  [ADDR_WIDTH:0] rd_gray_sync0, rd_gray_sync1;
    reg  full_r;
    reg  [ADDR_WIDTH:0] high_water_r;
    reg  [ADDR_WIDTH:0] rd_bin, rd_gray;
    reg  [ADDR_WIDTH:0] wr_gray_sync0, wr_gray_sync1;
    reg  empty_r;

    // ── Write domain ────────────────────────────────────────────────
    // `wr_en`: a real write only happens when the source
    // actually asserts it, not unconditionally every cycle -- see this
    // file's header for why. `do_write` is the single gate the write
    // pointer, the memory write, and `overflow_attempt` all share.
    // Case-equality against a literal 1 (not a plain logical AND) is
    // deliberate: found empirically that a real HLS-generated upstream
    // signal (tile_stats_hls, reused unmodified from elsewhere in this design)
    // can read as X on cycles it never actually issues on -- harmless
    // for every check that ever compared it against a clean-0 operand
    // (X && 0 correctly resolves to 0 under 4-state AND), but this
    // module's own `wr_bin <= wr_bin + do_write` has no such X-masking
    // property: any X reaching it permanently poisons the write pointer
    // for the rest of simulation, once latched. Simulation-only
    // robustness, not a functional gate change -- `wr_en` is never
    // actually X on real hardware.
    wire do_write = (wr_en === 1'b1) && !full;
    wire [ADDR_WIDTH:0] wr_bin_next  = wr_bin + do_write;
    wire [ADDR_WIDTH:0] wr_gray_next = (wr_bin_next >> 1) ^ wr_bin_next;

    assign full             = full_r;
    assign overflow_attempt = full && wr_en;
    assign occupancy        = wr_bin - gray2bin(rd_gray_sync1);
    assign high_water        = high_water_r;

    always @(posedge wr_clk) begin
        if (wr_rst) begin
            wr_bin        <= {(ADDR_WIDTH+1){1'b0}};
            wr_gray       <= {(ADDR_WIDTH+1){1'b0}};
            rd_gray_sync0 <= {(ADDR_WIDTH+1){1'b0}};
            rd_gray_sync1 <= {(ADDR_WIDTH+1){1'b0}};
            full_r        <= 1'b0;
            high_water_r  <= {(ADDR_WIDTH+1){1'b0}};
        end else begin
            wr_bin        <= wr_bin_next;
            wr_gray       <= wr_gray_next;
            rd_gray_sync0 <= rd_gray;
            rd_gray_sync1 <= rd_gray_sync0;
            full_r        <= (wr_gray_next ==
                {~rd_gray_sync1[ADDR_WIDTH:ADDR_WIDTH-1], rd_gray_sync1[ADDR_WIDTH-2:0]});
            if (occupancy > high_water_r) high_water_r <= occupancy;
        end
    end

    always @(posedge wr_clk) begin
        if (do_write) mem[wr_bin[ADDR_WIDTH-1:0]] <= din;
    end

    // ── Read domain ─────────────────────────────────────────────────
    wire [ADDR_WIDTH:0] rd_bin_next  = rd_bin + (!empty);
    wire [ADDR_WIDTH:0] rd_gray_next = (rd_bin_next >> 1) ^ rd_bin_next;

    // `dout` is registered, gated by `!empty` -- a plain
    // combinational `mem[rd_bin]` read (this primitive's original form)
    // lets a destination that samples `dout` unconditionally (no `empty`
    // routed to it -- see cdc_async_fifo's own header on why FORGE's
    // structural wiring doesn't expose one) observe an in-flight write's
    // value *before* the Gray-code-synchronized `empty` flag confirms
    // it's real: `mem[]` itself isn't part of the CDC synchronization
    // path, only the pointer comparison is, so a combinational read can
    // glitch ahead of it. Found empirically wiring the packetizer design: a
    // destination-side toggle-in-payload novelty
    // detector (packetizer_rtl.v) silently "caught up" to record 0's
    // toggle bit one or more cycles before `empty` ever deasserted,
    // permanently losing that one transition -- every later record then
    // observed one entry ahead of what its own novelty detector expected,
    // a clean, deterministic off-by-one, not sporadic corruption.
    // Registering the read output so it only ever captures `mem[rd_bin]`
    // on a cycle this read domain itself already knows is real (`!empty`)
    // closes that window entirely, at the cost of one extra registered
    // cycle before a freshly-dequeued value is visible -- consistent with
    // this primitive's own "fill/drain latency is data-dependent... not
    // statically bounded" framing already below.
    reg [WIDTH-1:0] dout_r;
    assign dout              = dout_r;
    assign empty             = empty_r;
    assign underflow_attempt = empty;

    always @(posedge rd_clk) begin
        if (rd_rst) begin
            rd_bin        <= {(ADDR_WIDTH+1){1'b0}};
            rd_gray       <= {(ADDR_WIDTH+1){1'b0}};
            wr_gray_sync0 <= {(ADDR_WIDTH+1){1'b0}};
            wr_gray_sync1 <= {(ADDR_WIDTH+1){1'b0}};
            empty_r       <= 1'b1;
            dout_r        <= {WIDTH{1'b0}};
        end else begin
            if (!empty) dout_r <= mem[rd_bin[ADDR_WIDTH-1:0]];
            rd_bin        <= rd_bin_next;
            rd_gray       <= rd_gray_next;
            wr_gray_sync0 <= wr_gray;
            wr_gray_sync1 <= wr_gray_sync0;
            empty_r       <= (rd_gray_next == wr_gray_sync1);
        end
    end

endmodule
