// ============================================================
// tb_hit_collector_xsim.sv — Generated by gen-sim
// Flow:         hit_collector_xsim
// Top module:   hit_collector
// Generated at: 2026-04-28 16:07 UTC
// DO NOT EDIT — regenerate with: gen-sim hit_collector_xsim
// ============================================================
`timescale 1ns/1ps

module tb_hit_collector_xsim;

  // ── Timing parameters ────────────────────────────────────
  localparam real CLK_PERIOD_NS              = 4.0;
  localparam int  RESET_CYCLES               = 4;
  localparam int  IDLE_CYCLES_AFTER_RESET    = 0;
  localparam int  POST_STIMULUS_DRAIN_CYCLES = 4;

  // ── Clock and reset ──────────────────────────────────────
  logic ap_clk;
  logic ap_rst;

  initial ap_clk = 1'b0;
  always #(CLK_PERIOD_NS / 2.0) ap_clk = ~ap_clk;

    `ifndef PROBE_LOG
    localparam int PROBE_LOG = 0;
    `else
    localparam int PROBE_LOG = `PROBE_LOG;
    `endif

  // ── DUT signals (from port_map) ───────────────────────
  logic [31:0] in_hit_0;
  logic in_valid_0;
  logic [31:0] in_hit_1;
  logic in_valid_1;
  logic [31:0] in_hit_2;
  logic in_valid_2;
  logic [31:0] in_hit_3;
  logic in_valid_3;
  wire  [2:0] n_hits;
  wire  [15:0] phi_sum;
  wire  collector_valid;


  // ── Stimulus ─────────────────────────────────────────────
  `include "stimulus_current.svh"

  // ── DUT instantiation ────────────────────────────────────
  hit_collector dut (
    .in_hit_0(in_hit_0),
    .in_valid_0(in_valid_0),
    .in_hit_1(in_hit_1),
    .in_valid_1(in_valid_1),
    .in_hit_2(in_hit_2),
    .in_valid_2(in_valid_2),
    .in_hit_3(in_hit_3),
    .in_valid_3(in_valid_3),
    .n_hits(n_hits),
    .phi_sum(phi_sum),
    .collector_valid(collector_valid),
    .ap_rst(ap_rst)
  );

  // ── Cycle counter ────────────────────────────────────────
  integer cycle_count;

  // ── Output trace ─────────────────────────────────────────
  integer trace_fd;
    integer probe_fd;

  // ── Main test sequence ──────────────────────────────────
  initial begin
    cycle_count = 0;
    ap_rst      = 1'b1;
    in_hit_0 = '0;
    in_valid_0 = '0;
    in_hit_1 = '0;
    in_valid_1 = '0;
    in_hit_2 = '0;
    in_valid_2 = '0;
    in_hit_3 = '0;
    in_valid_3 = '0;

    trace_fd = $fopen("hit_collector_outputs.csv", "w");
    $fwrite(trace_fd, "cycle,n_hits,phi_sum,collector_valid\n");


    // Reset phase
    repeat (RESET_CYCLES) @(posedge ap_clk);
    ap_rst = 1'b0;

    // Idle settle phase
    repeat (IDLE_CYCLES_AFTER_RESET) @(posedge ap_clk);

    // Stimulus phase
    run_stimulus();  // defined in stimulus_current.svh (framework-standard handoff contract)

    // Drain phase
    repeat (POST_STIMULUS_DRAIN_CYCLES) @(posedge ap_clk);

    $fclose(trace_fd);

    $display("TB PASS: hit_collector_xsim completed");
    $finish;
  end

  // ── Output logging ───────────────────────────────────────
  always @(posedge ap_clk) begin
    if (!ap_rst) begin
      $fwrite(trace_fd, "%0d,%0d,%0h,%0b\n", cycle_count, n_hits, phi_sum, collector_valid);

      cycle_count <= cycle_count + 1;
    end
  end

endmodule
