// ============================================================
// tb_algo_top.sv — Generated by gen-sim
// Flow:         full_functional_xsim
// Top module:   algo_top
// Generated at: 2026-08-05 00:23 UTC
// DO NOT EDIT — regenerate with: gen-sim full_functional_xsim
// ============================================================
`timescale 1ns/1ps

module tb_algo_top;

  // ── Timing parameters ────────────────────────────────────
  localparam real CLK_PERIOD_NS              = 5.0;
  localparam int  RESET_CYCLES               = 4;
  localparam int  IDLE_CYCLES_AFTER_RESET    = 0;
  localparam int  POST_STIMULUS_DRAIN_CYCLES = 40;

  // ── Clock and reset ──────────────────────────────────────
  logic ap_clk;
  logic ap_rst;

  initial ap_clk = 1'b0;
  always #(CLK_PERIOD_NS / 2.0) ap_clk = ~ap_clk;

  // ── Additional clock domains (release-plan Phase 10, slice 10.4) ──
  logic clk_output;
  initial clk_output = 1'b0;
  always #(8.0 / 2.0) clk_output = ~clk_output;


    `ifndef PROBE_LOG
    localparam int PROBE_LOG = 0;
    `else
    localparam int PROBE_LOG = `PROBE_LOG;
    `endif

  // ── DUT signals (from port_map) ───────────────────────
  wire  [255:0] pktz_packet_data;
  wire  [31:0] pktz_packet_keep;
  wire  pktz_packet_last;
  wire  pktz_packet_valid;
  logic norm_end_of_frame;
  logic norm_end_of_line;
  logic [15:0] norm_frame_id;
  logic [7:0] norm_pixel;
  logic norm_pixel_valid;
  logic [15:0] norm_tile_id;
  logic [11:0] norm_x;
  logic [11:0] norm_y;
  logic rst_output;


  // ── Stimulus ─────────────────────────────────────────────
  `include "stimulus_current.svh"

  // ── DUT instantiation ────────────────────────────────────
  algo_top dut (
    .pktz_packet_data(pktz_packet_data),
    .pktz_packet_keep(pktz_packet_keep),
    .pktz_packet_last(pktz_packet_last),
    .pktz_packet_valid(pktz_packet_valid),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .clk_output(clk_output),
    .norm_end_of_frame(norm_end_of_frame),
    .norm_end_of_line(norm_end_of_line),
    .norm_frame_id(norm_frame_id),
    .norm_pixel(norm_pixel),
    .norm_pixel_valid(norm_pixel_valid),
    .norm_tile_id(norm_tile_id),
    .norm_x(norm_x),
    .norm_y(norm_y),
    .rst_output(rst_output)
  );

  // ── Cycle counter ────────────────────────────────────────
  integer cycle_count;

  // ── Output trace ─────────────────────────────────────────
  integer trace_fd;
    integer probe_fd;

  // ── Main test sequence ──────────────────────────────────
  initial begin
    cycle_count = 0;
    ap_rst      = 1'b1;
    norm_end_of_frame = '0;
    norm_end_of_line = '0;
    norm_frame_id = '0;
    norm_pixel = '0;
    norm_pixel_valid = '0;
    norm_tile_id = '0;
    norm_x = '0;
    norm_y = '0;
    rst_output = '0;

    trace_fd = $fopen("algo_top_outputs.csv", "w");
    $fwrite(trace_fd, "cycle,pktz_packet_data,pktz_packet_keep,pktz_packet_last,pktz_packet_valid\n");
    if (PROBE_LOG) begin
      probe_fd = $fopen("algo_top_probe.csv", "w");
      if (probe_fd == 0) $fatal(1, "Failed to open algo_top_probe.csv");
      $fwrite(probe_fd, "cycle,pr_full,pr_empty,pr_overflow,pr_underflow,pr_occupancy,pr_high_water,ts_full,ts_empty,ts_overflow,ts_underflow,ts_occupancy,ts_high_water\n");
    end

    // Reset phase
    repeat (RESET_CYCLES) @(posedge ap_clk);
    ap_rst = 1'b0;

    // Idle settle phase
    repeat (IDLE_CYCLES_AFTER_RESET) @(posedge ap_clk);

    // Stimulus phase
    run_stimulus();  // defined in stimulus_current.svh (framework-standard handoff contract)

    // Drain phase
    repeat (POST_STIMULUS_DRAIN_CYCLES) @(posedge ap_clk);

    $fclose(trace_fd);
    if (PROBE_LOG) $fclose(probe_fd);
    $display("TB PASS: full_functional_xsim completed");
    $finish;
  end

  // ── Output logging ───────────────────────────────────────
  always @(posedge ap_clk) begin
    if (!ap_rst) begin
      $fwrite(trace_fd, "%0d,%0h,%0h,%0b,%0b\n", cycle_count, pktz_packet_data, pktz_packet_keep, pktz_packet_last, pktz_packet_valid);
      if (PROBE_LOG) begin
        $fwrite(probe_fd, "%0d,%0b,%0b,%0b,%0b,%0h,%0h,%0b,%0b,%0b,%0b,%0h,%0h\n", cycle_count, dut.sync_net_prpack_pktz_out_record_full, dut.sync_net_prpack_pktz_out_record_empty, dut.sync_net_prpack_pktz_out_record_overflow, dut.sync_net_prpack_pktz_out_record_underflow, dut.sync_net_prpack_pktz_out_record_occupancy, dut.sync_net_prpack_pktz_out_record_high_water, dut.sync_net_tspack_pktz_out_record_full, dut.sync_net_tspack_pktz_out_record_empty, dut.sync_net_tspack_pktz_out_record_overflow, dut.sync_net_tspack_pktz_out_record_underflow, dut.sync_net_tspack_pktz_out_record_occupancy, dut.sync_net_tspack_pktz_out_record_high_water);
      end
      cycle_count <= cycle_count + 1;
    end
  end

endmodule
