// stimulus_current.svh — generated for trigger_logic_xsim
// Generated by gen_stimulus.py — DO NOT EDIT
// Source: trigger_demo_golden.xml
//
// Defines task run_stimulus() — called from the TB initial block
// after reset/idle phases.  Uses $fatal(1,...) on any assertion failure.

task automatic run_stimulus();
  integer _fail;
  _fail = 0;

  // Event 0: n_hits=3 → accept=1 quality=3
  @(posedge ap_clk);
  n_hits   = 3'd3;
  phi_sum  = 16'h0213;
  in_valid = 1'b1;
  #1;  // combinational settle
  if (trigger_accept !== 1'b1) begin $display("FAIL [E0] trigger_accept=%0b expect=1", trigger_accept); _fail = 1; end
  if (trigger_quality !== 8'd3) begin $display("FAIL [E0] trigger_quality=%0d expect=3", trigger_quality); _fail = 1; end
  if (trigger_valid !== 1'b1) begin $display("FAIL [E0] trigger_valid=%0b expect=1", trigger_valid); _fail = 1; end

  // Event 1: n_hits=1 → accept=0 quality=1
  @(posedge ap_clk);
  n_hits   = 3'd1;
  phi_sum  = 16'h00D1;
  in_valid = 1'b1;
  #1;  // combinational settle
  if (trigger_accept !== 1'b0) begin $display("FAIL [E1] trigger_accept=%0b expect=0", trigger_accept); _fail = 1; end
  if (trigger_quality !== 8'd1) begin $display("FAIL [E1] trigger_quality=%0d expect=1", trigger_quality); _fail = 1; end
  if (trigger_valid !== 1'b1) begin $display("FAIL [E1] trigger_valid=%0b expect=1", trigger_valid); _fail = 1; end

  // Event 2: n_hits=4 → accept=1 quality=4
  @(posedge ap_clk);
  n_hits   = 3'd4;
  phi_sum  = 16'h0A04;
  in_valid = 1'b1;
  #1;  // combinational settle
  if (trigger_accept !== 1'b1) begin $display("FAIL [E2] trigger_accept=%0b expect=1", trigger_accept); _fail = 1; end
  if (trigger_quality !== 8'd4) begin $display("FAIL [E2] trigger_quality=%0d expect=4", trigger_quality); _fail = 1; end
  if (trigger_valid !== 1'b1) begin $display("FAIL [E2] trigger_valid=%0b expect=1", trigger_valid); _fail = 1; end

  // Event 3: n_hits=0 → accept=0 quality=0
  @(posedge ap_clk);
  n_hits   = 3'd0;
  phi_sum  = 16'h0000;
  in_valid = 1'b0;
  #1;  // combinational settle
  if (trigger_accept !== 1'b0) begin $display("FAIL [E3] trigger_accept=%0b expect=0", trigger_accept); _fail = 1; end
  if (trigger_quality !== 8'd0) begin $display("FAIL [E3] trigger_quality=%0d expect=0", trigger_quality); _fail = 1; end
  if (trigger_valid !== 1'b0) begin $display("FAIL [E3] trigger_valid=%0b expect=0", trigger_valid); _fail = 1; end

  if (_fail) $fatal(1, "TB FAIL: trigger_logic_xsim — %0d assertion(s) failed", _fail);
endtask
