// stimulus_current.svh — generated by plugin gen_stimulus.py
// DO NOT EDIT — regenerate by running gen_stimulus.py
//
// Framework contract:
//   * This file is `include'd into the testbench module body.
//   * Must declare exactly one task: ``task automatic run_stimulus();``
//   * The task is called once after reset + idle cycles.
//   * Signals ap_clk, ap_rst (and all DUT ports) are in scope.

// flow=passthrough_readmemh stimulus_mode=readmemh

reg [17:0] event_mem [0:1];
initial $readmemh("/data3/home/pleguina/work/omtf-integration-test/workspace/arc-framework/plugins/passthrough_demo/forge/verify/passthrough_readmemh/passthrough_events.mem", event_mem);

task automatic run_stimulus();
    integer event_index;
    reg [17:0] event_word;
    reg [7:0] exp_data_out;
    reg exp_data_out_valid;

    if (!$value$plusargs("EVENT_INDEX=%d", event_index)) event_index = 0;
    event_word = event_mem[event_index];

    ap_rst <= 1'b1;
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    @(posedge ap_clk);
    ap_rst <= 1'b0;
    @(posedge ap_clk);

    pt_data_in <= event_word[17:10];
    pt_data_in_valid <= event_word[9];
    exp_data_out = event_word[8:1];
    exp_data_out_valid = event_word[0];
    @(posedge ap_clk);
    @(posedge ap_clk);

    $display("FORGE_CHECK|check_id=data_out_check|label=data_out_check|signal=pt_data_out|expected=0x%h|observed=0x%h|width=8|passed=%0d", exp_data_out, pt_data_out, (pt_data_out === exp_data_out));
    if (pt_data_out !== exp_data_out) begin
      $display("FAIL: data_out_check — expected exp_data_out, got %0h", pt_data_out);
      $fatal(1, "Check failed: data_out_check");
    end
    $display("FORGE_CHECK|check_id=data_out_valid_check|label=data_out_valid_check|signal=pt_data_out_valid|expected=0x%h|observed=0x%h|width=1|passed=%0d", exp_data_out_valid, pt_data_out_valid, (pt_data_out_valid === exp_data_out_valid));
    if (pt_data_out_valid !== exp_data_out_valid) begin
      $display("FAIL: data_out_valid_check — expected exp_data_out_valid, got %0h", pt_data_out_valid);
      $fatal(1, "Check failed: data_out_valid_check");
    end

    pt_data_in_valid <= 1'b0;
    @(posedge ap_clk);
    @(posedge ap_clk);
endtask : run_stimulus
