// ============================================================
// tb_algo_top.sv — Generated by gen-sim
// Flow:         passthrough_readmemh
// Top module:   algo_top
// Generated at: 2026-07-29 14:02 UTC
// DO NOT EDIT — regenerate with: gen-sim passthrough_readmemh
// ============================================================
`timescale 1ns/1ps

module tb_algo_top;

  // ── Timing parameters ────────────────────────────────────
  localparam real CLK_PERIOD_NS              = 4.0;
  localparam int  RESET_CYCLES               = 4;
  localparam int  IDLE_CYCLES_AFTER_RESET    = 0;
  localparam int  POST_STIMULUS_DRAIN_CYCLES = 4;

  // ── Clock and reset ──────────────────────────────────────
  logic ap_clk;
  logic ap_rst;

  initial ap_clk = 1'b0;
  always #(CLK_PERIOD_NS / 2.0) ap_clk = ~ap_clk;

    `ifndef PROBE_LOG
    localparam int PROBE_LOG = 0;
    `else
    localparam int PROBE_LOG = `PROBE_LOG;
    `endif

  // ── DUT signals (from port_map) ───────────────────────
  wire  [7:0] pt_data_out;
  wire  pt_data_out_valid;
  logic [7:0] pt_data_in;
  logic pt_data_in_valid;


  // ── Stimulus ─────────────────────────────────────────────
  `include "stimulus_current.svh"

  // ── DUT instantiation ────────────────────────────────────
  algo_top dut (
    .pt_data_out(pt_data_out),
    .pt_data_out_valid(pt_data_out_valid),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .pt_data_in(pt_data_in),
    .pt_data_in_valid(pt_data_in_valid)
  );

  // ── Cycle counter ────────────────────────────────────────
  integer cycle_count;

  // ── Output trace ─────────────────────────────────────────
  integer trace_fd;
    integer probe_fd;

  // ── Main test sequence ──────────────────────────────────
  initial begin
    cycle_count = 0;
    ap_rst      = 1'b1;
    pt_data_in = '0;
    pt_data_in_valid = '0;

    trace_fd = $fopen("algo_top_outputs.csv", "w");
    $fwrite(trace_fd, "cycle,pt_data_out,pt_data_out_valid\n");


    // Reset phase
    repeat (RESET_CYCLES) @(posedge ap_clk);
    ap_rst = 1'b0;

    // Idle settle phase
    repeat (IDLE_CYCLES_AFTER_RESET) @(posedge ap_clk);

    // Stimulus phase
    run_stimulus();  // defined in stimulus_current.svh (framework-standard handoff contract)

    // Drain phase
    repeat (POST_STIMULUS_DRAIN_CYCLES) @(posedge ap_clk);

    $fclose(trace_fd);

    $display("TB PASS: passthrough_readmemh completed");
    $finish;
  end

  // ── Output logging ───────────────────────────────────────
  always @(posedge ap_clk) begin
    if (!ap_rst) begin
      $fwrite(trace_fd, "%0d,%0h,%0b\n", cycle_count, pt_data_out, pt_data_out_valid);

      cycle_count <= cycle_count + 1;
    end
  end

endmodule
