"""forge.analysis.latency_runtime.reporter
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Render runtime latency comparison results as Markdown.
"""
from __future__ import annotations

from pathlib import Path
from typing import List, Optional

from forge.analysis.latency_runtime.comparator import LatencyComparison


_VERDICT_ICON = {
    "match":   "✅",
    "over":    "⚠",
    "under":   "⚠",
    "unknown": "❓",
}


def render_markdown(
    comparisons: List[LatencyComparison],
    out_path: Optional[Path] = None,
) -> str:
    """Render comparison table as Markdown.

    If *out_path* is given the text is also written to that file.
    Returns the rendered string in both cases.
    """
    lines: List[str] = [
        "# Runtime Latency Comparison", "",
        "| Module | HLS Predicted | Observed | Delta | Verdict |",
        "|--------|:------------:|:-------:|:-----:|---------|",
    ]

    for c in comparisons:
        pred  = str(c.hls_predicted) if c.hls_predicted is not None else "—"
        obs   = str(c.observed)      if c.observed      is not None else "—"
        if c.delta is None:
            delta = "—"
        elif c.delta > 0:
            delta = f"+{c.delta}"
        else:
            delta = str(c.delta)
        icon = _VERDICT_ICON.get(c.verdict, "")
        lines.append(
            f"| {c.module_name} | {pred} | {obs} | {delta} | {icon} {c.verdict} |"
        )

    lines += ["", "*Generated by `forge analyze runtime-latency`*", ""]
    text = "\n".join(lines)

    if out_path is not None:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(text)

    return text
