// ============================================================
// tb_algo_top.sv — Generated by gen-sim
// Flow:         platform_wrapper_xsim
// Top module:   algo_top
// Generated at: 2026-08-05 09:21 UTC
// DO NOT EDIT — regenerate with: gen-sim platform_wrapper_xsim
// ============================================================
`timescale 1ns/1ps

module tb_algo_top;

  // ── Timing parameters ────────────────────────────────────
  localparam real CLK_PERIOD_NS              = 5.0;
  localparam int  RESET_CYCLES               = 4;
  localparam int  IDLE_CYCLES_AFTER_RESET    = 0;
  localparam int  POST_STIMULUS_DRAIN_CYCLES = 40;

  // ── Clock and reset ──────────────────────────────────────
  logic ap_clk;
  logic ap_rst;

  initial ap_clk = 1'b0;
  always #(CLK_PERIOD_NS / 2.0) ap_clk = ~ap_clk;

  // ── Additional clock domains (release-plan Phase 10, slice 10.4) ──
  logic clk_control;
  initial clk_control = 1'b0;
  always #(20.0 / 2.0) clk_control = ~clk_control;
  logic clk_output;
  initial clk_output = 1'b0;
  always #(8.0 / 2.0) clk_output = ~clk_output;


    `ifndef PROBE_LOG
    localparam int PROBE_LOG = 0;
    `else
    localparam int PROBE_LOG = `PROBE_LOG;
    `endif

  // ── DUT signals (from port_map) ───────────────────────
  wire  merge_tag_mismatch;
  wire  [255:0] pktz_packet_data;
  wire  [31:0] pktz_packet_keep;
  wire  pktz_packet_last;
  wire  pktz_packet_valid;
  wire  tjoin_join_mismatch;
  wire  tjoin_out_end_of_frame;
  logic [15:0] ctrl_mailbox_frame_limit_in;
  logic [1:0] ctrl_mailbox_kernel_mode_in;
  logic [7:0] ctrl_mailbox_threshold_in;
  logic norm_end_of_frame;
  logic norm_end_of_line;
  logic [15:0] norm_frame_id;
  logic [7:0] norm_pixel;
  logic norm_pixel_valid;
  logic [15:0] norm_tile_id;
  logic [11:0] norm_x;
  logic [11:0] norm_y;
  logic rst_control;
  logic rst_output;


  // ── Stimulus ─────────────────────────────────────────────
  `include "stimulus_current.svh"

  // ── DUT instantiation ────────────────────────────────────
  algo_top dut (
    .merge_tag_mismatch(merge_tag_mismatch),
    .pktz_packet_data(pktz_packet_data),
    .pktz_packet_keep(pktz_packet_keep),
    .pktz_packet_last(pktz_packet_last),
    .pktz_packet_valid(pktz_packet_valid),
    .tjoin_join_mismatch(tjoin_join_mismatch),
    .tjoin_out_end_of_frame(tjoin_out_end_of_frame),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .clk_control(clk_control),
    .clk_output(clk_output),
    .ctrl_mailbox_frame_limit_in(ctrl_mailbox_frame_limit_in),
    .ctrl_mailbox_kernel_mode_in(ctrl_mailbox_kernel_mode_in),
    .ctrl_mailbox_threshold_in(ctrl_mailbox_threshold_in),
    .norm_end_of_frame(norm_end_of_frame),
    .norm_end_of_line(norm_end_of_line),
    .norm_frame_id(norm_frame_id),
    .norm_pixel(norm_pixel),
    .norm_pixel_valid(norm_pixel_valid),
    .norm_tile_id(norm_tile_id),
    .norm_x(norm_x),
    .norm_y(norm_y),
    .rst_control(rst_control),
    .rst_output(rst_output)
  );

  // ── Cycle counter ────────────────────────────────────────
  integer cycle_count;

  // ── Output trace ─────────────────────────────────────────
  integer trace_fd;
    integer probe_fd;

  // ── Main test sequence ──────────────────────────────────
  initial begin
    cycle_count = 0;
    ap_rst      = 1'b1;
    ctrl_mailbox_frame_limit_in = '0;
    ctrl_mailbox_kernel_mode_in = '0;
    ctrl_mailbox_threshold_in = '0;
    norm_end_of_frame = '0;
    norm_end_of_line = '0;
    norm_frame_id = '0;
    norm_pixel = '0;
    norm_pixel_valid = '0;
    norm_tile_id = '0;
    norm_x = '0;
    norm_y = '0;
    rst_control = '0;
    rst_output = '0;

    trace_fd = $fopen("algo_top_outputs.csv", "w");
    $fwrite(trace_fd, "cycle,merge_tag_mismatch,pktz_packet_data,pktz_packet_keep,pktz_packet_last,pktz_packet_valid,tjoin_join_mismatch,tjoin_out_end_of_frame\n");


    // Reset phase
    repeat (RESET_CYCLES) @(posedge ap_clk);
    ap_rst = 1'b0;

    // Idle settle phase
    repeat (IDLE_CYCLES_AFTER_RESET) @(posedge ap_clk);

    // Stimulus phase
    run_stimulus();  // defined in stimulus_current.svh (framework-standard handoff contract)

    // Drain phase
    repeat (POST_STIMULUS_DRAIN_CYCLES) @(posedge ap_clk);

    $fclose(trace_fd);

    $display("TB PASS: platform_wrapper_xsim completed");
    $finish;
  end

  // ── Output logging ───────────────────────────────────────
  always @(posedge ap_clk) begin
    if (!ap_rst) begin
      $fwrite(trace_fd, "%0d,%0b,%0h,%0h,%0b,%0b,%0b,%0b\n", cycle_count, merge_tag_mismatch, pktz_packet_data, pktz_packet_keep, pktz_packet_last, pktz_packet_valid, tjoin_join_mismatch, tjoin_out_end_of_frame);

      cycle_count <= cycle_count + 1;
    end
  end

endmodule
