// ============================================================
// tb_trigger_logic_xsim.sv — Generated by gen-sim
// Flow:         trigger_logic_xsim
// Top module:   trigger_logic
// Generated at: 2026-04-05 01:01 UTC
// DO NOT EDIT — regenerate with: gen-sim trigger_logic_xsim
// ============================================================
`timescale 1ns/1ps

module tb_trigger_logic_xsim;

  // ── Timing parameters ────────────────────────────────────
  localparam real CLK_PERIOD_NS              = 4.0;
  localparam int  RESET_CYCLES               = 4;
  localparam int  IDLE_CYCLES_AFTER_RESET    = 0;
  localparam int  POST_STIMULUS_DRAIN_CYCLES = 4;

  // ── Clock and reset ──────────────────────────────────────
  logic ap_clk;
  logic ap_rst;

  initial ap_clk = 1'b0;
  always #(CLK_PERIOD_NS / 2.0) ap_clk = ~ap_clk;

  // ── DUT signals (from port_map) ───────────────────────
  logic [2:0] n_hits;
  logic [15:0] phi_sum;
  logic in_valid;
  wire  trigger_accept;
  wire  [7:0] trigger_quality;
  wire  trigger_valid;


  // ── Stimulus ─────────────────────────────────────────────
  `include "stimulus_current.svh"

  // ── DUT instantiation ────────────────────────────────────
  trigger_logic dut (
    .n_hits(n_hits),
    .phi_sum(phi_sum),
    .in_valid(in_valid),
    .trigger_accept(trigger_accept),
    .trigger_quality(trigger_quality),
    .trigger_valid(trigger_valid),
    .ap_rst(ap_rst)
  );

  // ── Cycle counter ────────────────────────────────────────
  integer cycle_count;

  // ── Output trace ─────────────────────────────────────────
  integer trace_fd;

  // ── Main test sequence ──────────────────────────────────
  initial begin
    cycle_count = 0;
    ap_rst      = 1'b1;
    n_hits = '0;
    phi_sum = '0;
    in_valid = '0;

    trace_fd = $fopen("trigger_logic_trace.csv", "w");
    $fwrite(trace_fd, "cycle\n");

    // Reset phase
    repeat (RESET_CYCLES) @(posedge ap_clk);
    ap_rst = 1'b0;

    // Idle settle phase
    repeat (IDLE_CYCLES_AFTER_RESET) @(posedge ap_clk);

    // Stimulus phase
    run_stimulus();  // defined in stimulus_current.svh (framework-standard handoff contract)

    // Drain phase
    repeat (POST_STIMULUS_DRAIN_CYCLES) @(posedge ap_clk);

    $fclose(trace_fd);
    $display("TB PASS: trigger_logic_xsim completed");
    $finish;
  end

  // ── Output logging ───────────────────────────────────────
  always @(posedge ap_clk) begin
    if (!ap_rst) begin
      $fwrite(trace_fd, "%0d\n", cycle_count);
      cycle_count <= cycle_count + 1;
    end
  end

endmodule
