// ------------------------------------------------------------
//  Auto-generated by topgen – structural Verilog top
//  DO NOT EDIT BY HAND
// ------------------------------------------------------------

module algo_top (
  input ap_clk,
  input ap_rst,
  input [31:0] dec_0_raw_hit,
  input [31:0] dec_1_raw_hit,
  input [31:0] dec_2_raw_hit,
  input [31:0] dec_3_raw_hit,
  input dec_0_raw_valid,
  input dec_1_raw_valid,
  input dec_2_raw_valid,
  input dec_3_raw_valid,
  output [31:0] tout_trigger_word,
  output tout_out_valid
);

  // Internal wires (one per driving output pin per instance)
  wire [2:0] net_col_n_hits;
  wire [2:0] reg_net_col_trig_n_hits;
  wire [15:0] net_col_phi_sum;
  wire [15:0] reg_net_col_trig_phi_sum;
  wire net_col_collector_valid;
  wire reg_net_col_trig_collector_valid;
  wire net_trig_trigger_accept;
  wire delay_net_trig_tfan_trigger_accept;
  wire [7:0] net_trig_trigger_quality;
  wire [7:0] delay_net_trig_tfan_trigger_quality;
  wire net_trig_trigger_valid;
  wire delay_net_trig_tfan_trigger_valid;
  wire net_tfan_accept_lane_0;
  wire net_tfan_accept_lane_1;
  wire [7:0] net_tfan_quality_lane_0;
  wire [7:0] net_tfan_quality_lane_1;
  wire net_tfan_valid_lane_0;
  wire net_tfan_valid_lane_1;
  wire net_tsink_trigger_accept;
  wire [7:0] net_tsink_trigger_quality;
  wire net_tsink_trigger_valid;
  wire [31:0] net_dec_0_decoded_hit;
  wire net_dec_0_decoded_valid;
  wire [31:0] net_dec_1_decoded_hit;
  wire net_dec_1_decoded_valid;
  wire [31:0] net_dec_2_decoded_hit;
  wire net_dec_2_decoded_valid;
  wire [31:0] net_dec_3_decoded_hit;
  wire net_dec_3_decoded_valid;
  wire [31:0] net_tout_trigger_word;
  wire net_tout_out_valid;

  // dec instance 1/4
  hit_decoder dec_0 (
    .ap_rst(ap_rst),
    .raw_hit(dec_0_raw_hit),
    .raw_valid(dec_0_raw_valid),
    .decoded_hit(net_dec_0_decoded_hit),
    .decoded_valid(net_dec_0_decoded_valid)
  );

  // dec instance 2/4
  hit_decoder dec_1 (
    .ap_rst(ap_rst),
    .raw_hit(dec_1_raw_hit),
    .raw_valid(dec_1_raw_valid),
    .decoded_hit(net_dec_1_decoded_hit),
    .decoded_valid(net_dec_1_decoded_valid)
  );

  // dec instance 3/4
  hit_decoder dec_2 (
    .ap_rst(ap_rst),
    .raw_hit(dec_2_raw_hit),
    .raw_valid(dec_2_raw_valid),
    .decoded_hit(net_dec_2_decoded_hit),
    .decoded_valid(net_dec_2_decoded_valid)
  );

  // dec instance 4/4
  hit_decoder dec_3 (
    .ap_rst(ap_rst),
    .raw_hit(dec_3_raw_hit),
    .raw_valid(dec_3_raw_valid),
    .decoded_hit(net_dec_3_decoded_hit),
    .decoded_valid(net_dec_3_decoded_valid)
  );

  // col instance 1/1
  hit_collector col (
    .ap_rst(ap_rst),
    .in_hit_0(net_dec_0_decoded_hit),
    .in_hit_1(net_dec_1_decoded_hit),
    .in_hit_2(net_dec_2_decoded_hit),
    .in_hit_3(net_dec_3_decoded_hit),
    .in_valid_0(net_dec_0_decoded_valid),
    .in_valid_1(net_dec_1_decoded_valid),
    .in_valid_2(net_dec_2_decoded_valid),
    .in_valid_3(net_dec_3_decoded_valid),
    .n_hits(net_col_n_hits),
    .phi_sum(net_col_phi_sum),
    .collector_valid(net_col_collector_valid)
  );

  // trig instance 1/1
  trigger_logic trig (
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .n_hits(reg_net_col_trig_n_hits),
    .phi_sum(reg_net_col_trig_phi_sum),
    .in_valid(reg_net_col_trig_collector_valid),
    .trigger_accept(net_trig_trigger_accept),
    .trigger_quality(net_trig_trigger_quality),
    .trigger_valid(net_trig_trigger_valid)
  );

  // partmon instance 1/1
  decoded_partition_sink partmon (
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .lower_hit_0(net_dec_0_decoded_hit),
    .lower_hit_1(net_dec_1_decoded_hit),
    .lower_valid_0(net_dec_0_decoded_valid),
    .lower_valid_1(net_dec_1_decoded_valid),
    .upper_hit_0(net_dec_2_decoded_hit),
    .upper_hit_1(net_dec_3_decoded_hit),
    .upper_valid_0(net_dec_2_decoded_valid),
    .upper_valid_1(net_dec_3_decoded_valid)
  );

  // tfan instance 1/1
  trigger_fanout tfan (
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .trigger_accept(delay_net_trig_tfan_trigger_accept),
    .trigger_quality(delay_net_trig_tfan_trigger_quality),
    .trigger_valid(delay_net_trig_tfan_trigger_valid),
    .accept_lane_0(net_tfan_accept_lane_0),
    .accept_lane_1(net_tfan_accept_lane_1),
    .quality_lane_0(net_tfan_quality_lane_0),
    .quality_lane_1(net_tfan_quality_lane_1),
    .valid_lane_0(net_tfan_valid_lane_0),
    .valid_lane_1(net_tfan_valid_lane_1)
  );

  // tsink instance 1/1
  trigger_contract_sink tsink (
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .accept_lane_0(net_tfan_accept_lane_0),
    .accept_lane_1(net_tfan_accept_lane_1),
    .quality_lane_0(net_tfan_quality_lane_0),
    .quality_lane_1(net_tfan_quality_lane_1),
    .valid_lane_0(net_tfan_valid_lane_0),
    .valid_lane_1(net_tfan_valid_lane_1),
    .trigger_accept(net_tsink_trigger_accept),
    .trigger_quality(net_tsink_trigger_quality),
    .trigger_valid(net_tsink_trigger_valid)
  );

  // tout instance 1/1
  trigger_output tout (
    .ap_rst(ap_rst),
    .trigger_accept(net_tsink_trigger_accept),
    .trigger_quality(net_tsink_trigger_quality),
    .trigger_valid(net_tsink_trigger_valid),
    .trigger_word(net_tout_trigger_word),
    .out_valid(net_tout_out_valid)
  );

  // Top-level bindings for exported producer outputs
  assign tout_trigger_word = net_tout_trigger_word;
  assign tout_out_valid = net_tout_out_valid;

  // Register stages for pipelined connections
  // Pipeline col.n_hits → trig (2 stages)
  RegisterStage #(
    .DATAWIDTH(3),
    .STAGES(2)
  ) reg_stage_0 (
    .clk(ap_clk),
    .data_in(net_col_n_hits),
    .data_out(reg_net_col_trig_n_hits)
  );

  // Pipeline col.phi_sum → trig (2 stages)
  RegisterStage #(
    .DATAWIDTH(16),
    .STAGES(2)
  ) reg_stage_1 (
    .clk(ap_clk),
    .data_in(net_col_phi_sum),
    .data_out(reg_net_col_trig_phi_sum)
  );

  // Pipeline col.collector_valid → trig (2 stages)
  RegisterStage #(
    .DATAWIDTH(1),
    .STAGES(2)
  ) reg_stage_2 (
    .clk(ap_clk),
    .data_in(net_col_collector_valid),
    .data_out(reg_net_col_trig_collector_valid)
  );

  // Signal delays for connection timing alignment
  // Delay trig.trigger_accept → tfan (+3 cycles)
  signal_delay #(
    .WIDTH(1),
    .DEPTH(3)
  ) delay_0 (
    .clk(ap_clk),
    .rst(ap_rst),
    .din(net_trig_trigger_accept),
    .dout(delay_net_trig_tfan_trigger_accept)
  );

  // Delay trig.trigger_quality → tfan (+3 cycles)
  signal_delay #(
    .WIDTH(8),
    .DEPTH(3)
  ) delay_1 (
    .clk(ap_clk),
    .rst(ap_rst),
    .din(net_trig_trigger_quality),
    .dout(delay_net_trig_tfan_trigger_quality)
  );

  // Delay trig.trigger_valid → tfan (+3 cycles)
  signal_delay #(
    .WIDTH(1),
    .DEPTH(3)
  ) delay_2 (
    .clk(ap_clk),
    .rst(ap_rst),
    .din(net_trig_trigger_valid),
    .dout(delay_net_trig_tfan_trigger_valid)
  );

  // Control signal distribution with delays
  // Output alignment delays
endmodule