// ============================================================
// tb_bindings.svh — Generated by arc gen-top
// Top module   : algo_top
// Port sig hash: 5334c6f79077de61
// DO NOT EDIT — regenerate: arc gen-top ...
// ============================================================

// -- Outputs (wire — driven by DUT) --
// other
wire tout_out_valid;
wire [31:0] tout_trigger_word;

// -- Unclassified DUT ports --
logic ap_clk;
logic ap_rst;
logic [31:0] dec_0_raw_hit;
logic dec_0_raw_valid;
logic [31:0] dec_1_raw_hit;
logic dec_1_raw_valid;
logic [31:0] dec_2_raw_hit;
logic dec_2_raw_valid;
logic [31:0] dec_3_raw_hit;
logic dec_3_raw_valid;

// -- Simulation helpers (not DUT ports) --
integer cycle_count;
integer out_csv_fd;
integer probe_csv_fd;

